/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { assetsDownloadAsset } from "../../funcs/assetsDownloadAsset.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  resourceType: components.ResourceType$inboundSchema,
  publicId: z.string(),
  format: z.string().optional(),
  type: components.StorageType$inboundSchema.optional(),
  expiresAt: z.number().int().optional(),
  attachment: z.boolean().default(false),
  targetFilename: z.string().optional(),
  transformation: z.string().optional(),
  apiKey: z.string().optional(),
  signature: z.string().optional(),
  timestamp: z.number().int().optional(),
};

export const tool$assetsDownloadAsset: ToolDefinition<typeof args> = {
  name: "download-asset",
  description: `Generates a download link for a specific asset (image)`,
  scopes: ["admin"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsDownloadAsset(
      client,
      args.resourceType,
      args.publicId,
      args.format,
      args.type,
      args.expiresAt,
      args.attachment,
      args.targetFilename,
      args.transformation,
      args.apiKey,
      args.signature,
      args.timestamp,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
