/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsListResourceTags } from "../../funcs/assetsListResourceTags.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListResourceTagsRequest$inboundSchema,
};

export const tool$assetsListResourceTags: ToolDefinition<typeof args> = {
  name: "assets-list-resource-tags",
  description: `Get tags

Retrieves a comprehensive list of all tags that exist in your product environment for assets of the specified type.

[Cloudinary Admin API documentation](https://cloudinary.com/documentation/admin_api)
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsListResourceTags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
