/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsRestoreResourcesByAssetIDs } from "../../funcs/assetsRestoreResourcesByAssetIDs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RestoreResourcesByAssetIDsRequest$inboundSchema,
};

export const tool$assetsRestoreResourcesByAssetIDs: ToolDefinition<
  typeof args
> = {
  name: "assets-restore-resources-by-asset-I-ds",
  description: `Restore assets

Restores one or more resources from backup using their asset IDs. Can optionally specify versions to restore.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsRestoreResourcesByAssetIDs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
