/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetMetadataUpdateAssetsMetadata } from "../../funcs/assetMetadataUpdateAssetsMetadata.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  resourceType: components.ResourceType$inboundSchema,
  metadataUpdateRequest: components.MetadataUpdateRequest$inboundSchema,
};

export const tool$assetMetadataUpdateAssetsMetadata: ToolDefinition<
  typeof args
> = {
  name: "manage-asset-metadata",
  description: `Sets structured metadata values on multiple assets

Assigns structured metadata field values to the given assets, addressing them by public ID.

Values are merged into each asset's existing structured metadata: fields not mentioned
keep their current values, and an empty value clears the field. Every referenced field
must already exist in the product environment. Conditional metadata rules are evaluated
as part of the update.
`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetMetadataUpdateAssetsMetadata(
      client,
      args.resourceType,
      args.metadataUpdateRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
