/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupsDeleteBackupVersions } from "../../funcs/backupsDeleteBackupVersions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteBackupVersionsRequest$inboundSchema,
};

export const tool$backupsDeleteBackupVersions: ToolDefinition<typeof args> = {
  name: "backups-delete-backup-versions",
  description: `Delete backed up versions

Deletes specific backed up versions of an asset identified by asset ID.
This operation is irreversible and deleted versions cannot be recovered.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await backupsDeleteBackupVersions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
