/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { explodeExplodeResource } from "../../funcs/explodeExplodeResource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ExplodeResourceRequest$inboundSchema,
};

export const tool$explodeExplodeResource: ToolDefinition<typeof args> = {
  name: "explode-explode-resource",
  description: `Create derived images from multi-page file

Generates derived images for each of the individual pages/frames in a multi-page/frame file (such as a PDF or animated image).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await explodeExplodeResource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
