/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moderationsListResourcesByModerationKindAndStatus } from "../../funcs/moderationsListResourcesByModerationKindAndStatus.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.ListResourcesByModerationKindAndStatusRequest$inboundSchema,
};

export const tool$moderationsListResourcesByModerationKindAndStatus:
  ToolDefinition<typeof args> = {
    name: "moderations-list-resources-by-moderation-kind-and-status",
    description: `Get resources by moderation kind and status

Retrieves resources matching specific moderation kind and status.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await moderationsListResourcesByModerationKindAndStatus(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
