/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videoAnalyticsGetVideoViews } from "../../funcs/videoAnalyticsGetVideoViews.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetVideoViewsRequest$inboundSchema,
};

export const tool$videoAnalyticsGetVideoViews: ToolDefinition<typeof args> = {
  name: "video-analytics-get-video-views",
  description: `Get video views

Retrieves analytics data for video views. Results can be filtered using expressions based on various criteria
such as video public ID, view duration, viewer information, and more.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videoAnalyticsGetVideoViews(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
