/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupsDeleteBackupVersions } from "../funcs/backupsDeleteBackupVersions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Backups extends ClientSDK {
  /**
   * Delete backed up versions
   *
   * @remarks
   * Deletes specific backed up versions of an asset identified by asset ID.
   * This operation is irreversible and deleted versions cannot be recovered.
   */
  async deleteBackupVersions(
    request: operations.DeleteBackupVersionsRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteBackupVersionsResponse> {
    return unwrapAsync(backupsDeleteBackupVersions(
      this,
      request,
      options,
    ));
  }
}
