/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { foldersAssignFolderRoles } from "../funcs/foldersAssignFolderRoles.js";
import { foldersCreateFolder } from "../funcs/foldersCreateFolder.js";
import { foldersDestroyFolder } from "../funcs/foldersDestroyFolder.js";
import { foldersGetFolderById } from "../funcs/foldersGetFolderById.js";
import { foldersGetFolderByPath } from "../funcs/foldersGetFolderByPath.js";
import { foldersGetFolderDescendants } from "../funcs/foldersGetFolderDescendants.js";
import { foldersGetFolderRoles } from "../funcs/foldersGetFolderRoles.js";
import { foldersListRootFolders } from "../funcs/foldersListRootFolders.js";
import { foldersRenameFolderOperation } from "../funcs/foldersRenameFolderOperation.js";
import { foldersSearchFolders } from "../funcs/foldersSearchFolders.js";
import { foldersSearchFoldersPost } from "../funcs/foldersSearchFoldersPost.js";
import { foldersShowFolder } from "../funcs/foldersShowFolder.js";
import { foldersUpdateFolder } from "../funcs/foldersUpdateFolder.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Folders extends ClientSDK {
  /**
   * List sub-folders
   *
   * @remarks
   * Returns a list of sub-folders under the specified folder path.
   */
  async showFolder(
    folder: string,
    options?: RequestOptions,
  ): Promise<components.FoldersListResponse> {
    return unwrapAsync(foldersShowFolder(
      this,
      folder,
      options,
    ));
  }

  /**
   * Renames or moves an entire folder (along with all assets it contains) to a new location
   *
   * @remarks
   * Renames or moves an entire folder (along with all assets it contains) to a new location within your Cloudinary media library.
   */
  async updateFolder(
    folder: string,
    moveFolderRequest: components.MoveFolderRequest,
    options?: RequestOptions,
  ): Promise<components.MoveFolderResponse> {
    return unwrapAsync(foldersUpdateFolder(
      this,
      folder,
      moveFolderRequest,
      options,
    ));
  }

  /**
   * Creates a new empty folder in your Cloudinary media library
   *
   * @remarks
   * Creates a new folder at the specified path
   */
  async createFolder(
    folder: string,
    options?: RequestOptions,
  ): Promise<components.CreateFolderResponse> {
    return unwrapAsync(foldersCreateFolder(
      this,
      folder,
      options,
    ));
  }

  /**
   * Deletes an existing folder from your media library
   *
   * @remarks
   * Deletes a folder and all assets within it.
   */
  async destroyFolder(
    folder: string,
    options?: RequestOptions,
  ): Promise<components.DeleteFolderResponse> {
    return unwrapAsync(foldersDestroyFolder(
      this,
      folder,
      options,
    ));
  }

  /**
   * Get root folders
   *
   * @remarks
   * Retrieves an array of all root folders in your Cloudinary product environment. Limited to 2000 results.
   */
  async listRootFolders(
    request: operations.ListRootFoldersRequest,
    options?: RequestOptions,
  ): Promise<components.FoldersListResponse> {
    return unwrapAsync(foldersListRootFolders(
      this,
      request,
      options,
    ));
  }

  /**
   * Searches for folders whose attributes match a given expression
   *
   * @remarks
   * Lists the folders that match the specified search expression. Limited to 2000 results. If no parameters are passed, returns the 50 most recently created folders in descending order of creation time.
   */
  async searchFolders(
    expression?: string | undefined,
    sortBy?: Array<{ [k: string]: components.DirectionEnum }> | undefined,
    maxResults?: number | undefined,
    nextCursor?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.FoldersSearchResponse> {
    return unwrapAsync(foldersSearchFolders(
      this,
      expression,
      sortBy,
      maxResults,
      nextCursor,
      options,
    ));
  }

  /**
   * Searches for folders in your product environment
   *
   * @remarks
   * Lists the folders that match the specified search expression. Limited to 2000 results. If no parameters are passed, returns the 50 most recently created folders in descending order of creation time.
   */
  async searchFoldersPost(
    request: components.FolderSearchRequest,
    options?: RequestOptions,
  ): Promise<components.FoldersSearchResponse> {
    return unwrapAsync(foldersSearchFoldersPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get folder roles
   *
   * @remarks
   * Lists the principals (users, groups, or API keys) and their role assignments on a specific folder, including roles inherited from ancestor folders.
   */
  async getFolderRoles(
    folderId: string,
    permittedRoles?: boolean | undefined,
    options?: RequestOptions,
  ): Promise<components.FolderRolesResponse> {
    return unwrapAsync(foldersGetFolderRoles(
      this,
      folderId,
      permittedRoles,
      options,
    ));
  }

  /**
   * Assign folder roles
   *
   * @remarks
   * Assigns or removes folder roles for a principal (user, group, or API key).
   * Supports all system folder roles (see [System roles reference](https://cloudinary.com/documentation/permissions_system_roles_policies#folder_roles)).
   * Enterprise customers can also assign custom roles by ID.
   * Note: Assigning roles to users or groups via this endpoint requires their user or group IDs, which are available through the Provisioning API (Enterprise only). Free customers can use this endpoint to assign roles only to API keys, but can assign folder roles to users and groups through the UI.
   */
  async assignFolderRoles(
    folderId: string,
    assignFolderRolesRequest: components.AssignFolderRolesRequest,
    options?: RequestOptions,
  ): Promise<components.SuccessResponse> {
    return unwrapAsync(foldersAssignFolderRoles(
      this,
      folderId,
      assignFolderRolesRequest,
      options,
    ));
  }

  /**
   * Rename or move a folder
   *
   * @remarks
   * Renames or moves the folder at the specified path, along with all the assets it contains, to a new path.
   */
  async renameFolderOperation(
    request: components.FolderRenameRequest,
    options?: RequestOptions,
  ): Promise<components.FolderRenameResponse> {
    return unwrapAsync(foldersRenameFolderOperation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a folder by its identifier
   *
   * @remarks
   * Returns the details of the folder with the specified identifier, including its ancestors.
   */
  async getFolderById(
    request: components.FolderByIdRequest,
    options?: RequestOptions,
  ): Promise<components.FolderDetailResponse> {
    return unwrapAsync(foldersGetFolderById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a folder by its path
   *
   * @remarks
   * Returns the details of the folder at the specified path, including its ancestors.
   */
  async getFolderByPath(
    request: components.FolderByPathRequest,
    options?: RequestOptions,
  ): Promise<components.FolderDetailResponse> {
    return unwrapAsync(foldersGetFolderByPath(
      this,
      request,
      options,
    ));
  }

  /**
   * Get the descendants of a folder
   *
   * @remarks
   * Returns the descendant folders of the folder with the specified identifier, optionally filtered to a set of folder identifiers.
   */
  async getFolderDescendants(
    request: components.FolderDescendantsRequest,
    options?: RequestOptions,
  ): Promise<components.FolderDescendantsResponse> {
    return unwrapAsync(foldersGetFolderDescendants(
      this,
      request,
      options,
    ));
  }
}
