/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generationGenerateImage } from "../funcs/generationGenerateImage.js";
import { generationGenerateImageFromImages } from "../funcs/generationGenerateImageFromImages.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Generation extends ClientSDK {
  /**
   * Generate an image
   *
   * @remarks
   * Generate an image from a text prompt using AI models.
   *
   * The model is selected via the optional `model` object:
   * 1. If `model.id` is provided, use that exact model.
   * 2. Else if `model.family` (+ optional `model.tier`) is provided, resolve via the model registry; a missing tier defaults to `standard`.
   * 3. If `model` is omitted, use the global default (nano-banana / premium, i.e. `nano-banana-2`).
   */
  async generateImage(
    request: components.GenerateImageRequest,
    options?: RequestOptions,
  ): Promise<operations.GenerateImageResponse> {
    return unwrapAsync(generationGenerateImage(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate an image from reference images
   *
   * @remarks
   * Generate an image guided by one or more **reference images** — restyle,
   * on-brand variants, character consistency, virtual try-on, edit/extend —
   * steered by `prompt`.
   *
   * Only edit-capable models are selectable here. The model is selected via
   * the optional `model` object, exactly like `text_to_image`, but IDs are
   * restricted to edit models:
   * 1. If `model.id` is provided, use that exact edit model.
   * 2. Else if `model.family` (+ optional `model.tier`) is provided, resolve
   *
   *    to that family's edit model (e.g. `nano-banana` / `premium` →
   *    `nano-banana-2-edit`).
   * 3. If `model` is omitted, use the default edit model (`nano-banana-2-edit`).
   *
   * Each reference image is either a stored managed asset (by `asset_id`,
   * read-permission checked) or an external HTTPS `url`.
   */
  async generateImageFromImages(
    request: components.ImageToImageRequest,
    options?: RequestOptions,
  ): Promise<operations.GenerateImageFromImagesResponse> {
    return unwrapAsync(generationGenerateImageFromImages(
      this,
      request,
      options,
    ));
  }
}
