/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moderationsListResourcesByModerationKindAndStatus } from "../funcs/moderationsListResourcesByModerationKindAndStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Moderations extends ClientSDK {
  /**
   * Get resources by moderation kind and status
   *
   * @remarks
   * Retrieves resources matching specific moderation kind and status.
   */
  async listResourcesByModerationKindAndStatus(
    request: operations.ListResourcesByModerationKindAndStatusRequest,
    options?: RequestOptions,
  ): Promise<components.ListResponse> {
    return unwrapAsync(moderationsListResourcesByModerationKindAndStatus(
      this,
      request,
      options,
    ));
  }
}
