/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peopleGetPerson } from "../funcs/peopleGetPerson.js";
import { peopleInspectPeoplePermissions } from "../funcs/peopleInspectPeoplePermissions.js";
import { peopleListPeople } from "../funcs/peopleListPeople.js";
import { peopleUpdatePerson } from "../funcs/peopleUpdatePerson.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class People extends ClientSDK {
  /**
   * List recognized people
   *
   * @remarks
   * Returns a list of all recognized people in your product environment.
   * People Search must be enabled for this product environment.
   */
  async listPeople(
    maxResults?: number | undefined,
    nextCursor?: string | undefined,
    nameStatus?: operations.NameStatus | undefined,
    namePrefix?: string | undefined,
    status?: components.PersonStatus | undefined,
    sortBy?: operations.ListPeopleSortBy | undefined,
    direction?: components.DirectionEnum | undefined,
    options?: RequestOptions,
  ): Promise<components.PeopleListResponse> {
    return unwrapAsync(peopleListPeople(
      this,
      maxResults,
      nextCursor,
      nameStatus,
      namePrefix,
      status,
      sortBy,
      direction,
      options,
    ));
  }

  /**
   * Get person details
   *
   * @remarks
   * Returns details of a specific recognized person.
   * People Search must be enabled for this product environment.
   */
  async getPerson(
    personId: string,
    options?: RequestOptions,
  ): Promise<components.PersonResponse> {
    return unwrapAsync(peopleGetPerson(
      this,
      personId,
      options,
    ));
  }

  /**
   * Update a person
   *
   * @remarks
   * Updates a recognized person's name, status, or thumbnail image.
   * At least one of name, status, or thumbnail_asset_id must be provided.
   * People Search must be enabled for this product environment.
   */
  async updatePerson(
    personId: string,
    updatePersonRequest: components.UpdatePersonRequest,
    options?: RequestOptions,
  ): Promise<components.UpdatePersonResponse> {
    return unwrapAsync(peopleUpdatePerson(
      this,
      personId,
      updatePersonRequest,
      options,
    ));
  }

  /**
   * Inspect the caller's permitted actions on people
   *
   * @remarks
   * Returns, for each requested person and action, whether the authenticated caller is permitted to perform that action.
   */
  async inspectPeoplePermissions(
    request: components.PeopleInspectRequest,
    options?: RequestOptions,
  ): Promise<components.PeopleInspectResponse> {
    return unwrapAsync(peopleInspectPeoplePermissions(
      this,
      request,
      options,
    ));
  }
}
