/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchSearchAssets } from "../funcs/searchSearchAssets.js";
import { searchVisualSearchAssets } from "../funcs/searchVisualSearchAssets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Provides a powerful query interface to filter and retrieve assets and their details
   *
   * @remarks
   * Returns a list of resources matching the specified search criteria.
   *
   * Uses a Lucene-like query language to filter assets by descriptive attributes (`public_id`, `asset_id`, `filename`, `display_name`, `folder` / `asset_folder`, `tags`, `context.<key>`), file details (`resource_type`, `type`, `format`, `bytes`, `width`, `height`, `duration`, `pages`, `aspect_ratio`, `transparent`, `grayscale`), lifecycle dates (`uploaded_at`, `created_at`, `taken_at`, `updated_at`, `last_updated.<kind>`), moderation and lifecycle state (`status`, `moderation_status`, `moderation_kind`), embedded data (`image_metadata.*`), structured metadata (`metadata.<external_id>`), and analysis fields (`face_count`, `colors`, `quality_score`, `illustration_score`, `accessibility_analysis.*`). Supports sorting, aggregate counts, and complex boolean expressions.
   *
   * Examples: `tags:shirt AND uploaded_at>1d`, `resource_type:image AND bytes>1000000`, `folder:products OR context.category:electronics`. See the [search expressions guide](https://cloudinary.com/documentation/search_expressions.md) for the full syntax and field reference.
   */
  async searchAssets(
    request: components.SearchParameters,
    options?: RequestOptions,
  ): Promise<components.SearchResponse> {
    return unwrapAsync(searchSearchAssets(
      this,
      request,
      options,
    ));
  }

  /**
   * Finds images in your asset library based on visual similarity or content
   *
   * @remarks
   * Returns a list of resources that are visually similar to a specified image. You can provide the source image for comparison in one of three ways:
   * - Provide a URL of an image
   * - Specify the asset ID of an existing image
   * - Provide a textual description
   */
  async visualSearchAssets(
    request: components.VisualSearchParametersUnion,
    options?: RequestOptions,
  ): Promise<components.SearchResponse> {
    return unwrapAsync(searchVisualSearchAssets(
      this,
      request,
      options,
    ));
  }
}
