/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsListResourceTags } from "../funcs/tagsListResourceTags.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tags extends ClientSDK {
  /**
   * Get tags
   *
   * @remarks
   * Retrieves a comprehensive list of all tags that exist in your product environment for assets of the specified type.
   *
   * [Cloudinary Admin API documentation](https://cloudinary.com/documentation/admin_api)
   */
  async listResourceTags(
    request: operations.ListResourceTagsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListResourceTagsResponse> {
    return unwrapAsync(tagsListResourceTags(
      this,
      request,
      options,
    ));
  }
}
