workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Asset Management API:
        inputs:
            - location: https://cloudinary.github.io/api-schemas/asset-management/schema.yml
        overlays:
            - location: https://cloudinary.github.io/api-schemas/overlays/security-scheme-cloud-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/overlays/cloud-name-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/mcp-disabled.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/remove-mcp-description.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/signature-optional-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/asset-management/overlays/remove-multipart-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/asset-management/overlays/create-only-archive-mode-overlay.yml
        registry:
            location: registry.speakeasyapi.dev/cloudinary/cloudinary/asset-management-api
targets:
    asset-management-js:
        target: typescript
        source: Asset Management API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cloudinary/cloudinary/asset-management-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
