/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConcatGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

/** @internal */
export const ConcatGlobals$inboundSchema: z.ZodType<
  ConcatGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type ConcatGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const ConcatGlobals$outboundSchema: z.ZodType<
  ConcatGlobals$Outbound,
  z.ZodTypeDef,
  ConcatGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function concatGlobalsToJSON(concatGlobals: ConcatGlobals): string {
  return JSON.stringify(ConcatGlobals$outboundSchema.parse(concatGlobals));
}
export function concatGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ConcatGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConcatGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConcatGlobals' from JSON`,
  );
}
