/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteBackupVersionsGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type DeleteBackupVersionsRequest = {
  /**
   * The asset ID of the resource. Must be a 32-character hexadecimal string.
   */
  assetId: string;
  /**
   * The asset IDs and version IDs to delete.
   */
  deleteBackupVersionsRequest: components.DeleteBackupVersionsRequest;
};

export type DeleteBackupVersionsResponse =
  | components.DeleteBackupVersionsResponse
  | components.DeleteBackupVersionsPartialResponse;

/** @internal */
export const DeleteBackupVersionsGlobals$inboundSchema: z.ZodType<
  DeleteBackupVersionsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type DeleteBackupVersionsGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const DeleteBackupVersionsGlobals$outboundSchema: z.ZodType<
  DeleteBackupVersionsGlobals$Outbound,
  z.ZodTypeDef,
  DeleteBackupVersionsGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function deleteBackupVersionsGlobalsToJSON(
  deleteBackupVersionsGlobals: DeleteBackupVersionsGlobals,
): string {
  return JSON.stringify(
    DeleteBackupVersionsGlobals$outboundSchema.parse(
      deleteBackupVersionsGlobals,
    ),
  );
}
export function deleteBackupVersionsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBackupVersionsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBackupVersionsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBackupVersionsGlobals' from JSON`,
  );
}

/** @internal */
export const DeleteBackupVersionsRequest$inboundSchema: z.ZodType<
  DeleteBackupVersionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_id: z.string(),
  delete_backup_versions_request:
    components.DeleteBackupVersionsRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "asset_id": "assetId",
    "delete_backup_versions_request": "deleteBackupVersionsRequest",
  });
});
/** @internal */
export type DeleteBackupVersionsRequest$Outbound = {
  asset_id: string;
  delete_backup_versions_request:
    components.DeleteBackupVersionsRequest$Outbound;
};

/** @internal */
export const DeleteBackupVersionsRequest$outboundSchema: z.ZodType<
  DeleteBackupVersionsRequest$Outbound,
  z.ZodTypeDef,
  DeleteBackupVersionsRequest
> = z.object({
  assetId: z.string(),
  deleteBackupVersionsRequest:
    components.DeleteBackupVersionsRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    assetId: "asset_id",
    deleteBackupVersionsRequest: "delete_backup_versions_request",
  });
});

export function deleteBackupVersionsRequestToJSON(
  deleteBackupVersionsRequest: DeleteBackupVersionsRequest,
): string {
  return JSON.stringify(
    DeleteBackupVersionsRequest$outboundSchema.parse(
      deleteBackupVersionsRequest,
    ),
  );
}
export function deleteBackupVersionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBackupVersionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBackupVersionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBackupVersionsRequest' from JSON`,
  );
}

/** @internal */
export const DeleteBackupVersionsResponse$inboundSchema: z.ZodType<
  DeleteBackupVersionsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.DeleteBackupVersionsResponse$inboundSchema,
  components.DeleteBackupVersionsPartialResponse$inboundSchema,
]);
/** @internal */
export type DeleteBackupVersionsResponse$Outbound =
  | components.DeleteBackupVersionsResponse$Outbound
  | components.DeleteBackupVersionsPartialResponse$Outbound;

/** @internal */
export const DeleteBackupVersionsResponse$outboundSchema: z.ZodType<
  DeleteBackupVersionsResponse$Outbound,
  z.ZodTypeDef,
  DeleteBackupVersionsResponse
> = z.union([
  components.DeleteBackupVersionsResponse$outboundSchema,
  components.DeleteBackupVersionsPartialResponse$outboundSchema,
]);

export function deleteBackupVersionsResponseToJSON(
  deleteBackupVersionsResponse: DeleteBackupVersionsResponse,
): string {
  return JSON.stringify(
    DeleteBackupVersionsResponse$outboundSchema.parse(
      deleteBackupVersionsResponse,
    ),
  );
}
export function deleteBackupVersionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBackupVersionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBackupVersionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBackupVersionsResponse' from JSON`,
  );
}
