/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExplicitAssetGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type ExplicitAssetRequest = {
  /**
   * The type of resource (image, video, or raw).
   */
  resourceType: components.ResourceType;
  /**
   * The asset and operations to apply.
   */
  explicitRequest: components.ExplicitRequest;
};

/** @internal */
export const ExplicitAssetGlobals$inboundSchema: z.ZodType<
  ExplicitAssetGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type ExplicitAssetGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const ExplicitAssetGlobals$outboundSchema: z.ZodType<
  ExplicitAssetGlobals$Outbound,
  z.ZodTypeDef,
  ExplicitAssetGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function explicitAssetGlobalsToJSON(
  explicitAssetGlobals: ExplicitAssetGlobals,
): string {
  return JSON.stringify(
    ExplicitAssetGlobals$outboundSchema.parse(explicitAssetGlobals),
  );
}
export function explicitAssetGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitAssetGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExplicitAssetGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitAssetGlobals' from JSON`,
  );
}

/** @internal */
export const ExplicitAssetRequest$inboundSchema: z.ZodType<
  ExplicitAssetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: components.ResourceType$inboundSchema,
  explicit_request: components.ExplicitRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "explicit_request": "explicitRequest",
  });
});
/** @internal */
export type ExplicitAssetRequest$Outbound = {
  resource_type: string;
  explicit_request: components.ExplicitRequest$Outbound;
};

/** @internal */
export const ExplicitAssetRequest$outboundSchema: z.ZodType<
  ExplicitAssetRequest$Outbound,
  z.ZodTypeDef,
  ExplicitAssetRequest
> = z.object({
  resourceType: components.ResourceType$outboundSchema,
  explicitRequest: components.ExplicitRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    explicitRequest: "explicit_request",
  });
});

export function explicitAssetRequestToJSON(
  explicitAssetRequest: ExplicitAssetRequest,
): string {
  return JSON.stringify(
    ExplicitAssetRequest$outboundSchema.parse(explicitAssetRequest),
  );
}
export function explicitAssetRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitAssetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExplicitAssetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitAssetRequest' from JSON`,
  );
}
