/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListPeopleGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

/**
 * Filter by whether the person has been named. Default: all.
 */
export const NameStatus = {
  All: "all",
  Named: "named",
  Unnamed: "unnamed",
} as const;
/**
 * Filter by whether the person has been named. Default: all.
 */
export type NameStatus = ClosedEnum<typeof NameStatus>;

/**
 * The field to sort results by. Default: name (ascending).
 *
 * @remarks
 */
export const ListPeopleSortBy = {
  Name: "name",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field to sort results by. Default: name (ascending).
 *
 * @remarks
 */
export type ListPeopleSortBy = ClosedEnum<typeof ListPeopleSortBy>;

export type ListPeopleRequest = {
  /**
   * The maximum number of people to return. Default: 50.
   */
  maxResults?: number | undefined;
  /**
   * The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.
   */
  nextCursor?: string | undefined;
  /**
   * Filter by whether the person has been named. Default: all.
   */
  nameStatus?: NameStatus | undefined;
  /**
   * Filter people whose names start with the given prefix (case insensitive).
   */
  namePrefix?: string | undefined;
  /**
   * Filter by person status.
   */
  status?: components.PersonStatus | undefined;
  /**
   * The field to sort results by. Default: name (ascending).
   *
   * @remarks
   */
  sortBy?: ListPeopleSortBy | undefined;
  /**
   * The sort direction for the results. Default is "desc".
   */
  direction?: components.DirectionEnum | undefined;
};

/** @internal */
export const ListPeopleGlobals$inboundSchema: z.ZodType<
  ListPeopleGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type ListPeopleGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const ListPeopleGlobals$outboundSchema: z.ZodType<
  ListPeopleGlobals$Outbound,
  z.ZodTypeDef,
  ListPeopleGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function listPeopleGlobalsToJSON(
  listPeopleGlobals: ListPeopleGlobals,
): string {
  return JSON.stringify(
    ListPeopleGlobals$outboundSchema.parse(listPeopleGlobals),
  );
}
export function listPeopleGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListPeopleGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPeopleGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPeopleGlobals' from JSON`,
  );
}

/** @internal */
export const NameStatus$inboundSchema: z.ZodNativeEnum<typeof NameStatus> = z
  .nativeEnum(NameStatus);
/** @internal */
export const NameStatus$outboundSchema: z.ZodNativeEnum<typeof NameStatus> =
  NameStatus$inboundSchema;

/** @internal */
export const ListPeopleSortBy$inboundSchema: z.ZodNativeEnum<
  typeof ListPeopleSortBy
> = z.nativeEnum(ListPeopleSortBy);
/** @internal */
export const ListPeopleSortBy$outboundSchema: z.ZodNativeEnum<
  typeof ListPeopleSortBy
> = ListPeopleSortBy$inboundSchema;

/** @internal */
export const ListPeopleRequest$inboundSchema: z.ZodType<
  ListPeopleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_results: z.number().int().default(50),
  next_cursor: z.string().optional(),
  name_status: NameStatus$inboundSchema.default("all"),
  name_prefix: z.string().optional(),
  status: components.PersonStatus$inboundSchema.optional(),
  sort_by: ListPeopleSortBy$inboundSchema.default("name"),
  direction: components.DirectionEnum$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "max_results": "maxResults",
    "next_cursor": "nextCursor",
    "name_status": "nameStatus",
    "name_prefix": "namePrefix",
    "sort_by": "sortBy",
  });
});
/** @internal */
export type ListPeopleRequest$Outbound = {
  max_results: number;
  next_cursor?: string | undefined;
  name_status: string;
  name_prefix?: string | undefined;
  status?: string | undefined;
  sort_by: string;
  direction?: string | undefined;
};

/** @internal */
export const ListPeopleRequest$outboundSchema: z.ZodType<
  ListPeopleRequest$Outbound,
  z.ZodTypeDef,
  ListPeopleRequest
> = z.object({
  maxResults: z.number().int().default(50),
  nextCursor: z.string().optional(),
  nameStatus: NameStatus$outboundSchema.default("all"),
  namePrefix: z.string().optional(),
  status: components.PersonStatus$outboundSchema.optional(),
  sortBy: ListPeopleSortBy$outboundSchema.default("name"),
  direction: components.DirectionEnum$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    maxResults: "max_results",
    nextCursor: "next_cursor",
    nameStatus: "name_status",
    namePrefix: "name_prefix",
    sortBy: "sort_by",
  });
});

export function listPeopleRequestToJSON(
  listPeopleRequest: ListPeopleRequest,
): string {
  return JSON.stringify(
    ListPeopleRequest$outboundSchema.parse(listPeopleRequest),
  );
}
export function listPeopleRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListPeopleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPeopleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPeopleRequest' from JSON`,
  );
}
