/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListRootFoldersGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type ListRootFoldersRequest = {};

/** @internal */
export const ListRootFoldersGlobals$inboundSchema: z.ZodType<
  ListRootFoldersGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type ListRootFoldersGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const ListRootFoldersGlobals$outboundSchema: z.ZodType<
  ListRootFoldersGlobals$Outbound,
  z.ZodTypeDef,
  ListRootFoldersGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function listRootFoldersGlobalsToJSON(
  listRootFoldersGlobals: ListRootFoldersGlobals,
): string {
  return JSON.stringify(
    ListRootFoldersGlobals$outboundSchema.parse(listRootFoldersGlobals),
  );
}
export function listRootFoldersGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListRootFoldersGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRootFoldersGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRootFoldersGlobals' from JSON`,
  );
}

/** @internal */
export const ListRootFoldersRequest$inboundSchema: z.ZodType<
  ListRootFoldersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ListRootFoldersRequest$Outbound = {};

/** @internal */
export const ListRootFoldersRequest$outboundSchema: z.ZodType<
  ListRootFoldersRequest$Outbound,
  z.ZodTypeDef,
  ListRootFoldersRequest
> = z.object({});

export function listRootFoldersRequestToJSON(
  listRootFoldersRequest: ListRootFoldersRequest,
): string {
  return JSON.stringify(
    ListRootFoldersRequest$outboundSchema.parse(listRootFoldersRequest),
  );
}
export function listRootFoldersRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListRootFoldersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRootFoldersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRootFoldersRequest' from JSON`,
  );
}
