/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListResourceTagsGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type ListResourceTagsRequest = {
  /**
   * The type of resource (image, video, or raw).
   */
  resourceType: components.ResourceType;
  /**
   * Limit the returned tags to those that start with the specified prefix.
   */
  prefix?: string | undefined;
  /**
   * Cursor for pagination.
   */
  nextCursor?: string | undefined;
  /**
   * Maximum number of results to return (1-500).
   */
  maxResults?: number | undefined;
};

/** @internal */
export const ListResourceTagsGlobals$inboundSchema: z.ZodType<
  ListResourceTagsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type ListResourceTagsGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const ListResourceTagsGlobals$outboundSchema: z.ZodType<
  ListResourceTagsGlobals$Outbound,
  z.ZodTypeDef,
  ListResourceTagsGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function listResourceTagsGlobalsToJSON(
  listResourceTagsGlobals: ListResourceTagsGlobals,
): string {
  return JSON.stringify(
    ListResourceTagsGlobals$outboundSchema.parse(listResourceTagsGlobals),
  );
}
export function listResourceTagsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceTagsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceTagsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceTagsGlobals' from JSON`,
  );
}

/** @internal */
export const ListResourceTagsRequest$inboundSchema: z.ZodType<
  ListResourceTagsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: components.ResourceType$inboundSchema,
  prefix: z.string().optional(),
  next_cursor: z.string().optional(),
  max_results: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "next_cursor": "nextCursor",
    "max_results": "maxResults",
  });
});
/** @internal */
export type ListResourceTagsRequest$Outbound = {
  resource_type: string;
  prefix?: string | undefined;
  next_cursor?: string | undefined;
  max_results?: number | undefined;
};

/** @internal */
export const ListResourceTagsRequest$outboundSchema: z.ZodType<
  ListResourceTagsRequest$Outbound,
  z.ZodTypeDef,
  ListResourceTagsRequest
> = z.object({
  resourceType: components.ResourceType$outboundSchema,
  prefix: z.string().optional(),
  nextCursor: z.string().optional(),
  maxResults: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    nextCursor: "next_cursor",
    maxResults: "max_results",
  });
});

export function listResourceTagsRequestToJSON(
  listResourceTagsRequest: ListResourceTagsRequest,
): string {
  return JSON.stringify(
    ListResourceTagsRequest$outboundSchema.parse(listResourceTagsRequest),
  );
}
export function listResourceTagsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceTagsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceTagsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceTagsRequest' from JSON`,
  );
}
