/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAssetsContextGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type UpdateAssetsContextRequest = {
  /**
   * The type of resource (image, video, or raw).
   */
  resourceType: components.ResourceType;
  /**
   * The context command, the metadata to apply, and the assets to apply it to.
   */
  contextUpdateRequest: components.ContextUpdateRequest;
};

/** @internal */
export const UpdateAssetsContextGlobals$inboundSchema: z.ZodType<
  UpdateAssetsContextGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type UpdateAssetsContextGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const UpdateAssetsContextGlobals$outboundSchema: z.ZodType<
  UpdateAssetsContextGlobals$Outbound,
  z.ZodTypeDef,
  UpdateAssetsContextGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function updateAssetsContextGlobalsToJSON(
  updateAssetsContextGlobals: UpdateAssetsContextGlobals,
): string {
  return JSON.stringify(
    UpdateAssetsContextGlobals$outboundSchema.parse(updateAssetsContextGlobals),
  );
}
export function updateAssetsContextGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAssetsContextGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAssetsContextGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAssetsContextGlobals' from JSON`,
  );
}

/** @internal */
export const UpdateAssetsContextRequest$inboundSchema: z.ZodType<
  UpdateAssetsContextRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: components.ResourceType$inboundSchema,
  context_update_request: components.ContextUpdateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "context_update_request": "contextUpdateRequest",
  });
});
/** @internal */
export type UpdateAssetsContextRequest$Outbound = {
  resource_type: string;
  context_update_request: components.ContextUpdateRequest$Outbound;
};

/** @internal */
export const UpdateAssetsContextRequest$outboundSchema: z.ZodType<
  UpdateAssetsContextRequest$Outbound,
  z.ZodTypeDef,
  UpdateAssetsContextRequest
> = z.object({
  resourceType: components.ResourceType$outboundSchema,
  contextUpdateRequest: components.ContextUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    contextUpdateRequest: "context_update_request",
  });
});

export function updateAssetsContextRequestToJSON(
  updateAssetsContextRequest: UpdateAssetsContextRequest,
): string {
  return JSON.stringify(
    UpdateAssetsContextRequest$outboundSchema.parse(updateAssetsContextRequest),
  );
}
export function updateAssetsContextRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAssetsContextRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAssetsContextRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAssetsContextRequest' from JSON`,
  );
}
