/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePersonGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type UpdatePersonRequest = {
  /**
   * The unique identifier of the person.
   */
  personId: string;
  /**
   * The updated person attributes.
   */
  updatePersonRequest: components.UpdatePersonRequest;
};

/** @internal */
export const UpdatePersonGlobals$inboundSchema: z.ZodType<
  UpdatePersonGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type UpdatePersonGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const UpdatePersonGlobals$outboundSchema: z.ZodType<
  UpdatePersonGlobals$Outbound,
  z.ZodTypeDef,
  UpdatePersonGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function updatePersonGlobalsToJSON(
  updatePersonGlobals: UpdatePersonGlobals,
): string {
  return JSON.stringify(
    UpdatePersonGlobals$outboundSchema.parse(updatePersonGlobals),
  );
}
export function updatePersonGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePersonGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePersonGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePersonGlobals' from JSON`,
  );
}

/** @internal */
export const UpdatePersonRequest$inboundSchema: z.ZodType<
  UpdatePersonRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  person_id: z.string(),
  update_person_request: components.UpdatePersonRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "person_id": "personId",
    "update_person_request": "updatePersonRequest",
  });
});
/** @internal */
export type UpdatePersonRequest$Outbound = {
  person_id: string;
  update_person_request: components.UpdatePersonRequest$Outbound;
};

/** @internal */
export const UpdatePersonRequest$outboundSchema: z.ZodType<
  UpdatePersonRequest$Outbound,
  z.ZodTypeDef,
  UpdatePersonRequest
> = z.object({
  personId: z.string(),
  updatePersonRequest: components.UpdatePersonRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    personId: "person_id",
    updatePersonRequest: "update_person_request",
  });
});

export function updatePersonRequestToJSON(
  updatePersonRequest: UpdatePersonRequest,
): string {
  return JSON.stringify(
    UpdatePersonRequest$outboundSchema.parse(updatePersonRequest),
  );
}
export function updatePersonRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePersonRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePersonRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePersonRequest' from JSON`,
  );
}
