/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAssetsMetadataGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type UpdateAssetsMetadataRequest = {
  /**
   * The type of resource (image, video, or raw).
   */
  resourceType: components.ResourceType;
  /**
   * The structured metadata values to assign and the assets to assign them to.
   */
  metadataUpdateRequest: components.MetadataUpdateRequest;
};

/** @internal */
export const UpdateAssetsMetadataGlobals$inboundSchema: z.ZodType<
  UpdateAssetsMetadataGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type UpdateAssetsMetadataGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const UpdateAssetsMetadataGlobals$outboundSchema: z.ZodType<
  UpdateAssetsMetadataGlobals$Outbound,
  z.ZodTypeDef,
  UpdateAssetsMetadataGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function updateAssetsMetadataGlobalsToJSON(
  updateAssetsMetadataGlobals: UpdateAssetsMetadataGlobals,
): string {
  return JSON.stringify(
    UpdateAssetsMetadataGlobals$outboundSchema.parse(
      updateAssetsMetadataGlobals,
    ),
  );
}
export function updateAssetsMetadataGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAssetsMetadataGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAssetsMetadataGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAssetsMetadataGlobals' from JSON`,
  );
}

/** @internal */
export const UpdateAssetsMetadataRequest$inboundSchema: z.ZodType<
  UpdateAssetsMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: components.ResourceType$inboundSchema,
  metadata_update_request: components.MetadataUpdateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "metadata_update_request": "metadataUpdateRequest",
  });
});
/** @internal */
export type UpdateAssetsMetadataRequest$Outbound = {
  resource_type: string;
  metadata_update_request: components.MetadataUpdateRequest$Outbound;
};

/** @internal */
export const UpdateAssetsMetadataRequest$outboundSchema: z.ZodType<
  UpdateAssetsMetadataRequest$Outbound,
  z.ZodTypeDef,
  UpdateAssetsMetadataRequest
> = z.object({
  resourceType: components.ResourceType$outboundSchema,
  metadataUpdateRequest: components.MetadataUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    metadataUpdateRequest: "metadata_update_request",
  });
});

export function updateAssetsMetadataRequestToJSON(
  updateAssetsMetadataRequest: UpdateAssetsMetadataRequest,
): string {
  return JSON.stringify(
    UpdateAssetsMetadataRequest$outboundSchema.parse(
      updateAssetsMetadataRequest,
    ),
  );
}
export function updateAssetsMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAssetsMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAssetsMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAssetsMetadataRequest' from JSON`,
  );
}
