/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type of access control to apply to the asset.
 */
export const AccessType = {
  Token: "token",
  Anonymous: "anonymous",
} as const;
/**
 * The type of access control to apply to the asset.
 */
export type AccessType = ClosedEnum<typeof AccessType>;

/**
 * The start date and time when anonymous access becomes available. Accepts ISO 8601 string or Unix timestamp.
 */
export type Start = string | number;

/**
 * The end date and time when anonymous access expires. Accepts ISO 8601 string or Unix timestamp.
 */
export type End = string | number;

/**
 * Access control rule that defines when and how the asset can be accessed.
 */
export type AccessControlItem = {
  /**
   * The type of access control to apply to the asset.
   */
  accessType: AccessType;
  /**
   * The authentication key identifier for token-based access. Default key is used if not specified or if set to 'default'.
   */
  key?: string | undefined;
  /**
   * The start date and time when anonymous access becomes available. Accepts ISO 8601 string or Unix timestamp.
   */
  start?: string | number | undefined;
  /**
   * The end date and time when anonymous access expires. Accepts ISO 8601 string or Unix timestamp.
   */
  end?: string | number | undefined;
};

/** @internal */
export const AccessType$inboundSchema: z.ZodNativeEnum<typeof AccessType> = z
  .nativeEnum(AccessType);
/** @internal */
export const AccessType$outboundSchema: z.ZodNativeEnum<typeof AccessType> =
  AccessType$inboundSchema;

/** @internal */
export const Start$inboundSchema: z.ZodType<Start, z.ZodTypeDef, unknown> = z
  .union([z.string(), z.number().int()]);
/** @internal */
export type Start$Outbound = string | number;

/** @internal */
export const Start$outboundSchema: z.ZodType<
  Start$Outbound,
  z.ZodTypeDef,
  Start
> = z.union([z.string(), z.number().int()]);

export function startToJSON(start: Start): string {
  return JSON.stringify(Start$outboundSchema.parse(start));
}
export function startFromJSON(
  jsonString: string,
): SafeParseResult<Start, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Start$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Start' from JSON`,
  );
}

/** @internal */
export const End$inboundSchema: z.ZodType<End, z.ZodTypeDef, unknown> = z.union(
  [z.string(), z.number().int()],
);
/** @internal */
export type End$Outbound = string | number;

/** @internal */
export const End$outboundSchema: z.ZodType<End$Outbound, z.ZodTypeDef, End> = z
  .union([z.string(), z.number().int()]);

export function endToJSON(end: End): string {
  return JSON.stringify(End$outboundSchema.parse(end));
}
export function endFromJSON(
  jsonString: string,
): SafeParseResult<End, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => End$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'End' from JSON`,
  );
}

/** @internal */
export const AccessControlItem$inboundSchema: z.ZodType<
  AccessControlItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_type: AccessType$inboundSchema,
  key: z.string().optional(),
  start: z.union([z.string(), z.number().int()]).optional(),
  end: z.union([z.string(), z.number().int()]).optional(),
}).transform((v) => {
  return remap$(v, {
    "access_type": "accessType",
  });
});
/** @internal */
export type AccessControlItem$Outbound = {
  access_type: string;
  key?: string | undefined;
  start?: string | number | undefined;
  end?: string | number | undefined;
};

/** @internal */
export const AccessControlItem$outboundSchema: z.ZodType<
  AccessControlItem$Outbound,
  z.ZodTypeDef,
  AccessControlItem
> = z.object({
  accessType: AccessType$outboundSchema,
  key: z.string().optional(),
  start: z.union([z.string(), z.number().int()]).optional(),
  end: z.union([z.string(), z.number().int()]).optional(),
}).transform((v) => {
  return remap$(v, {
    accessType: "access_type",
  });
});

export function accessControlItemToJSON(
  accessControlItem: AccessControlItem,
): string {
  return JSON.stringify(
    AccessControlItem$outboundSchema.parse(accessControlItem),
  );
}
export function accessControlItemFromJSON(
  jsonString: string,
): SafeParseResult<AccessControlItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessControlItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessControlItem' from JSON`,
  );
}
