/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApiErrorError = {
  message: string;
};

/** @internal */
export const ApiErrorError$inboundSchema: z.ZodType<
  ApiErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ApiErrorError$Outbound = {
  message: string;
};

/** @internal */
export const ApiErrorError$outboundSchema: z.ZodType<
  ApiErrorError$Outbound,
  z.ZodTypeDef,
  ApiErrorError
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiErrorError$ {
  /** @deprecated use `ApiErrorError$inboundSchema` instead. */
  export const inboundSchema = ApiErrorError$inboundSchema;
  /** @deprecated use `ApiErrorError$outboundSchema` instead. */
  export const outboundSchema = ApiErrorError$outboundSchema;
  /** @deprecated use `ApiErrorError$Outbound` instead. */
  export type Outbound = ApiErrorError$Outbound;
}

export function apiErrorErrorToJSON(apiErrorError: ApiErrorError): string {
  return JSON.stringify(ApiErrorError$outboundSchema.parse(apiErrorError));
}

export function apiErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ApiErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiErrorError' from JSON`,
  );
}
