/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Static asset delivery type.
 */
export const AssetDeliveryType = {
  Asset: "asset",
} as const;
/**
 * Static asset delivery type.
 */
export type AssetDeliveryType = ClosedEnum<typeof AssetDeliveryType>;

/** @internal */
export const AssetDeliveryType$inboundSchema: z.ZodNativeEnum<
  typeof AssetDeliveryType
> = z.nativeEnum(AssetDeliveryType);
/** @internal */
export const AssetDeliveryType$outboundSchema: z.ZodNativeEnum<
  typeof AssetDeliveryType
> = AssetDeliveryType$inboundSchema;
