/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PrincipalType,
  PrincipalType$inboundSchema,
  PrincipalType$outboundSchema,
} from "./principaltype.js";

/**
 * The user, group, or API key whose role assignments are being modified.
 */
export type Principal = {
  /**
   * The type of principal.
   */
  type: PrincipalType;
  /**
   * The unique identifier of the principal. For `apiKey`, provide the API key value.
   */
  id: string;
};

/**
 * The operation to perform on the principal’s role assignments. `add` grants the specified roles; `remove` revokes them.
 */
export const Operation = {
  Add: "add",
  Remove: "remove",
} as const;
/**
 * The operation to perform on the principal’s role assignments. `add` grants the specified roles; `remove` revokes them.
 */
export type Operation = ClosedEnum<typeof Operation>;

export type AssignFolderRolesRequest = {
  /**
   * The user, group, or API key whose role assignments are being modified.
   */
  principal: Principal;
  /**
   * The operation to perform on the principal’s role assignments. `add` grants the specified roles; `remove` revokes them.
   */
  operation: Operation;
  /**
   * The role IDs to add or remove.
   */
  roles: Array<string>;
};

/** @internal */
export const Principal$inboundSchema: z.ZodType<
  Principal,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PrincipalType$inboundSchema,
  id: z.string(),
});
/** @internal */
export type Principal$Outbound = {
  type: string;
  id: string;
};

/** @internal */
export const Principal$outboundSchema: z.ZodType<
  Principal$Outbound,
  z.ZodTypeDef,
  Principal
> = z.object({
  type: PrincipalType$outboundSchema,
  id: z.string(),
});

export function principalToJSON(principal: Principal): string {
  return JSON.stringify(Principal$outboundSchema.parse(principal));
}
export function principalFromJSON(
  jsonString: string,
): SafeParseResult<Principal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Principal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Principal' from JSON`,
  );
}

/** @internal */
export const Operation$inboundSchema: z.ZodNativeEnum<typeof Operation> = z
  .nativeEnum(Operation);
/** @internal */
export const Operation$outboundSchema: z.ZodNativeEnum<typeof Operation> =
  Operation$inboundSchema;

/** @internal */
export const AssignFolderRolesRequest$inboundSchema: z.ZodType<
  AssignFolderRolesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  principal: z.lazy(() => Principal$inboundSchema),
  operation: Operation$inboundSchema,
  roles: z.array(z.string()),
});
/** @internal */
export type AssignFolderRolesRequest$Outbound = {
  principal: Principal$Outbound;
  operation: string;
  roles: Array<string>;
};

/** @internal */
export const AssignFolderRolesRequest$outboundSchema: z.ZodType<
  AssignFolderRolesRequest$Outbound,
  z.ZodTypeDef,
  AssignFolderRolesRequest
> = z.object({
  principal: z.lazy(() => Principal$outboundSchema),
  operation: Operation$outboundSchema,
  roles: z.array(z.string()),
});

export function assignFolderRolesRequestToJSON(
  assignFolderRolesRequest: AssignFolderRolesRequest,
): string {
  return JSON.stringify(
    AssignFolderRolesRequest$outboundSchema.parse(assignFolderRolesRequest),
  );
}
export function assignFolderRolesRequestFromJSON(
  jsonString: string,
): SafeParseResult<AssignFolderRolesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssignFolderRolesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssignFolderRolesRequest' from JSON`,
  );
}
