/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Contextual metadata grouped by kind. Custom user context appears under the 'custom' key. Other context kinds may also appear as additional keys.
 */
export type ContextFullResponse = {
  /**
   * User-defined contextual metadata as key-value pairs.
   */
  custom?: { [k: string]: string } | undefined;
  additionalProperties?: { [k: string]: { [k: string]: string } } | undefined;
};

/** @internal */
export const ContextFullResponse$inboundSchema: z.ZodType<
  ContextFullResponse,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    custom: z.record(z.string()).optional(),
  }).catchall(z.record(z.string())),
  "additionalProperties",
  true,
);
/** @internal */
export type ContextFullResponse$Outbound = {
  custom?: { [k: string]: string } | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ContextFullResponse$outboundSchema: z.ZodType<
  ContextFullResponse$Outbound,
  z.ZodTypeDef,
  ContextFullResponse
> = z.object({
  custom: z.record(z.string()).optional(),
  additionalProperties: z.record(z.record(z.string())).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function contextFullResponseToJSON(
  contextFullResponse: ContextFullResponse,
): string {
  return JSON.stringify(
    ContextFullResponse$outboundSchema.parse(contextFullResponse),
  );
}
export function contextFullResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContextFullResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextFullResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextFullResponse' from JSON`,
  );
}
