/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Coordinate data for faces and custom regions.
 */
export type CoordinatesResponse = {
  /**
   * Detected face coordinate rectangles [x, y, width, height].
   */
  faces?: Array<Array<number>> | undefined;
  /**
   * Custom coordinate rectangles [x, y, width, height].
   */
  custom?: Array<Array<number>> | undefined;
};

/** @internal */
export const CoordinatesResponse$inboundSchema: z.ZodType<
  CoordinatesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  faces: z.array(z.array(z.number().int())).optional(),
  custom: z.array(z.array(z.number())).optional(),
});
/** @internal */
export type CoordinatesResponse$Outbound = {
  faces?: Array<Array<number>> | undefined;
  custom?: Array<Array<number>> | undefined;
};

/** @internal */
export const CoordinatesResponse$outboundSchema: z.ZodType<
  CoordinatesResponse$Outbound,
  z.ZodTypeDef,
  CoordinatesResponse
> = z.object({
  faces: z.array(z.array(z.number().int())).optional(),
  custom: z.array(z.array(z.number())).optional(),
});

export function coordinatesResponseToJSON(
  coordinatesResponse: CoordinatesResponse,
): string {
  return JSON.stringify(
    CoordinatesResponse$outboundSchema.parse(coordinatesResponse),
  );
}
export function coordinatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<CoordinatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CoordinatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CoordinatesResponse' from JSON`,
  );
}
