/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteFolderResponse = {
  /**
   * List of deleted folder paths.
   */
  deleted: Array<string>;
};

/** @internal */
export const DeleteFolderResponse$inboundSchema: z.ZodType<
  DeleteFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  deleted: z.array(z.string()),
});
/** @internal */
export type DeleteFolderResponse$Outbound = {
  deleted: Array<string>;
};

/** @internal */
export const DeleteFolderResponse$outboundSchema: z.ZodType<
  DeleteFolderResponse$Outbound,
  z.ZodTypeDef,
  DeleteFolderResponse
> = z.object({
  deleted: z.array(z.string()),
});

export function deleteFolderResponseToJSON(
  deleteFolderResponse: DeleteFolderResponse,
): string {
  return JSON.stringify(
    DeleteFolderResponse$outboundSchema.parse(deleteFolderResponse),
  );
}
export function deleteFolderResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteFolderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteFolderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteFolderResponse' from JSON`,
  );
}
