/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestroyByAssetIdRequest = {
  /**
   * A 32-character hexadecimal asset ID.
   */
  assetId: string;
  /**
   * Whether to invalidate CDN cache. Default is false.
   */
  invalidate?: boolean | undefined;
  /**
   * URL to receive completion notification.
   */
  notificationUrl?: string | undefined;
  /**
   * URL for redirect after operation completion.
   */
  callback?: string | undefined;
};

/** @internal */
export const DestroyByAssetIdRequest$inboundSchema: z.ZodType<
  DestroyByAssetIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_id: z.string(),
  invalidate: z.boolean().optional(),
  notification_url: z.string().optional(),
  callback: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "asset_id": "assetId",
    "notification_url": "notificationUrl",
  });
});
/** @internal */
export type DestroyByAssetIdRequest$Outbound = {
  asset_id: string;
  invalidate?: boolean | undefined;
  notification_url?: string | undefined;
  callback?: string | undefined;
};

/** @internal */
export const DestroyByAssetIdRequest$outboundSchema: z.ZodType<
  DestroyByAssetIdRequest$Outbound,
  z.ZodTypeDef,
  DestroyByAssetIdRequest
> = z.object({
  assetId: z.string(),
  invalidate: z.boolean().optional(),
  notificationUrl: z.string().optional(),
  callback: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    assetId: "asset_id",
    notificationUrl: "notification_url",
  });
});

export function destroyByAssetIdRequestToJSON(
  destroyByAssetIdRequest: DestroyByAssetIdRequest,
): string {
  return JSON.stringify(
    DestroyByAssetIdRequest$outboundSchema.parse(destroyByAssetIdRequest),
  );
}
export function destroyByAssetIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DestroyByAssetIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyByAssetIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyByAssetIdRequest' from JSON`,
  );
}
