/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The status of the explode operation.
 */
export const ExplodeResponseStatus = {
  Processing: "processing",
} as const;
/**
 * The status of the explode operation.
 */
export type ExplodeResponseStatus = ClosedEnum<typeof ExplodeResponseStatus>;

export type ExplodeResponse = {
  /**
   * The status of the explode operation.
   */
  status?: ExplodeResponseStatus | undefined;
  /**
   * The ID of the batch operation.
   */
  batchId?: string | undefined;
};

/** @internal */
export const ExplodeResponseStatus$inboundSchema: z.ZodNativeEnum<
  typeof ExplodeResponseStatus
> = z.nativeEnum(ExplodeResponseStatus);
/** @internal */
export const ExplodeResponseStatus$outboundSchema: z.ZodNativeEnum<
  typeof ExplodeResponseStatus
> = ExplodeResponseStatus$inboundSchema;

/** @internal */
export const ExplodeResponse$inboundSchema: z.ZodType<
  ExplodeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ExplodeResponseStatus$inboundSchema.optional(),
  batch_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "batch_id": "batchId",
  });
});
/** @internal */
export type ExplodeResponse$Outbound = {
  status?: string | undefined;
  batch_id?: string | undefined;
};

/** @internal */
export const ExplodeResponse$outboundSchema: z.ZodType<
  ExplodeResponse$Outbound,
  z.ZodTypeDef,
  ExplodeResponse
> = z.object({
  status: ExplodeResponseStatus$outboundSchema.optional(),
  batchId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    batchId: "batch_id",
  });
});

export function explodeResponseToJSON(
  explodeResponse: ExplodeResponse,
): string {
  return JSON.stringify(ExplodeResponse$outboundSchema.parse(explodeResponse));
}
export function explodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExplodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExplodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplodeResponse' from JSON`,
  );
}
