/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessControlItem,
  AccessControlItem$inboundSchema,
  AccessControlItem$Outbound,
  AccessControlItem$outboundSchema,
} from "./accesscontrolitem.js";
import {
  ExplicitDeliveryType,
  ExplicitDeliveryType$inboundSchema,
  ExplicitDeliveryType$Outbound,
  ExplicitDeliveryType$outboundSchema,
} from "./explicitdeliverytype.js";
import {
  ResponsiveBreakpoint,
  ResponsiveBreakpoint$inboundSchema,
  ResponsiveBreakpoint$Outbound,
  ResponsiveBreakpoint$outboundSchema,
} from "./responsivebreakpoint.js";
import {
  StructuredMetadataParam,
  StructuredMetadataParam$inboundSchema,
  StructuredMetadataParam$Outbound,
  StructuredMetadataParam$outboundSchema,
} from "./structuredmetadataparam.js";
import {
  TagsParam,
  TagsParam$inboundSchema,
  TagsParam$Outbound,
  TagsParam$outboundSchema,
} from "./tagsparam.js";

/**
 * Configuration object for automatic video transcription with translation options.
 */
export type ExplicitRequestAutoTranscription = {
  /**
   * Array of target language codes for transcription translation.
   */
  translate?: Array<string> | undefined;
};

export type ExplicitRequestAutoTranscriptionUnion =
  | boolean
  | ExplicitRequestAutoTranscription;

/**
 * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use accessControl instead.
 */
export const ExplicitRequestAccessMode = {
  Public: "public",
  Authenticated: "authenticated",
} as const;
/**
 * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use accessControl instead.
 */
export type ExplicitRequestAccessMode = ClosedEnum<
  typeof ExplicitRequestAccessMode
>;

/**
 * Named region coordinate groups for cropping with region gravity.
 *
 * @remarks
 * Can be a JSON-encoded string or an object. Each region name may contain
 * only letters, numbers, or hyphens, and must have at least two coordinate pairs.
 */
export type ExplicitRequestRegions = string | {
  [k: string]: Array<Array<number>>;
};

/**
 * Settings to automatically generate breakpoints for responsive images.
 */
export type ExplicitRequestResponsiveBreakpoints =
  | Array<ResponsiveBreakpoint>
  | ResponsiveBreakpoint;

/**
 * Override the quality setting for this asset.
 */
export type QualityOverride = string | number;

/**
 * Common parameters for configuring an asset, including transformation, tagging, metadata, and moderation options.
 */
export type ExplicitRequest = {
  /**
   * Whether to return accessibility analysis values for the image.
   */
  accessibilityAnalysis?: boolean | undefined;
  /**
   * The asset folder to assign to the asset.
   */
  assetFolder?: string | undefined;
  /**
   * When set to true, returns the uploaded asset's public_id immediately in the response, before the upload is completed (asynchronously). Default: false.
   *
   * @remarks
   */
  async?: boolean | undefined;
  /**
   * Whether to trigger automatic generation of video chapters. Chapters will be generated and saved as a .vtt file with -chapters appended to the public ID of the video. You can enable chapters as part of the Cloudinary Video Player. Relevant for videos only.
   */
  autoChaptering?: boolean | undefined;
  /**
   * Automatically assigns tags to an asset according to detected objects or categories with a confidence score higher than the specified value.
   *
   * @remarks
   * Use together with the detection parameter for:
   * - Cloudinary AI Content Analysis
   * - Amazon Rekognition Celebrity Detection
   * Use together with the categorization parameter for:
   * - Google Automatic Video Tagging
   * - Google Auto Tagging
   * - Imagga Auto Tagging
   * - Amazon Rekognition Auto Tagging
   */
  autoTagging?: number | undefined;
  autoTranscription?: boolean | ExplicitRequestAutoTranscription | undefined;
  /**
   * Restricts access to the asset by specifying one or more access types.
   *
   * @remarks
   * The asset is restricted unless at least one listed access type is valid.
   */
  accessControl?: Array<AccessControlItem> | undefined;
  /**
   * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
   *
   * @remarks
   *
   * @deprecated field: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use accessControl instead.
   */
  accessMode?: ExplicitRequestAccessMode | undefined;
  /**
   * Whether to backup the uploaded asset. When set to true, backs up uploaded assets to a secondary storage bucket.
   */
  backup?: boolean | undefined;
  /**
   * Automatically remove the background of an image using an add-on.
   *
   * @remarks
   * - Set to cloudinary_ai to use the deep-learning based Cloudinary AI Background Removal add-on.
   *   Optionally append a template suffix (e.g., cloudinary_ai:fine_edges).
   * - Note: this feature has been superseded by background removal on the fly.
   * - Set to pixelz to use the human-powered Pixelz Remove-The-Background Editing add-on service.
   * Relevant for images only.
   */
  backgroundRemoval?: string | undefined;
  /**
   * A URL to redirect to after the upload/explicit is completed instead of returning the upload response.
   *
   * @remarks
   * Signed upload result parameters are added to the callback URL. This parameter is ignored for XHR (Ajax XMLHttpRequest) or JavaScript Fetch API upload requests.
   * Note: This parameter is relevant for direct uploads from a form in the browser. It is automatically set if you perform direct upload from the browser using Cloudinary's SDKs and the jQuery plugin.
   *
   * @deprecated field: The callback parameter is deprecated. Not relevant for modern browsers. Starting July 2025 new customers will not be able to use this parameter..
   */
  callback?: string | undefined;
  /**
   * A comma-separated list of the categorization add-ons to run on the asset.
   *
   * @remarks
   * Set to google_tagging, google_video_tagging, imagga_tagging and/or aws_rek_tagging
   * to automatically classify the scenes of the uploaded asset.
   * Optionally append a language code suffix (e.g., google_tagging:fr).
   */
  categorization?: string | undefined;
  /**
   * Whether to return a cinemagraph analysis value for the media asset between 0 and 1, where 0 means the asset is not a cinemagraph and 1 means the asset is a cinemagraph. Relevant for animated images and video only. A static image will return 0.
   */
  cinemagraphAnalysis?: boolean | undefined;
  /**
   * Whether to retrieve predominant colors & color histogram of the uploaded image. Note: If all returned colors are opaque, then 6-digit RGB hex values are returned. If one or more colors contain an alpha channel, then 8-digit RGBA hex quadruplet values are returned.
   */
  colors?: boolean | undefined;
  /**
   * Invokes the relevant add-on to return a list of detected content.
   *
   * @remarks
   * Set to:
   * - <content-aware model>_[<version>] (e.g. coco_v2) to return a list of detected content using the Cloudinary AI Content Analysis add-on. Can be used together with the auto_tagging parameter to apply tags automatically.
   * - captioning to analyze an image and suggest a caption based on the image's contents.
   * - iqa to analyze the quality of an image.
   * - watermark-detection to detect watermarks in an image.
   * - adv_face to return a list of facial attributes using the Advanced Facial Attribute Detection add-on.
   * - aws_rek_face to return a list of detected celebrities and facial attributes using the Amazon Rekognition Celebrity Detection add-on. Can be used together with the auto_tagging parameter to apply tags automatically.
   */
  detection?: string | undefined;
  /**
   * Whether to discard the name of the original uploaded file. Relevant when delivering assets as attachments (setting the flag disposition:attachment in delivery URLs).
   */
  discardOriginalFilename?: boolean | undefined;
  /**
   * A display name for the asset.
   */
  displayName?: string | undefined;
  /**
   * Whether to generate the eager transformations asynchronously in the background after the upload request is completed rather than before the upload is completed.
   */
  eagerAsync?: boolean | undefined;
  /**
   * A URL to notify when eager transformations are completed.
   */
  eagerNotificationUrl?: string | undefined;
  /**
   * Allows you to modify upload parameters by specifying custom logic with JavaScript. This can be useful for conditionally adding tags, contextual metadata, structured metadata or eager transformations depending on specific criteria of the uploaded file.
   */
  eval?: string | undefined;
  /**
   * Whether to detect faces in the asset.
   */
  faces?: boolean | undefined;
  /**
   * Overrides the originally uploaded asset's file name in downloads that use flags like fl_attachment or fl_force_original.
   */
  filenameOverride?: string | undefined;
  /**
   * Folder name where the uploaded asset will be stored. This parameter applies when using the Admin API, or when specifying the upload preset for unsigned uploading with the Upload API.
   *
   * @deprecated field: If Dynamic folders mode is enabled on your product environment, this parameter is deprecated, and it's recommended to use the asset_folder parameter to control where the asset will be placed. If you also want your public_id to match the initial asset folder path, include the use_asset_folder_as_public_id_prefixparameter.
  .
   */
  folder?: string | undefined;
  /**
   * An optional format to convert the uploaded asset to before saving in the cloud.
   */
  format?: string | undefined;
  /**
   * Whether to invalidate CDN cache copies of a previously uploaded asset that shares the same public ID. Default: false.
   *
   * @remarks
   */
  invalidate?: boolean | undefined;
  /**
   * Whether to return IPTC, XMP, and detailed Exif metadata of the uploaded asset in the response.
   *
   * @remarks
   * Supported for images, video, and audio.
   * - Returned metadata for images includes: PixelsPerUnitX, PixelsPerUnitY, PixelUnits, Colorspace, and DPI.
   * - Returned metadata for audio and video includes: audio_codec, audio_bit_rate, audio_frequency, channels, channel_layout.
   * - Additional metadata for video includes: pix_format, codec, level, profile, video_bit_rate, dar.
   */
  mediaMetadata?: boolean | undefined;
  /**
   * A pipe-separated list or a map of custom metadata fields (by external_id) and the values to assign to each of them. The = " and | characters can be supported as values when escaped with a prepended backslash (\). For a multi-select field, you can set a maximum of 3000 different metadata values on an asset.
   *
   * @remarks
   */
  metadata?: StructuredMetadataParam | undefined;
  /**
   * Whether to clear metadata field values that have become invalid due to a change in metadata rules. If false, the API returns an error if any existing metadata value is no longer valid. Default: false.
   */
  clearInvalid?: boolean | undefined;
  /**
   * For all asset types, set to:
   *
   * @remarks
   * - manual to add the uploaded asset to a list of pending assets that can be moderated using the Admin API or the Cloudinary Console.
   * - perception_point to automatically moderate the uploaded asset using the Perception Point Malware Detection add-on.
   *
   * For images only, set to:
   * - webpurify to automatically moderate the uploaded image using the WebPurify Image Moderation add-on.
   * - aws_rek to automatically moderate the uploaded image using the Amazon Rekognition AI Moderation add-on.
   * - duplicate:<threshold> to detect if the same or a similar image already exists using the Cloudinary Duplicate Image Detection add-on. Set threshold to a float greater than 0 and less than or equal to 1.0 to specify how similar an image needs to be in order to be considered a duplicate. Set threshold to 0 to add an image to the index of images that are searched when duplicate detection is invoked for another image.
   *
   * For videos only, set to:
   * - aws_rek_video to automatically moderate the uploaded video using the Amazon Rekognition Video Moderation add-on.
   * - google_video_moderation automatically moderate the uploaded video using the Google AI Video Moderation add-on.
   *
   * To request multiple moderations in a single API call:
   * - Send the desired list of moderations as a pipe-separated string with manual moderation, if relevant, being last.
   *
   * Note: Rejected assets are automatically invalidated on the CDN within approximately ten minutes.
   */
  moderation?: string | undefined;
  /**
   * A URL to notify when the asset is ready.
   */
  notificationUrl?: string | undefined;
  /**
   * Set to adv_ocr to extract all text elements in an image as well as the bounding box
   *
   * @remarks
   * coordinates of each detected element using the OCR text detection and extraction add-on.
   * Optionally append options (e.g., adv_ocr:document).
   */
  ocr?: string | undefined;
  /**
   * Allows you to update an asset by specifying custom logic with JavaScript that is executed after the upload to Cloudinary is completed successfully. This can be useful for conditionally adding tags, contextual metadata, and structured metadata, depending on the results of using the detection parameter on upload.
   */
  onSuccess?: string | undefined;
  /**
   * When applying eager for already existing video transformations, this setting indicates whether to force the existing derived video resources to be regenerated. Default for videos: false.
   *
   * @remarks
   * Note: When specifying existing eager transformations for images, corresponding derived images are always regenerated.
   */
  overwrite?: boolean | undefined;
  /**
   * Whether to return the perceptual hash (pHash) on the uploaded image for image similarity detection.
   *
   * @remarks
   */
  phash?: boolean | undefined;
  /**
   * A proxy to use for fetching remote URLs. The format should be http://hostname:port.
   */
  proxy?: string | undefined;
  /**
   * The public ID of the existing asset to apply operations on.
   */
  publicId: string;
  /**
   * A string or path that's automatically prepended to the public_id with a forward slash. The value can contain the same characters as the public_id including additional forward slashes. This prefix can be useful to provide context and improve the SEO of an asset's filename in the delivery URL, but the value does not impact the location where the asset is stored.
   */
  publicIdPrefix?: string | undefined;
  /**
   * Whether to return a quality analysis value for the image between 0 and 1, where 0 means the image is blurry and out of focus and 1 means the image is sharp and in focus. Relevant for images only.
   */
  qualityAnalysis?: boolean | undefined;
  /**
   * Generates a related file based on the uploaded file.
   *
   * @remarks
   * - Set to aspose to automatically create a PDF or other image format from a raw Office document using the Aspose Document Conversion add-on. (Asynchronous)
   * - Set to google_speech to instruct the Google AI Video Transcription add-on to generate an automatic transcript raw file from an uploaded video. (Asynchronous)
   * - Set to extract_text to extract all the text from a PDF file and store it in a raw JSON file with a public ID in the format: [pdf_public_id].extract_text.json. The full URL of the generated JSON file is included in the API response. Unlike the above raw_convert options, this option doesn't require registering for an add-on.(Synchronous)
   * - Set to azure_video_indexer to generate AI-powered video insights from Microsoft Azure. (Asynchronous)
   */
  rawConvert?: string | undefined;
  /**
   * Named region coordinate groups for cropping with region gravity.
   *
   * @remarks
   * Can be a JSON-encoded string or an object. Each region name may contain
   * only letters, numbers, or hyphens, and must have at least two coordinate pairs.
   */
  regions?: string | { [k: string]: Array<Array<number>> } | undefined;
  /**
   * Settings to automatically generate breakpoints for responsive images.
   */
  responsiveBreakpoints?:
    | Array<ResponsiveBreakpoint>
    | ResponsiveBreakpoint
    | undefined;
  /**
   * Whether to return a deletion token in the upload response. The token can be used to delete the uploaded asset within approximately 10 minutes using an unauthenticated API call.
   */
  returnDeleteToken?: boolean | undefined;
  /**
   * Name of an upload preset that you defined for your Cloudinary product environment. An upload preset consists of upload parameters centrally managed using the Admin API or from the Upload Presets page of the Console Settings.
   */
  uploadPreset?: string | undefined;
  /**
   * Whether to add the asset_folder value as a prefix to the public_id value (prepended with a forward slash). This ensures that the public ID path will always match the initial asset folder, and can help to retain the behavior that previously existed in fixed folder mode. However, keep in mind that even when this option is used during upload, an asset with a certain public ID path can later be moved to a completely different asset folder hierarchy without impacting the public ID. This option only ensures path matching for the initial upload. Relevant only when public_id_prefix (or folder) has not been separately specified.
   */
  useAssetFolderAsPublicIdPrefix?: boolean | undefined;
  /**
   * Whether to use the original file name of the uploaded asset if available for the public ID. The file name is normalized and random characters are appended to ensure uniqueness if the file name already exists. Default: false.
   *
   * @remarks
   */
  useFilename?: boolean | undefined;
  /**
   * Whether to automatically assign the original filename of the uploaded asset as the asset's display name. Relevant only if the display_name parameter isn't set.
   */
  useFilenameAsDisplayName?: boolean | undefined;
  /**
   * Whether the display name should be unique.
   */
  uniqueDisplayName?: boolean | undefined;
  /**
   * When set to false and used together with use_filename, if an asset with the same file name already exists, no random characters are appended to the file name. Instead, the asset is overwritten. Default: true (random characters are added to the file name if needed).
   *
   * @remarks
   */
  uniqueFilename?: boolean | undefined;
  /**
   * Whether to index the image for use with visual searches. Relevant for images only.
   */
  visualSearch?: boolean | undefined;
  /**
   * A comma-separated list of tag names, or an array of tag names.
   */
  tags?: TagsParam | undefined;
  /**
   * A pipe-separated list of key-value pairs of general textual context metadata to attach to the asset (e.g., "alt=My image|caption=Nice photo"). A literal = or | inside a value must be escaped with a prepending backslash, and a literal backslash must be doubled. A double quote must not be escaped.
   */
  context?: string | undefined;
  /**
   * A list of transformations to eagerly generate for the asset. Accepts either a single transformation or a pipe-separated list of transformations.
   */
  eager?: string | undefined;
  /**
   * An incoming transformation to run on the uploaded asset before its storage. In contrast to eager, this parameter is applied before the file is stored.
   */
  transformation?: string | undefined;
  /**
   * A comma-separated list of file formats that are allowed for uploading. Files of other types will be rejected. The formats can be any combination of image types, video formats or raw file extensions.
   *
   * @remarks
   * Note: You can also add the `format` parameter to convert other file types instead of rejecting them. In this case, only files that would normally be rejected are converted, any file format allowed for upload won't be converted.
   */
  allowedFormats?: string | undefined;
  /**
   * An HTTP header or a list of headers lines for adding as response HTTP headers when delivering the asset to your users. Supported headers: Link, Authorization, X-Robots-Tag.
   *
   * @remarks
   */
  headers?: string | undefined;
  /**
   * Face coordinates as comma-separated values, with multiple faces separated by pipes.
   */
  faceCoordinates?: string | undefined;
  /**
   * Custom coordinates as comma-separated values, with multiple coordinates separated by pipes.
   */
  customCoordinates?: string | undefined;
  /**
   * Delivery types accepted by the explicit operation.
   */
  type?: ExplicitDeliveryType | undefined;
  /**
   * Override the quality setting for this asset.
   */
  qualityOverride?: string | number | undefined;
};

/** @internal */
export const ExplicitRequestAutoTranscription$inboundSchema: z.ZodType<
  ExplicitRequestAutoTranscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  translate: z.array(z.string()).optional(),
});
/** @internal */
export type ExplicitRequestAutoTranscription$Outbound = {
  translate?: Array<string> | undefined;
};

/** @internal */
export const ExplicitRequestAutoTranscription$outboundSchema: z.ZodType<
  ExplicitRequestAutoTranscription$Outbound,
  z.ZodTypeDef,
  ExplicitRequestAutoTranscription
> = z.object({
  translate: z.array(z.string()).optional(),
});

export function explicitRequestAutoTranscriptionToJSON(
  explicitRequestAutoTranscription: ExplicitRequestAutoTranscription,
): string {
  return JSON.stringify(
    ExplicitRequestAutoTranscription$outboundSchema.parse(
      explicitRequestAutoTranscription,
    ),
  );
}
export function explicitRequestAutoTranscriptionFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitRequestAutoTranscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExplicitRequestAutoTranscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitRequestAutoTranscription' from JSON`,
  );
}

/** @internal */
export const ExplicitRequestAutoTranscriptionUnion$inboundSchema: z.ZodType<
  ExplicitRequestAutoTranscriptionUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.boolean(),
  z.lazy(() => ExplicitRequestAutoTranscription$inboundSchema),
]);
/** @internal */
export type ExplicitRequestAutoTranscriptionUnion$Outbound =
  | boolean
  | ExplicitRequestAutoTranscription$Outbound;

/** @internal */
export const ExplicitRequestAutoTranscriptionUnion$outboundSchema: z.ZodType<
  ExplicitRequestAutoTranscriptionUnion$Outbound,
  z.ZodTypeDef,
  ExplicitRequestAutoTranscriptionUnion
> = z.union([
  z.boolean(),
  z.lazy(() => ExplicitRequestAutoTranscription$outboundSchema),
]);

export function explicitRequestAutoTranscriptionUnionToJSON(
  explicitRequestAutoTranscriptionUnion: ExplicitRequestAutoTranscriptionUnion,
): string {
  return JSON.stringify(
    ExplicitRequestAutoTranscriptionUnion$outboundSchema.parse(
      explicitRequestAutoTranscriptionUnion,
    ),
  );
}
export function explicitRequestAutoTranscriptionUnionFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitRequestAutoTranscriptionUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExplicitRequestAutoTranscriptionUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitRequestAutoTranscriptionUnion' from JSON`,
  );
}

/** @internal */
export const ExplicitRequestAccessMode$inboundSchema: z.ZodNativeEnum<
  typeof ExplicitRequestAccessMode
> = z.nativeEnum(ExplicitRequestAccessMode);
/** @internal */
export const ExplicitRequestAccessMode$outboundSchema: z.ZodNativeEnum<
  typeof ExplicitRequestAccessMode
> = ExplicitRequestAccessMode$inboundSchema;

/** @internal */
export const ExplicitRequestRegions$inboundSchema: z.ZodType<
  ExplicitRequestRegions,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.record(z.array(z.array(z.number().int())))]);
/** @internal */
export type ExplicitRequestRegions$Outbound = string | {
  [k: string]: Array<Array<number>>;
};

/** @internal */
export const ExplicitRequestRegions$outboundSchema: z.ZodType<
  ExplicitRequestRegions$Outbound,
  z.ZodTypeDef,
  ExplicitRequestRegions
> = z.union([z.string(), z.record(z.array(z.array(z.number().int())))]);

export function explicitRequestRegionsToJSON(
  explicitRequestRegions: ExplicitRequestRegions,
): string {
  return JSON.stringify(
    ExplicitRequestRegions$outboundSchema.parse(explicitRequestRegions),
  );
}
export function explicitRequestRegionsFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitRequestRegions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExplicitRequestRegions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitRequestRegions' from JSON`,
  );
}

/** @internal */
export const ExplicitRequestResponsiveBreakpoints$inboundSchema: z.ZodType<
  ExplicitRequestResponsiveBreakpoints,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(ResponsiveBreakpoint$inboundSchema),
  ResponsiveBreakpoint$inboundSchema,
]);
/** @internal */
export type ExplicitRequestResponsiveBreakpoints$Outbound =
  | Array<ResponsiveBreakpoint$Outbound>
  | ResponsiveBreakpoint$Outbound;

/** @internal */
export const ExplicitRequestResponsiveBreakpoints$outboundSchema: z.ZodType<
  ExplicitRequestResponsiveBreakpoints$Outbound,
  z.ZodTypeDef,
  ExplicitRequestResponsiveBreakpoints
> = z.union([
  z.array(ResponsiveBreakpoint$outboundSchema),
  ResponsiveBreakpoint$outboundSchema,
]);

export function explicitRequestResponsiveBreakpointsToJSON(
  explicitRequestResponsiveBreakpoints: ExplicitRequestResponsiveBreakpoints,
): string {
  return JSON.stringify(
    ExplicitRequestResponsiveBreakpoints$outboundSchema.parse(
      explicitRequestResponsiveBreakpoints,
    ),
  );
}
export function explicitRequestResponsiveBreakpointsFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitRequestResponsiveBreakpoints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExplicitRequestResponsiveBreakpoints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitRequestResponsiveBreakpoints' from JSON`,
  );
}

/** @internal */
export const QualityOverride$inboundSchema: z.ZodType<
  QualityOverride,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number().int()]);
/** @internal */
export type QualityOverride$Outbound = string | number;

/** @internal */
export const QualityOverride$outboundSchema: z.ZodType<
  QualityOverride$Outbound,
  z.ZodTypeDef,
  QualityOverride
> = z.union([z.string(), z.number().int()]);

export function qualityOverrideToJSON(
  qualityOverride: QualityOverride,
): string {
  return JSON.stringify(QualityOverride$outboundSchema.parse(qualityOverride));
}
export function qualityOverrideFromJSON(
  jsonString: string,
): SafeParseResult<QualityOverride, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QualityOverride$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QualityOverride' from JSON`,
  );
}

/** @internal */
export const ExplicitRequest$inboundSchema: z.ZodType<
  ExplicitRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessibility_analysis: z.boolean().optional(),
  asset_folder: z.string().optional(),
  async: z.boolean().optional(),
  auto_chaptering: z.boolean().optional(),
  auto_tagging: z.number().optional(),
  auto_transcription: z.union([
    z.boolean(),
    z.lazy(() => ExplicitRequestAutoTranscription$inboundSchema),
  ]).optional(),
  access_control: z.array(AccessControlItem$inboundSchema).optional(),
  access_mode: ExplicitRequestAccessMode$inboundSchema.optional(),
  backup: z.boolean().optional(),
  background_removal: z.string().optional(),
  callback: z.string().optional(),
  categorization: z.string().optional(),
  cinemagraph_analysis: z.boolean().optional(),
  colors: z.boolean().default(false),
  detection: z.string().optional(),
  discard_original_filename: z.boolean().optional(),
  display_name: z.string().optional(),
  eager_async: z.boolean().optional(),
  eager_notification_url: z.string().optional(),
  eval: z.string().optional(),
  faces: z.boolean().optional(),
  filename_override: z.string().optional(),
  folder: z.string().optional(),
  format: z.string().optional(),
  invalidate: z.boolean().optional(),
  media_metadata: z.boolean().optional(),
  metadata: StructuredMetadataParam$inboundSchema.optional(),
  clear_invalid: z.boolean().default(false),
  moderation: z.string().optional(),
  notification_url: z.string().optional(),
  ocr: z.string().optional(),
  on_success: z.string().optional(),
  overwrite: z.boolean().optional(),
  phash: z.boolean().optional(),
  proxy: z.string().optional(),
  public_id: z.string(),
  public_id_prefix: z.string().optional(),
  quality_analysis: z.boolean().optional(),
  raw_convert: z.string().optional(),
  regions: z.union([z.string(), z.record(z.array(z.array(z.number().int())))])
    .optional(),
  responsive_breakpoints: z.union([
    z.array(ResponsiveBreakpoint$inboundSchema),
    ResponsiveBreakpoint$inboundSchema,
  ]).optional(),
  return_delete_token: z.boolean().optional(),
  upload_preset: z.string().optional(),
  use_asset_folder_as_public_id_prefix: z.boolean().optional(),
  use_filename: z.boolean().optional(),
  use_filename_as_display_name: z.boolean().optional(),
  unique_display_name: z.boolean().optional(),
  unique_filename: z.boolean().optional(),
  visual_search: z.boolean().optional(),
  tags: TagsParam$inboundSchema.optional(),
  context: z.string().optional(),
  eager: z.string().optional(),
  transformation: z.string().optional(),
  allowed_formats: z.string().optional(),
  headers: z.string().optional(),
  face_coordinates: z.string().optional(),
  custom_coordinates: z.string().optional(),
  type: ExplicitDeliveryType$inboundSchema.optional(),
  quality_override: z.union([z.string(), z.number().int()]).optional(),
}).transform((v) => {
  return remap$(v, {
    "accessibility_analysis": "accessibilityAnalysis",
    "asset_folder": "assetFolder",
    "auto_chaptering": "autoChaptering",
    "auto_tagging": "autoTagging",
    "auto_transcription": "autoTranscription",
    "access_control": "accessControl",
    "access_mode": "accessMode",
    "background_removal": "backgroundRemoval",
    "cinemagraph_analysis": "cinemagraphAnalysis",
    "discard_original_filename": "discardOriginalFilename",
    "display_name": "displayName",
    "eager_async": "eagerAsync",
    "eager_notification_url": "eagerNotificationUrl",
    "filename_override": "filenameOverride",
    "media_metadata": "mediaMetadata",
    "clear_invalid": "clearInvalid",
    "notification_url": "notificationUrl",
    "on_success": "onSuccess",
    "public_id": "publicId",
    "public_id_prefix": "publicIdPrefix",
    "quality_analysis": "qualityAnalysis",
    "raw_convert": "rawConvert",
    "responsive_breakpoints": "responsiveBreakpoints",
    "return_delete_token": "returnDeleteToken",
    "upload_preset": "uploadPreset",
    "use_asset_folder_as_public_id_prefix": "useAssetFolderAsPublicIdPrefix",
    "use_filename": "useFilename",
    "use_filename_as_display_name": "useFilenameAsDisplayName",
    "unique_display_name": "uniqueDisplayName",
    "unique_filename": "uniqueFilename",
    "visual_search": "visualSearch",
    "allowed_formats": "allowedFormats",
    "face_coordinates": "faceCoordinates",
    "custom_coordinates": "customCoordinates",
    "quality_override": "qualityOverride",
  });
});
/** @internal */
export type ExplicitRequest$Outbound = {
  accessibility_analysis?: boolean | undefined;
  asset_folder?: string | undefined;
  async?: boolean | undefined;
  auto_chaptering?: boolean | undefined;
  auto_tagging?: number | undefined;
  auto_transcription?:
    | boolean
    | ExplicitRequestAutoTranscription$Outbound
    | undefined;
  access_control?: Array<AccessControlItem$Outbound> | undefined;
  access_mode?: string | undefined;
  backup?: boolean | undefined;
  background_removal?: string | undefined;
  callback?: string | undefined;
  categorization?: string | undefined;
  cinemagraph_analysis?: boolean | undefined;
  colors: boolean;
  detection?: string | undefined;
  discard_original_filename?: boolean | undefined;
  display_name?: string | undefined;
  eager_async?: boolean | undefined;
  eager_notification_url?: string | undefined;
  eval?: string | undefined;
  faces?: boolean | undefined;
  filename_override?: string | undefined;
  folder?: string | undefined;
  format?: string | undefined;
  invalidate?: boolean | undefined;
  media_metadata?: boolean | undefined;
  metadata?: StructuredMetadataParam$Outbound | undefined;
  clear_invalid: boolean;
  moderation?: string | undefined;
  notification_url?: string | undefined;
  ocr?: string | undefined;
  on_success?: string | undefined;
  overwrite?: boolean | undefined;
  phash?: boolean | undefined;
  proxy?: string | undefined;
  public_id: string;
  public_id_prefix?: string | undefined;
  quality_analysis?: boolean | undefined;
  raw_convert?: string | undefined;
  regions?: string | { [k: string]: Array<Array<number>> } | undefined;
  responsive_breakpoints?:
    | Array<ResponsiveBreakpoint$Outbound>
    | ResponsiveBreakpoint$Outbound
    | undefined;
  return_delete_token?: boolean | undefined;
  upload_preset?: string | undefined;
  use_asset_folder_as_public_id_prefix?: boolean | undefined;
  use_filename?: boolean | undefined;
  use_filename_as_display_name?: boolean | undefined;
  unique_display_name?: boolean | undefined;
  unique_filename?: boolean | undefined;
  visual_search?: boolean | undefined;
  tags?: TagsParam$Outbound | undefined;
  context?: string | undefined;
  eager?: string | undefined;
  transformation?: string | undefined;
  allowed_formats?: string | undefined;
  headers?: string | undefined;
  face_coordinates?: string | undefined;
  custom_coordinates?: string | undefined;
  type?: ExplicitDeliveryType$Outbound | undefined;
  quality_override?: string | number | undefined;
};

/** @internal */
export const ExplicitRequest$outboundSchema: z.ZodType<
  ExplicitRequest$Outbound,
  z.ZodTypeDef,
  ExplicitRequest
> = z.object({
  accessibilityAnalysis: z.boolean().optional(),
  assetFolder: z.string().optional(),
  async: z.boolean().optional(),
  autoChaptering: z.boolean().optional(),
  autoTagging: z.number().optional(),
  autoTranscription: z.union([
    z.boolean(),
    z.lazy(() => ExplicitRequestAutoTranscription$outboundSchema),
  ]).optional(),
  accessControl: z.array(AccessControlItem$outboundSchema).optional(),
  accessMode: ExplicitRequestAccessMode$outboundSchema.optional(),
  backup: z.boolean().optional(),
  backgroundRemoval: z.string().optional(),
  callback: z.string().optional(),
  categorization: z.string().optional(),
  cinemagraphAnalysis: z.boolean().optional(),
  colors: z.boolean().default(false),
  detection: z.string().optional(),
  discardOriginalFilename: z.boolean().optional(),
  displayName: z.string().optional(),
  eagerAsync: z.boolean().optional(),
  eagerNotificationUrl: z.string().optional(),
  eval: z.string().optional(),
  faces: z.boolean().optional(),
  filenameOverride: z.string().optional(),
  folder: z.string().optional(),
  format: z.string().optional(),
  invalidate: z.boolean().optional(),
  mediaMetadata: z.boolean().optional(),
  metadata: StructuredMetadataParam$outboundSchema.optional(),
  clearInvalid: z.boolean().default(false),
  moderation: z.string().optional(),
  notificationUrl: z.string().optional(),
  ocr: z.string().optional(),
  onSuccess: z.string().optional(),
  overwrite: z.boolean().optional(),
  phash: z.boolean().optional(),
  proxy: z.string().optional(),
  publicId: z.string(),
  publicIdPrefix: z.string().optional(),
  qualityAnalysis: z.boolean().optional(),
  rawConvert: z.string().optional(),
  regions: z.union([z.string(), z.record(z.array(z.array(z.number().int())))])
    .optional(),
  responsiveBreakpoints: z.union([
    z.array(ResponsiveBreakpoint$outboundSchema),
    ResponsiveBreakpoint$outboundSchema,
  ]).optional(),
  returnDeleteToken: z.boolean().optional(),
  uploadPreset: z.string().optional(),
  useAssetFolderAsPublicIdPrefix: z.boolean().optional(),
  useFilename: z.boolean().optional(),
  useFilenameAsDisplayName: z.boolean().optional(),
  uniqueDisplayName: z.boolean().optional(),
  uniqueFilename: z.boolean().optional(),
  visualSearch: z.boolean().optional(),
  tags: TagsParam$outboundSchema.optional(),
  context: z.string().optional(),
  eager: z.string().optional(),
  transformation: z.string().optional(),
  allowedFormats: z.string().optional(),
  headers: z.string().optional(),
  faceCoordinates: z.string().optional(),
  customCoordinates: z.string().optional(),
  type: ExplicitDeliveryType$outboundSchema.optional(),
  qualityOverride: z.union([z.string(), z.number().int()]).optional(),
}).transform((v) => {
  return remap$(v, {
    accessibilityAnalysis: "accessibility_analysis",
    assetFolder: "asset_folder",
    autoChaptering: "auto_chaptering",
    autoTagging: "auto_tagging",
    autoTranscription: "auto_transcription",
    accessControl: "access_control",
    accessMode: "access_mode",
    backgroundRemoval: "background_removal",
    cinemagraphAnalysis: "cinemagraph_analysis",
    discardOriginalFilename: "discard_original_filename",
    displayName: "display_name",
    eagerAsync: "eager_async",
    eagerNotificationUrl: "eager_notification_url",
    filenameOverride: "filename_override",
    mediaMetadata: "media_metadata",
    clearInvalid: "clear_invalid",
    notificationUrl: "notification_url",
    onSuccess: "on_success",
    publicId: "public_id",
    publicIdPrefix: "public_id_prefix",
    qualityAnalysis: "quality_analysis",
    rawConvert: "raw_convert",
    responsiveBreakpoints: "responsive_breakpoints",
    returnDeleteToken: "return_delete_token",
    uploadPreset: "upload_preset",
    useAssetFolderAsPublicIdPrefix: "use_asset_folder_as_public_id_prefix",
    useFilename: "use_filename",
    useFilenameAsDisplayName: "use_filename_as_display_name",
    uniqueDisplayName: "unique_display_name",
    uniqueFilename: "unique_filename",
    visualSearch: "visual_search",
    allowedFormats: "allowed_formats",
    faceCoordinates: "face_coordinates",
    customCoordinates: "custom_coordinates",
    qualityOverride: "quality_override",
  });
});

export function explicitRequestToJSON(
  explicitRequest: ExplicitRequest,
): string {
  return JSON.stringify(ExplicitRequest$outboundSchema.parse(explicitRequest));
}
export function explicitRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExplicitRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExplicitRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExplicitRequest' from JSON`,
  );
}
