/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The add-on a quota applies to.
 */
export const Feature = {
  ImageGeneration: "image_generation",
} as const;
/**
 * The add-on a quota applies to.
 */
export type Feature = ClosedEnum<typeof Feature>;

/** @internal */
export const Feature$inboundSchema: z.ZodNativeEnum<typeof Feature> = z
  .nativeEnum(Feature);
/** @internal */
export const Feature$outboundSchema: z.ZodNativeEnum<typeof Feature> =
  Feature$inboundSchema;
