/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ResourceFieldsEnum,
  ResourceFieldsEnum$inboundSchema,
  ResourceFieldsEnum$outboundSchema,
} from "./resourcefieldsenum.js";

export type Fields = string | Array<ResourceFieldsEnum>;

/** @internal */
export const Fields$inboundSchema: z.ZodType<Fields, z.ZodTypeDef, unknown> = z
  .union([z.string(), z.array(ResourceFieldsEnum$inboundSchema)]);
/** @internal */
export type Fields$Outbound = string | Array<string>;

/** @internal */
export const Fields$outboundSchema: z.ZodType<
  Fields$Outbound,
  z.ZodTypeDef,
  Fields
> = z.union([z.string(), z.array(ResourceFieldsEnum$outboundSchema)]);

export function fieldsToJSON(fields: Fields): string {
  return JSON.stringify(Fields$outboundSchema.parse(fields));
}
export function fieldsFromJSON(
  jsonString: string,
): SafeParseResult<Fields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields' from JSON`,
  );
}
