/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FolderRole = {
  /**
   * The unique identifier of the role.
   */
  id: string;
  /**
   * The human-readable name of the role.
   */
  name: string;
  /**
   * A summary of the permissions granted by this role.
   */
  description: string;
  /**
   * Indicates whether this role is inherited from an ancestor folder. If false, it's assigned directly to the requested folder.
   */
  inherited: boolean;
};

/** @internal */
export const FolderRole$inboundSchema: z.ZodType<
  FolderRole,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  inherited: z.boolean(),
});
/** @internal */
export type FolderRole$Outbound = {
  id: string;
  name: string;
  description: string;
  inherited: boolean;
};

/** @internal */
export const FolderRole$outboundSchema: z.ZodType<
  FolderRole$Outbound,
  z.ZodTypeDef,
  FolderRole
> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  inherited: z.boolean(),
});

export function folderRoleToJSON(folderRole: FolderRole): string {
  return JSON.stringify(FolderRole$outboundSchema.parse(folderRole));
}
export function folderRoleFromJSON(
  jsonString: string,
): SafeParseResult<FolderRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderRole' from JSON`,
  );
}
