/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The identifier of the folder to retrieve.
 */
export type FolderByIdRequest = {
  /**
   * The immutable identifier of the folder to retrieve.
   */
  id: string;
};

/** @internal */
export const FolderByIdRequest$inboundSchema: z.ZodType<
  FolderByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type FolderByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const FolderByIdRequest$outboundSchema: z.ZodType<
  FolderByIdRequest$Outbound,
  z.ZodTypeDef,
  FolderByIdRequest
> = z.object({
  id: z.string(),
});

export function folderByIdRequestToJSON(
  folderByIdRequest: FolderByIdRequest,
): string {
  return JSON.stringify(
    FolderByIdRequest$outboundSchema.parse(folderByIdRequest),
  );
}
export function folderByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<FolderByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderByIdRequest' from JSON`,
  );
}
