/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DirectionEnum,
  DirectionEnum$inboundSchema,
  DirectionEnum$outboundSchema,
} from "./directionenum.js";

export type FolderSearchRequest = {
  /**
   * The (Lucene-like) string expression specifying the search query.
   */
  expression?: string | undefined;
  /**
   * An array of single-key objects mapping a field to a sort direction. Each object must contain exactly one field name mapped to 'asc' or 'desc'.
   *
   * @remarks
   * Default: [{"created_at": "desc"}].
   */
  sortBy?: Array<{ [k: string]: DirectionEnum }> | undefined;
  /**
   * Maximum number of folders to return (max 500, default 50).
   */
  maxResults?: number | undefined;
  /**
   * When more results are available, use the next_cursor value from the previous response.
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const FolderSearchRequest$inboundSchema: z.ZodType<
  FolderSearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  expression: z.string().optional(),
  sort_by: z.array(z.record(DirectionEnum$inboundSchema)).optional(),
  max_results: z.number().int().default(50),
  next_cursor: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "sort_by": "sortBy",
    "max_results": "maxResults",
    "next_cursor": "nextCursor",
  });
});
/** @internal */
export type FolderSearchRequest$Outbound = {
  expression?: string | undefined;
  sort_by?: Array<{ [k: string]: string }> | undefined;
  max_results: number;
  next_cursor?: string | undefined;
};

/** @internal */
export const FolderSearchRequest$outboundSchema: z.ZodType<
  FolderSearchRequest$Outbound,
  z.ZodTypeDef,
  FolderSearchRequest
> = z.object({
  expression: z.string().optional(),
  sortBy: z.array(z.record(DirectionEnum$outboundSchema)).optional(),
  maxResults: z.number().int().default(50),
  nextCursor: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sortBy: "sort_by",
    maxResults: "max_results",
    nextCursor: "next_cursor",
  });
});

export function folderSearchRequestToJSON(
  folderSearchRequest: FolderSearchRequest,
): string {
  return JSON.stringify(
    FolderSearchRequest$outboundSchema.parse(folderSearchRequest),
  );
}
export function folderSearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<FolderSearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderSearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderSearchRequest' from JSON`,
  );
}
