/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The result of renaming or moving a folder.
 */
export type FolderRenameResponse = {
  /**
   * Whether the source folder was deleted after the move.
   */
  folderDeleted?: boolean | undefined;
  /**
   * The number of assets successfully moved.
   */
  moved?: number | undefined;
  /**
   * The number of assets rejected during the move.
   */
  rejected?: number | undefined;
  /**
   * The number of assets that failed to move.
   */
  failed?: number | undefined;
};

/** @internal */
export const FolderRenameResponse$inboundSchema: z.ZodType<
  FolderRenameResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder_deleted: z.boolean().optional(),
  moved: z.number().int().optional(),
  rejected: z.number().int().optional(),
  failed: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "folder_deleted": "folderDeleted",
  });
});
/** @internal */
export type FolderRenameResponse$Outbound = {
  folder_deleted?: boolean | undefined;
  moved?: number | undefined;
  rejected?: number | undefined;
  failed?: number | undefined;
};

/** @internal */
export const FolderRenameResponse$outboundSchema: z.ZodType<
  FolderRenameResponse$Outbound,
  z.ZodTypeDef,
  FolderRenameResponse
> = z.object({
  folderDeleted: z.boolean().optional(),
  moved: z.number().int().optional(),
  rejected: z.number().int().optional(),
  failed: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    folderDeleted: "folder_deleted",
  });
});

export function folderRenameResponseToJSON(
  folderRenameResponse: FolderRenameResponse,
): string {
  return JSON.stringify(
    FolderRenameResponse$outboundSchema.parse(folderRenameResponse),
  );
}
export function folderRenameResponseFromJSON(
  jsonString: string,
): SafeParseResult<FolderRenameResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderRenameResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderRenameResponse' from JSON`,
  );
}
