/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The source and destination folder paths.
 */
export type FolderRenameRequest = {
  /**
   * The full path of the folder to rename or move.
   */
  path: string;
  /**
   * The new full path for the folder.
   */
  toPath: string;
  /**
   * The maximum number of assets that may be moved by the rename. Assets beyond this limit cause the rename to be rejected.
   */
  resourcesLimit?: number | undefined;
  /**
   * The maximum total size, in bytes, of the assets that may be moved by the rename.
   */
  resourcesSizeLimit?: number | undefined;
  /**
   * The maximum number of derived assets that may be moved by the rename.
   */
  maxDerived?: number | undefined;
};

/** @internal */
export const FolderRenameRequest$inboundSchema: z.ZodType<
  FolderRenameRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string(),
  to_path: z.string(),
  resources_limit: z.number().int().optional(),
  resources_size_limit: z.number().int().optional(),
  max_derived: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "to_path": "toPath",
    "resources_limit": "resourcesLimit",
    "resources_size_limit": "resourcesSizeLimit",
    "max_derived": "maxDerived",
  });
});
/** @internal */
export type FolderRenameRequest$Outbound = {
  path: string;
  to_path: string;
  resources_limit?: number | undefined;
  resources_size_limit?: number | undefined;
  max_derived?: number | undefined;
};

/** @internal */
export const FolderRenameRequest$outboundSchema: z.ZodType<
  FolderRenameRequest$Outbound,
  z.ZodTypeDef,
  FolderRenameRequest
> = z.object({
  path: z.string(),
  toPath: z.string(),
  resourcesLimit: z.number().int().optional(),
  resourcesSizeLimit: z.number().int().optional(),
  maxDerived: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    toPath: "to_path",
    resourcesLimit: "resources_limit",
    resourcesSizeLimit: "resources_size_limit",
    maxDerived: "max_derived",
  });
});

export function folderRenameRequestToJSON(
  folderRenameRequest: FolderRenameRequest,
): string {
  return JSON.stringify(
    FolderRenameRequest$outboundSchema.parse(folderRenameRequest),
  );
}
export function folderRenameRequestFromJSON(
  jsonString: string,
): SafeParseResult<FolderRenameRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderRenameRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderRenameRequest' from JSON`,
  );
}
