/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessControlItem,
  AccessControlItem$inboundSchema,
  AccessControlItem$Outbound,
  AccessControlItem$outboundSchema,
} from "./accesscontrolitem.js";
import {
  ContextFullResponse,
  ContextFullResponse$inboundSchema,
  ContextFullResponse$Outbound,
  ContextFullResponse$outboundSchema,
} from "./contextfullresponse.js";
import {
  CoordinatesResponse,
  CoordinatesResponse$inboundSchema,
  CoordinatesResponse$Outbound,
  CoordinatesResponse$outboundSchema,
} from "./coordinatesresponse.js";
import {
  DeliveryTypeAll,
  DeliveryTypeAll$inboundSchema,
  DeliveryTypeAll$Outbound,
  DeliveryTypeAll$outboundSchema,
} from "./deliverytypeall.js";

export type InfoModeration = {
  kind?: string | undefined;
  status?: string | undefined;
  updatedAt?: Date | undefined;
};

export type InfoRelatedAsset = {};

export type InfoLastUpdated = {
  accessControlUpdatedAt?: Date | undefined;
  contextUpdatedAt?: Date | undefined;
  metadataUpdatedAt?: Date | undefined;
  publicIdUpdatedAt?: Date | undefined;
  tagsUpdatedAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

export type InfoDerived = {
  transformation?: string | undefined;
  format?: string | undefined;
  bytes?: number | undefined;
  id?: string | undefined;
  url?: string | undefined;
  secureUrl?: string | undefined;
};

export type InfoVersion = {
  /**
   * Hexadecimal version ID; length is a positive multiple of 32 (typically 32 or 64).
   */
  versionId?: string | undefined;
  version?: string | undefined;
  format?: string | null | undefined;
  size?: number | undefined;
  time?: Date | undefined;
  restorable?: boolean | undefined;
};

/**
 * Additional asset information (visual search, recognized people, etc.)
 */
export type InfoInfo = {};

export type InfoDerivative = {
  /**
   * The unique identifier of the derived resource.
   */
  id?: string | undefined;
  /**
   * The transformation string that was applied.
   */
  transformation?: string | undefined;
  /**
   * The unique signature of the transformation.
   */
  transformationSignature?: string | undefined;
  /**
   * The secure URL for accessing the derived resource.
   */
  secureUrl?: string | undefined;
};

export type Info = {
  /**
   * A 32-character hexadecimal asset ID.
   */
  assetId?: string | undefined;
  publicId?: string | undefined;
  assetFolder?: string | undefined;
  displayName?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resourceType?: string | undefined;
  /**
   * All supported delivery types.
   */
  type?: DeliveryTypeAll | undefined;
  createdAt?: Date | undefined;
  uploadedAt?: Date | undefined;
  bytes?: number | undefined;
  backupBytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspectRatio?: number | null | undefined;
  pixels?: number | null | undefined;
  /**
   * Included if 'tags=true' parameter is used.
   */
  tags?: Array<string> | null | undefined;
  /**
   * Included if 'context=true' parameter is used.
   */
  context?: ContextFullResponse | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  /**
   * The type of moderation applied to the asset.
   */
  moderationKind?: string | undefined;
  /**
   * The current status of the moderation process for the asset.
   */
  moderationStatus?: string | undefined;
  /**
   * Included if 'moderations=true' parameter is used.
   */
  moderation?: Array<InfoModeration> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secureUrl?: string | undefined;
  status?: string | undefined;
  accessControl?: Array<AccessControlItem> | null | undefined;
  etag?: string | undefined;
  /**
   * Whether the asset is animated (e.g., GIF, animated WebP). Null for non-animated assets.
   */
  animated?: boolean | null | undefined;
  /**
   * Duration in seconds for video/audio assets. Null for images.
   */
  duration?: number | null | undefined;
  /**
   * The subtype of the resource (e.g., for video). Null when not applicable.
   */
  resourceSubtype?: string | null | undefined;
  /**
   * The substatus of the resource. Null when not set.
   */
  substatus?: string | null | undefined;
  /**
   * Related assets linked to this resource. Null when none linked.
   */
  relatedAssets?: Array<InfoRelatedAsset> | null | undefined;
  lastUpdated?: InfoLastUpdated | null | undefined;
  /**
   * Cursor for paginating derived assets.
   */
  nextCursor?: string | undefined;
  derived?: Array<InfoDerived> | undefined;
  /**
   * Detected face rectangles. Included if 'faces=true' parameter is used.
   */
  faces?: Array<Array<number>> | null | undefined;
  /**
   * Face and custom coordinate data. Included if 'coordinates=true' parameter is used.
   */
  coordinates?: CoordinatesResponse | null | undefined;
  illustrationScore?: number | undefined;
  semiTransparent?: boolean | undefined;
  grayscale?: boolean | undefined;
  colors?: Array<Array<any>> | undefined;
  predominant?: { [k: string]: Array<Array<any>> } | undefined;
  versions?: Array<InfoVersion> | undefined;
  /**
   * Additional asset information (visual search, recognized people, etc.)
   */
  info?: InfoInfo | undefined;
  /**
   * Included if 'derived=true' parameter is used. Null when no derivatives exist.
   */
  derivatives?: Array<InfoDerivative> | null | undefined;
};

/** @internal */
export const InfoModeration$inboundSchema: z.ZodType<
  InfoModeration,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type InfoModeration$Outbound = {
  kind?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const InfoModeration$outboundSchema: z.ZodType<
  InfoModeration$Outbound,
  z.ZodTypeDef,
  InfoModeration
> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    updatedAt: "updated_at",
  });
});

export function infoModerationToJSON(infoModeration: InfoModeration): string {
  return JSON.stringify(InfoModeration$outboundSchema.parse(infoModeration));
}
export function infoModerationFromJSON(
  jsonString: string,
): SafeParseResult<InfoModeration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoModeration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoModeration' from JSON`,
  );
}

/** @internal */
export const InfoRelatedAsset$inboundSchema: z.ZodType<
  InfoRelatedAsset,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type InfoRelatedAsset$Outbound = {};

/** @internal */
export const InfoRelatedAsset$outboundSchema: z.ZodType<
  InfoRelatedAsset$Outbound,
  z.ZodTypeDef,
  InfoRelatedAsset
> = z.object({});

export function infoRelatedAssetToJSON(
  infoRelatedAsset: InfoRelatedAsset,
): string {
  return JSON.stringify(
    InfoRelatedAsset$outboundSchema.parse(infoRelatedAsset),
  );
}
export function infoRelatedAssetFromJSON(
  jsonString: string,
): SafeParseResult<InfoRelatedAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoRelatedAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoRelatedAsset' from JSON`,
  );
}

/** @internal */
export const InfoLastUpdated$inboundSchema: z.ZodType<
  InfoLastUpdated,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_control_updated_at: z.string().datetime({ offset: true }).transform(
    v => new Date(v)
  ).optional(),
  context_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  public_id_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  tags_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "access_control_updated_at": "accessControlUpdatedAt",
    "context_updated_at": "contextUpdatedAt",
    "metadata_updated_at": "metadataUpdatedAt",
    "public_id_updated_at": "publicIdUpdatedAt",
    "tags_updated_at": "tagsUpdatedAt",
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type InfoLastUpdated$Outbound = {
  access_control_updated_at?: string | undefined;
  context_updated_at?: string | undefined;
  metadata_updated_at?: string | undefined;
  public_id_updated_at?: string | undefined;
  tags_updated_at?: string | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const InfoLastUpdated$outboundSchema: z.ZodType<
  InfoLastUpdated$Outbound,
  z.ZodTypeDef,
  InfoLastUpdated
> = z.object({
  accessControlUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  contextUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  metadataUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  publicIdUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  tagsUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    accessControlUpdatedAt: "access_control_updated_at",
    contextUpdatedAt: "context_updated_at",
    metadataUpdatedAt: "metadata_updated_at",
    publicIdUpdatedAt: "public_id_updated_at",
    tagsUpdatedAt: "tags_updated_at",
    updatedAt: "updated_at",
  });
});

export function infoLastUpdatedToJSON(
  infoLastUpdated: InfoLastUpdated,
): string {
  return JSON.stringify(InfoLastUpdated$outboundSchema.parse(infoLastUpdated));
}
export function infoLastUpdatedFromJSON(
  jsonString: string,
): SafeParseResult<InfoLastUpdated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoLastUpdated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoLastUpdated' from JSON`,
  );
}

/** @internal */
export const InfoDerived$inboundSchema: z.ZodType<
  InfoDerived,
  z.ZodTypeDef,
  unknown
> = z.object({
  transformation: z.string().optional(),
  format: z.string().optional(),
  bytes: z.number().int().optional(),
  id: z.string().optional(),
  url: z.string().optional(),
  secure_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "secure_url": "secureUrl",
  });
});
/** @internal */
export type InfoDerived$Outbound = {
  transformation?: string | undefined;
  format?: string | undefined;
  bytes?: number | undefined;
  id?: string | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
};

/** @internal */
export const InfoDerived$outboundSchema: z.ZodType<
  InfoDerived$Outbound,
  z.ZodTypeDef,
  InfoDerived
> = z.object({
  transformation: z.string().optional(),
  format: z.string().optional(),
  bytes: z.number().int().optional(),
  id: z.string().optional(),
  url: z.string().optional(),
  secureUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    secureUrl: "secure_url",
  });
});

export function infoDerivedToJSON(infoDerived: InfoDerived): string {
  return JSON.stringify(InfoDerived$outboundSchema.parse(infoDerived));
}
export function infoDerivedFromJSON(
  jsonString: string,
): SafeParseResult<InfoDerived, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoDerived$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoDerived' from JSON`,
  );
}

/** @internal */
export const InfoVersion$inboundSchema: z.ZodType<
  InfoVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  version_id: z.string().optional(),
  version: z.string().optional(),
  format: z.nullable(z.string()).optional(),
  size: z.number().int().optional(),
  time: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  restorable: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "version_id": "versionId",
  });
});
/** @internal */
export type InfoVersion$Outbound = {
  version_id?: string | undefined;
  version?: string | undefined;
  format?: string | null | undefined;
  size?: number | undefined;
  time?: string | undefined;
  restorable?: boolean | undefined;
};

/** @internal */
export const InfoVersion$outboundSchema: z.ZodType<
  InfoVersion$Outbound,
  z.ZodTypeDef,
  InfoVersion
> = z.object({
  versionId: z.string().optional(),
  version: z.string().optional(),
  format: z.nullable(z.string()).optional(),
  size: z.number().int().optional(),
  time: z.date().transform(v => v.toISOString()).optional(),
  restorable: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    versionId: "version_id",
  });
});

export function infoVersionToJSON(infoVersion: InfoVersion): string {
  return JSON.stringify(InfoVersion$outboundSchema.parse(infoVersion));
}
export function infoVersionFromJSON(
  jsonString: string,
): SafeParseResult<InfoVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoVersion' from JSON`,
  );
}

/** @internal */
export const InfoInfo$inboundSchema: z.ZodType<
  InfoInfo,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type InfoInfo$Outbound = {};

/** @internal */
export const InfoInfo$outboundSchema: z.ZodType<
  InfoInfo$Outbound,
  z.ZodTypeDef,
  InfoInfo
> = z.object({});

export function infoInfoToJSON(infoInfo: InfoInfo): string {
  return JSON.stringify(InfoInfo$outboundSchema.parse(infoInfo));
}
export function infoInfoFromJSON(
  jsonString: string,
): SafeParseResult<InfoInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoInfo' from JSON`,
  );
}

/** @internal */
export const InfoDerivative$inboundSchema: z.ZodType<
  InfoDerivative,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  transformation: z.string().optional(),
  transformation_signature: z.string().optional(),
  secure_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "transformation_signature": "transformationSignature",
    "secure_url": "secureUrl",
  });
});
/** @internal */
export type InfoDerivative$Outbound = {
  id?: string | undefined;
  transformation?: string | undefined;
  transformation_signature?: string | undefined;
  secure_url?: string | undefined;
};

/** @internal */
export const InfoDerivative$outboundSchema: z.ZodType<
  InfoDerivative$Outbound,
  z.ZodTypeDef,
  InfoDerivative
> = z.object({
  id: z.string().optional(),
  transformation: z.string().optional(),
  transformationSignature: z.string().optional(),
  secureUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    transformationSignature: "transformation_signature",
    secureUrl: "secure_url",
  });
});

export function infoDerivativeToJSON(infoDerivative: InfoDerivative): string {
  return JSON.stringify(InfoDerivative$outboundSchema.parse(infoDerivative));
}
export function infoDerivativeFromJSON(
  jsonString: string,
): SafeParseResult<InfoDerivative, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoDerivative$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoDerivative' from JSON`,
  );
}

/** @internal */
export const Info$inboundSchema: z.ZodType<Info, z.ZodTypeDef, unknown> = z
  .object({
    asset_id: z.string().optional(),
    public_id: z.string().optional(),
    asset_folder: z.string().optional(),
    display_name: z.string().optional(),
    folder: z.string().optional(),
    filename: z.string().optional(),
    format: z.string().optional(),
    version: z.number().int().optional(),
    resource_type: z.string().optional(),
    type: DeliveryTypeAll$inboundSchema.optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    uploaded_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    bytes: z.number().int().optional(),
    backup_bytes: z.number().int().optional(),
    width: z.nullable(z.number().int()).optional(),
    height: z.nullable(z.number().int()).optional(),
    aspect_ratio: z.nullable(z.number()).optional(),
    pixels: z.nullable(z.number().int()).optional(),
    tags: z.nullable(z.array(z.string())).optional(),
    context: z.nullable(ContextFullResponse$inboundSchema).optional(),
    metadata: z.record(z.any()).optional(),
    moderation_kind: z.string().optional(),
    moderation_status: z.string().optional(),
    moderation: z.array(z.lazy(() => InfoModeration$inboundSchema)).optional(),
    backup: z.boolean().optional(),
    url: z.string().optional(),
    secure_url: z.string().optional(),
    status: z.string().optional(),
    access_control: z.nullable(z.array(AccessControlItem$inboundSchema))
      .optional(),
    etag: z.string().optional(),
    animated: z.nullable(z.boolean()).optional(),
    duration: z.nullable(z.number()).optional(),
    resource_subtype: z.nullable(z.string()).optional(),
    substatus: z.nullable(z.string()).optional(),
    related_assets: z.nullable(
      z.array(z.lazy(() => InfoRelatedAsset$inboundSchema)),
    ).optional(),
    last_updated: z.nullable(z.lazy(() => InfoLastUpdated$inboundSchema))
      .optional(),
    next_cursor: z.string().optional(),
    derived: z.array(z.lazy(() => InfoDerived$inboundSchema)).optional(),
    faces: z.nullable(z.array(z.array(z.number().int()))).optional(),
    coordinates: z.nullable(CoordinatesResponse$inboundSchema).optional(),
    illustration_score: z.number().optional(),
    semi_transparent: z.boolean().optional(),
    grayscale: z.boolean().optional(),
    colors: z.array(z.array(z.any())).optional(),
    predominant: z.record(z.array(z.array(z.any()))).optional(),
    versions: z.array(z.lazy(() => InfoVersion$inboundSchema)).optional(),
    info: z.lazy(() => InfoInfo$inboundSchema).optional(),
    derivatives: z.nullable(z.array(z.lazy(() => InfoDerivative$inboundSchema)))
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "public_id": "publicId",
      "asset_folder": "assetFolder",
      "display_name": "displayName",
      "resource_type": "resourceType",
      "created_at": "createdAt",
      "uploaded_at": "uploadedAt",
      "backup_bytes": "backupBytes",
      "aspect_ratio": "aspectRatio",
      "moderation_kind": "moderationKind",
      "moderation_status": "moderationStatus",
      "secure_url": "secureUrl",
      "access_control": "accessControl",
      "resource_subtype": "resourceSubtype",
      "related_assets": "relatedAssets",
      "last_updated": "lastUpdated",
      "next_cursor": "nextCursor",
      "illustration_score": "illustrationScore",
      "semi_transparent": "semiTransparent",
    });
  });
/** @internal */
export type Info$Outbound = {
  asset_id?: string | undefined;
  public_id?: string | undefined;
  asset_folder?: string | undefined;
  display_name?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resource_type?: string | undefined;
  type?: DeliveryTypeAll$Outbound | undefined;
  created_at?: string | undefined;
  uploaded_at?: string | undefined;
  bytes?: number | undefined;
  backup_bytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspect_ratio?: number | null | undefined;
  pixels?: number | null | undefined;
  tags?: Array<string> | null | undefined;
  context?: ContextFullResponse$Outbound | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  moderation_kind?: string | undefined;
  moderation_status?: string | undefined;
  moderation?: Array<InfoModeration$Outbound> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  status?: string | undefined;
  access_control?: Array<AccessControlItem$Outbound> | null | undefined;
  etag?: string | undefined;
  animated?: boolean | null | undefined;
  duration?: number | null | undefined;
  resource_subtype?: string | null | undefined;
  substatus?: string | null | undefined;
  related_assets?: Array<InfoRelatedAsset$Outbound> | null | undefined;
  last_updated?: InfoLastUpdated$Outbound | null | undefined;
  next_cursor?: string | undefined;
  derived?: Array<InfoDerived$Outbound> | undefined;
  faces?: Array<Array<number>> | null | undefined;
  coordinates?: CoordinatesResponse$Outbound | null | undefined;
  illustration_score?: number | undefined;
  semi_transparent?: boolean | undefined;
  grayscale?: boolean | undefined;
  colors?: Array<Array<any>> | undefined;
  predominant?: { [k: string]: Array<Array<any>> } | undefined;
  versions?: Array<InfoVersion$Outbound> | undefined;
  info?: InfoInfo$Outbound | undefined;
  derivatives?: Array<InfoDerivative$Outbound> | null | undefined;
};

/** @internal */
export const Info$outboundSchema: z.ZodType<Info$Outbound, z.ZodTypeDef, Info> =
  z.object({
    assetId: z.string().optional(),
    publicId: z.string().optional(),
    assetFolder: z.string().optional(),
    displayName: z.string().optional(),
    folder: z.string().optional(),
    filename: z.string().optional(),
    format: z.string().optional(),
    version: z.number().int().optional(),
    resourceType: z.string().optional(),
    type: DeliveryTypeAll$outboundSchema.optional(),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    uploadedAt: z.date().transform(v => v.toISOString()).optional(),
    bytes: z.number().int().optional(),
    backupBytes: z.number().int().optional(),
    width: z.nullable(z.number().int()).optional(),
    height: z.nullable(z.number().int()).optional(),
    aspectRatio: z.nullable(z.number()).optional(),
    pixels: z.nullable(z.number().int()).optional(),
    tags: z.nullable(z.array(z.string())).optional(),
    context: z.nullable(ContextFullResponse$outboundSchema).optional(),
    metadata: z.record(z.any()).optional(),
    moderationKind: z.string().optional(),
    moderationStatus: z.string().optional(),
    moderation: z.array(z.lazy(() => InfoModeration$outboundSchema)).optional(),
    backup: z.boolean().optional(),
    url: z.string().optional(),
    secureUrl: z.string().optional(),
    status: z.string().optional(),
    accessControl: z.nullable(z.array(AccessControlItem$outboundSchema))
      .optional(),
    etag: z.string().optional(),
    animated: z.nullable(z.boolean()).optional(),
    duration: z.nullable(z.number()).optional(),
    resourceSubtype: z.nullable(z.string()).optional(),
    substatus: z.nullable(z.string()).optional(),
    relatedAssets: z.nullable(
      z.array(z.lazy(() => InfoRelatedAsset$outboundSchema)),
    ).optional(),
    lastUpdated: z.nullable(z.lazy(() => InfoLastUpdated$outboundSchema))
      .optional(),
    nextCursor: z.string().optional(),
    derived: z.array(z.lazy(() => InfoDerived$outboundSchema)).optional(),
    faces: z.nullable(z.array(z.array(z.number().int()))).optional(),
    coordinates: z.nullable(CoordinatesResponse$outboundSchema).optional(),
    illustrationScore: z.number().optional(),
    semiTransparent: z.boolean().optional(),
    grayscale: z.boolean().optional(),
    colors: z.array(z.array(z.any())).optional(),
    predominant: z.record(z.array(z.array(z.any()))).optional(),
    versions: z.array(z.lazy(() => InfoVersion$outboundSchema)).optional(),
    info: z.lazy(() => InfoInfo$outboundSchema).optional(),
    derivatives: z.nullable(
      z.array(z.lazy(() => InfoDerivative$outboundSchema)),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      assetId: "asset_id",
      publicId: "public_id",
      assetFolder: "asset_folder",
      displayName: "display_name",
      resourceType: "resource_type",
      createdAt: "created_at",
      uploadedAt: "uploaded_at",
      backupBytes: "backup_bytes",
      aspectRatio: "aspect_ratio",
      moderationKind: "moderation_kind",
      moderationStatus: "moderation_status",
      secureUrl: "secure_url",
      accessControl: "access_control",
      resourceSubtype: "resource_subtype",
      relatedAssets: "related_assets",
      lastUpdated: "last_updated",
      nextCursor: "next_cursor",
      illustrationScore: "illustration_score",
      semiTransparent: "semi_transparent",
    });
  });

export function infoToJSON(info: Info): string {
  return JSON.stringify(Info$outboundSchema.parse(info));
}
export function infoFromJSON(
  jsonString: string,
): SafeParseResult<Info, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Info$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Info' from JSON`,
  );
}
