/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AddonQuota,
  AddonQuota$inboundSchema,
  AddonQuota$Outbound,
  AddonQuota$outboundSchema,
} from "./addonquota.js";

/**
 * Rate limit information for the account's add-on quotas.
 */
export type Limits = {
  /**
   * Per-add-on quota usage for this account.
   */
  addonsQuota?: Array<AddonQuota> | undefined;
};

/** @internal */
export const Limits$inboundSchema: z.ZodType<Limits, z.ZodTypeDef, unknown> = z
  .object({
    addons_quota: z.array(AddonQuota$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "addons_quota": "addonsQuota",
    });
  });
/** @internal */
export type Limits$Outbound = {
  addons_quota?: Array<AddonQuota$Outbound> | undefined;
};

/** @internal */
export const Limits$outboundSchema: z.ZodType<
  Limits$Outbound,
  z.ZodTypeDef,
  Limits
> = z.object({
  addonsQuota: z.array(AddonQuota$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    addonsQuota: "addons_quota",
  });
});

export function limitsToJSON(limits: Limits): string {
  return JSON.stringify(Limits$outboundSchema.parse(limits));
}
export function limitsFromJSON(
  jsonString: string,
): SafeParseResult<Limits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Limits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Limits' from JSON`,
  );
}
