/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The delivery type for filtering resources in list operations.
 */
export const ListStorageType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Fetch: "fetch",
  List: "list",
} as const;
/**
 * The delivery type for filtering resources in list operations.
 */
export type ListStorageType = ClosedEnum<typeof ListStorageType>;

/** @internal */
export const ListStorageType$inboundSchema: z.ZodNativeEnum<
  typeof ListStorageType
> = z.nativeEnum(ListStorageType);

/** @internal */
export const ListStorageType$outboundSchema: z.ZodNativeEnum<
  typeof ListStorageType
> = ListStorageType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListStorageType$ {
  /** @deprecated use `ListStorageType$inboundSchema` instead. */
  export const inboundSchema = ListStorageType$inboundSchema;
  /** @deprecated use `ListStorageType$outboundSchema` instead. */
  export const outboundSchema = ListStorageType$outboundSchema;
}
