/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A reference to a managed asset in the caller's product environment, by
 *
 * @remarks
 * asset ID.
 */
export type ManagedAssetReference = {
  /**
   * Discriminator identifying this as a managed-asset reference.
   */
  sourceType: "managed_asset";
  /**
   * Cloudinary asset ID of the reference image. READ permission is enforced.
   */
  assetId: string;
};

/** @internal */
export const ManagedAssetReference$inboundSchema: z.ZodType<
  ManagedAssetReference,
  z.ZodTypeDef,
  unknown
> = z.object({
  source_type: z.literal("managed_asset"),
  asset_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "source_type": "sourceType",
    "asset_id": "assetId",
  });
});
/** @internal */
export type ManagedAssetReference$Outbound = {
  source_type: "managed_asset";
  asset_id: string;
};

/** @internal */
export const ManagedAssetReference$outboundSchema: z.ZodType<
  ManagedAssetReference$Outbound,
  z.ZodTypeDef,
  ManagedAssetReference
> = z.object({
  sourceType: z.literal("managed_asset"),
  assetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    sourceType: "source_type",
    assetId: "asset_id",
  });
});

export function managedAssetReferenceToJSON(
  managedAssetReference: ManagedAssetReference,
): string {
  return JSON.stringify(
    ManagedAssetReference$outboundSchema.parse(managedAssetReference),
  );
}
export function managedAssetReferenceFromJSON(
  jsonString: string,
): SafeParseResult<ManagedAssetReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagedAssetReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagedAssetReference' from JSON`,
  );
}
