/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Store the output as a permanent managed asset in your Cloudinary product environment (the default).
 */
export type ManagedAssetTarget = {
  /**
   * Discriminator identifying this as a managed-asset target.
   */
  targetType: "managed_asset";
  /**
   * Public ID to store the asset under. Auto-assigned when omitted.
   */
  publicId?: string | undefined;
  /**
   * Upload preset to apply. Uses the product environment's default when omitted.
   */
  uploadPreset?: string | undefined;
};

/** @internal */
export const ManagedAssetTarget$inboundSchema: z.ZodType<
  ManagedAssetTarget,
  z.ZodTypeDef,
  unknown
> = z.object({
  target_type: z.literal("managed_asset"),
  public_id: z.string().optional(),
  upload_preset: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "target_type": "targetType",
    "public_id": "publicId",
    "upload_preset": "uploadPreset",
  });
});
/** @internal */
export type ManagedAssetTarget$Outbound = {
  target_type: "managed_asset";
  public_id?: string | undefined;
  upload_preset?: string | undefined;
};

/** @internal */
export const ManagedAssetTarget$outboundSchema: z.ZodType<
  ManagedAssetTarget$Outbound,
  z.ZodTypeDef,
  ManagedAssetTarget
> = z.object({
  targetType: z.literal("managed_asset"),
  publicId: z.string().optional(),
  uploadPreset: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    targetType: "target_type",
    publicId: "public_id",
    uploadPreset: "upload_preset",
  });
});

export function managedAssetTargetToJSON(
  managedAssetTarget: ManagedAssetTarget,
): string {
  return JSON.stringify(
    ManagedAssetTarget$outboundSchema.parse(managedAssetTarget),
  );
}
export function managedAssetTargetFromJSON(
  jsonString: string,
): SafeParseResult<ManagedAssetTarget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagedAssetTarget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagedAssetTarget' from JSON`,
  );
}
