/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ModerationKind = {
  Manual: "manual",
  Webpurify: "webpurify",
  AwsRek: "aws_rek",
  AwsRekVideo: "aws_rek_video",
  PerceptionPoint: "perception_point",
  GoogleVideoModeration: "google_video_moderation",
  Duplicate: "duplicate",
} as const;
export type ModerationKind = ClosedEnum<typeof ModerationKind>;

/** @internal */
export const ModerationKind$inboundSchema: z.ZodNativeEnum<
  typeof ModerationKind
> = z.nativeEnum(ModerationKind);
/** @internal */
export const ModerationKind$outboundSchema: z.ZodNativeEnum<
  typeof ModerationKind
> = ModerationKind$inboundSchema;
