/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ModelAuto,
  ModelAuto$inboundSchema,
  ModelAuto$Outbound,
  ModelAuto$outboundSchema,
} from "./modelauto.js";
import {
  ModelByFamily,
  ModelByFamily$inboundSchema,
  ModelByFamily$Outbound,
  ModelByFamily$outboundSchema,
} from "./modelbyfamily.js";
import {
  ModelById,
  ModelById$inboundSchema,
  ModelById$Outbound,
  ModelById$outboundSchema,
} from "./modelbyid.js";

/**
 * Selects the model, in one of three mutually exclusive forms (omit to use
 *
 * @remarks
 * the global default):
 *   * `ModelByFamily`: `family` (+ optional `tier`); the stable-over-time
 *     selector.
 *   * `ModelById`: an explicit `id`, pinning one exact model.
 *   * `ModelAuto`: `mode: auto`, letting the service choose the model for
 *     the request (+ optional `preference`).
 */
export type ModelSelection = ModelByFamily | ModelById | ModelAuto;

/** @internal */
export const ModelSelection$inboundSchema: z.ZodType<
  ModelSelection,
  z.ZodTypeDef,
  unknown
> = z.union([
  ModelByFamily$inboundSchema,
  ModelById$inboundSchema,
  ModelAuto$inboundSchema,
]);
/** @internal */
export type ModelSelection$Outbound =
  | ModelByFamily$Outbound
  | ModelById$Outbound
  | ModelAuto$Outbound;

/** @internal */
export const ModelSelection$outboundSchema: z.ZodType<
  ModelSelection$Outbound,
  z.ZodTypeDef,
  ModelSelection
> = z.union([
  ModelByFamily$outboundSchema,
  ModelById$outboundSchema,
  ModelAuto$outboundSchema,
]);

export function modelSelectionToJSON(modelSelection: ModelSelection): string {
  return JSON.stringify(ModelSelection$outboundSchema.parse(modelSelection));
}
export function modelSelectionFromJSON(
  jsonString: string,
): SafeParseResult<ModelSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelSelection' from JSON`,
  );
}
