/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FolderNamePath,
  FolderNamePath$inboundSchema,
  FolderNamePath$Outbound,
  FolderNamePath$outboundSchema,
} from "./foldernamepath.js";

export type MoveFolderResponse = {
  from: FolderNamePath;
  to: FolderNamePath;
};

/** @internal */
export const MoveFolderResponse$inboundSchema: z.ZodType<
  MoveFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: FolderNamePath$inboundSchema,
  to: FolderNamePath$inboundSchema,
});
/** @internal */
export type MoveFolderResponse$Outbound = {
  from: FolderNamePath$Outbound;
  to: FolderNamePath$Outbound;
};

/** @internal */
export const MoveFolderResponse$outboundSchema: z.ZodType<
  MoveFolderResponse$Outbound,
  z.ZodTypeDef,
  MoveFolderResponse
> = z.object({
  from: FolderNamePath$outboundSchema,
  to: FolderNamePath$outboundSchema,
});

export function moveFolderResponseToJSON(
  moveFolderResponse: MoveFolderResponse,
): string {
  return JSON.stringify(
    MoveFolderResponse$outboundSchema.parse(moveFolderResponse),
  );
}
export function moveFolderResponseFromJSON(
  jsonString: string,
): SafeParseResult<MoveFolderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MoveFolderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MoveFolderResponse' from JSON`,
  );
}
