/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PeopleInspectionGroup,
  PeopleInspectionGroup$inboundSchema,
  PeopleInspectionGroup$Outbound,
  PeopleInspectionGroup$outboundSchema,
} from "./peopleinspectiongroup.js";

/**
 * A map of inspectable types to the items and actions to inspect.
 */
export type PeopleInspectionTargets = {
  /**
   * The items to inspect for a type and the actions to check against them.
   */
  person?: PeopleInspectionGroup | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const PeopleInspectionTargets$inboundSchema: z.ZodType<
  PeopleInspectionTargets,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    Person: PeopleInspectionGroup$inboundSchema.optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "Person": "person",
  });
});
/** @internal */
export type PeopleInspectionTargets$Outbound = {
  Person?: PeopleInspectionGroup$Outbound | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const PeopleInspectionTargets$outboundSchema: z.ZodType<
  PeopleInspectionTargets$Outbound,
  z.ZodTypeDef,
  PeopleInspectionTargets
> = z.object({
  person: PeopleInspectionGroup$outboundSchema.optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      person: "Person",
      additionalProperties: null,
    }),
  };
});

export function peopleInspectionTargetsToJSON(
  peopleInspectionTargets: PeopleInspectionTargets,
): string {
  return JSON.stringify(
    PeopleInspectionTargets$outboundSchema.parse(peopleInspectionTargets),
  );
}
export function peopleInspectionTargetsFromJSON(
  jsonString: string,
): SafeParseResult<PeopleInspectionTargets, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PeopleInspectionTargets$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PeopleInspectionTargets' from JSON`,
  );
}
