/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ManagedAssetReference,
  ManagedAssetReference$inboundSchema,
  ManagedAssetReference$Outbound,
  ManagedAssetReference$outboundSchema,
} from "./managedassetreference.js";
import {
  UrlReference,
  UrlReference$inboundSchema,
  UrlReference$Outbound,
  UrlReference$outboundSchema,
} from "./urlreference.js";

/**
 * A single reference image, in **one** of two mutually exclusive forms
 *
 * @remarks
 * determined by `source_type`:
 *   * `ManagedAssetReference`: a managed asset in the caller's product
 *     environment, by `asset_id` (read permission is checked).
 *   * `UrlReference`: an external image by HTTPS `url`.
 */
export type ReferenceImage = ManagedAssetReference | UrlReference;

/** @internal */
export const ReferenceImage$inboundSchema: z.ZodType<
  ReferenceImage,
  z.ZodTypeDef,
  unknown
> = z.union([ManagedAssetReference$inboundSchema, UrlReference$inboundSchema]);
/** @internal */
export type ReferenceImage$Outbound =
  | ManagedAssetReference$Outbound
  | UrlReference$Outbound;

/** @internal */
export const ReferenceImage$outboundSchema: z.ZodType<
  ReferenceImage$Outbound,
  z.ZodTypeDef,
  ReferenceImage
> = z.union([
  ManagedAssetReference$outboundSchema,
  UrlReference$outboundSchema,
]);

export function referenceImageToJSON(referenceImage: ReferenceImage): string {
  return JSON.stringify(ReferenceImage$outboundSchema.parse(referenceImage));
}
export function referenceImageFromJSON(
  jsonString: string,
): SafeParseResult<ReferenceImage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReferenceImage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReferenceImage' from JSON`,
  );
}
