/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The asset relation request.
 */
export type RelateAssetsByPublicIdRequest = {
  /**
   * Relates the asset to all the other assets specified in this array of up to 10 assets, specified as resource_type/type/public_id.
   */
  assetsToRelate: Array<string>;
};

/** @internal */
export const RelateAssetsByPublicIdRequest$inboundSchema: z.ZodType<
  RelateAssetsByPublicIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  assets_to_relate: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "assets_to_relate": "assetsToRelate",
  });
});
/** @internal */
export type RelateAssetsByPublicIdRequest$Outbound = {
  assets_to_relate: Array<string>;
};

/** @internal */
export const RelateAssetsByPublicIdRequest$outboundSchema: z.ZodType<
  RelateAssetsByPublicIdRequest$Outbound,
  z.ZodTypeDef,
  RelateAssetsByPublicIdRequest
> = z.object({
  assetsToRelate: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    assetsToRelate: "assets_to_relate",
  });
});

export function relateAssetsByPublicIdRequestToJSON(
  relateAssetsByPublicIdRequest: RelateAssetsByPublicIdRequest,
): string {
  return JSON.stringify(
    RelateAssetsByPublicIdRequest$outboundSchema.parse(
      relateAssetsByPublicIdRequest,
    ),
  );
}
export function relateAssetsByPublicIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<RelateAssetsByPublicIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RelateAssetsByPublicIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RelateAssetsByPublicIdRequest' from JSON`,
  );
}
