/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessControlItem,
  AccessControlItem$inboundSchema,
  AccessControlItem$Outbound,
  AccessControlItem$outboundSchema,
} from "./accesscontrolitem.js";
import {
  ContextFullResponse,
  ContextFullResponse$inboundSchema,
  ContextFullResponse$Outbound,
  ContextFullResponse$outboundSchema,
} from "./contextfullresponse.js";
import {
  CoordinatesResponse,
  CoordinatesResponse$inboundSchema,
  CoordinatesResponse$Outbound,
  CoordinatesResponse$outboundSchema,
} from "./coordinatesresponse.js";
import {
  DeliveryTypeAll,
  DeliveryTypeAll$inboundSchema,
  DeliveryTypeAll$Outbound,
  DeliveryTypeAll$outboundSchema,
} from "./deliverytypeall.js";

export type ResourceInternalResponseModeration = {
  kind?: string | undefined;
  status?: string | undefined;
  updatedAt?: Date | undefined;
};

export type ResourceInternalResponseRelatedAsset = {};

export type ResourceInternalResponseLastUpdated = {
  accessControlUpdatedAt?: Date | undefined;
  contextUpdatedAt?: Date | undefined;
  metadataUpdatedAt?: Date | undefined;
  publicIdUpdatedAt?: Date | undefined;
  tagsUpdatedAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

export type ResourceInternalResponseDerived = {
  transformation?: string | undefined;
  format?: string | undefined;
  bytes?: number | undefined;
  id?: string | undefined;
  url?: string | undefined;
  secureUrl?: string | undefined;
};

export type ResourceInternalResponseVersion = {
  /**
   * Hexadecimal version ID; length is a positive multiple of 32 (typically 32 or 64).
   */
  versionId?: string | undefined;
  version?: string | undefined;
  format?: string | null | undefined;
  size?: number | undefined;
  time?: Date | undefined;
  restorable?: boolean | undefined;
};

/**
 * Additional asset information (visual search, recognized people, etc.)
 */
export type ResourceInternalResponseInfo = {};

export type ResourceInternalResponseDerivative = {
  /**
   * The unique identifier of the derived resource.
   */
  id?: string | undefined;
  /**
   * The transformation string that was applied.
   */
  transformation?: string | undefined;
  /**
   * The unique signature of the transformation.
   */
  transformationSignature?: string | undefined;
  /**
   * The secure URL for accessing the derived resource.
   */
  secureUrl?: string | undefined;
};

/**
 * The details of a single asset. Returns the standard asset fields, plus additional
 *
 * @remarks
 * internal fields when accessed over the internal transport.
 */
export type ResourceInternalResponse = {
  /**
   * A 32-character hexadecimal asset ID.
   */
  assetId?: string | undefined;
  publicId?: string | undefined;
  assetFolder?: string | undefined;
  displayName?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resourceType?: string | undefined;
  /**
   * All supported delivery types.
   */
  type?: DeliveryTypeAll | undefined;
  createdAt?: Date | undefined;
  uploadedAt?: Date | undefined;
  bytes?: number | undefined;
  backupBytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspectRatio?: number | null | undefined;
  pixels?: number | null | undefined;
  /**
   * Included if 'tags=true' parameter is used.
   */
  tags?: Array<string> | null | undefined;
  /**
   * Included if 'context=true' parameter is used.
   */
  context?: ContextFullResponse | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  /**
   * The type of moderation applied to the asset.
   */
  moderationKind?: string | undefined;
  /**
   * The current status of the moderation process for the asset.
   */
  moderationStatus?: string | undefined;
  /**
   * Included if 'moderations=true' parameter is used.
   */
  moderation?: Array<ResourceInternalResponseModeration> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secureUrl?: string | undefined;
  status?: string | undefined;
  accessControl?: Array<AccessControlItem> | null | undefined;
  etag?: string | undefined;
  /**
   * Whether the asset is animated (e.g., GIF, animated WebP). Null for non-animated assets.
   */
  animated?: boolean | null | undefined;
  /**
   * Duration in seconds for video/audio assets. Null for images.
   */
  duration?: number | null | undefined;
  /**
   * The subtype of the resource (e.g., for video). Null when not applicable.
   */
  resourceSubtype?: string | null | undefined;
  /**
   * The substatus of the resource. Null when not set.
   */
  substatus?: string | null | undefined;
  /**
   * Related assets linked to this resource. Null when none linked.
   */
  relatedAssets?:
    | Array<ResourceInternalResponseRelatedAsset>
    | null
    | undefined;
  lastUpdated?: ResourceInternalResponseLastUpdated | null | undefined;
  /**
   * Cursor for paginating derived assets.
   */
  nextCursor?: string | undefined;
  derived?: Array<ResourceInternalResponseDerived> | undefined;
  /**
   * Detected face rectangles. Included if 'faces=true' parameter is used.
   */
  faces?: Array<Array<number>> | null | undefined;
  /**
   * Face and custom coordinate data. Included if 'coordinates=true' parameter is used.
   */
  coordinates?: CoordinatesResponse | null | undefined;
  illustrationScore?: number | undefined;
  semiTransparent?: boolean | undefined;
  grayscale?: boolean | undefined;
  colors?: Array<Array<any>> | undefined;
  predominant?: { [k: string]: Array<Array<any>> } | undefined;
  versions?: Array<ResourceInternalResponseVersion> | undefined;
  /**
   * Additional asset information (visual search, recognized people, etc.)
   */
  info?: ResourceInternalResponseInfo | undefined;
  /**
   * Included if 'derived=true' parameter is used. Null when no derivatives exist.
   */
  derivatives?: Array<ResourceInternalResponseDerivative> | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ResourceInternalResponseModeration$inboundSchema: z.ZodType<
  ResourceInternalResponseModeration,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type ResourceInternalResponseModeration$Outbound = {
  kind?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const ResourceInternalResponseModeration$outboundSchema: z.ZodType<
  ResourceInternalResponseModeration$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseModeration
> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    updatedAt: "updated_at",
  });
});

export function resourceInternalResponseModerationToJSON(
  resourceInternalResponseModeration: ResourceInternalResponseModeration,
): string {
  return JSON.stringify(
    ResourceInternalResponseModeration$outboundSchema.parse(
      resourceInternalResponseModeration,
    ),
  );
}
export function resourceInternalResponseModerationFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseModeration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ResourceInternalResponseModeration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseModeration' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponseRelatedAsset$inboundSchema: z.ZodType<
  ResourceInternalResponseRelatedAsset,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ResourceInternalResponseRelatedAsset$Outbound = {};

/** @internal */
export const ResourceInternalResponseRelatedAsset$outboundSchema: z.ZodType<
  ResourceInternalResponseRelatedAsset$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseRelatedAsset
> = z.object({});

export function resourceInternalResponseRelatedAssetToJSON(
  resourceInternalResponseRelatedAsset: ResourceInternalResponseRelatedAsset,
): string {
  return JSON.stringify(
    ResourceInternalResponseRelatedAsset$outboundSchema.parse(
      resourceInternalResponseRelatedAsset,
    ),
  );
}
export function resourceInternalResponseRelatedAssetFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseRelatedAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ResourceInternalResponseRelatedAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseRelatedAsset' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponseLastUpdated$inboundSchema: z.ZodType<
  ResourceInternalResponseLastUpdated,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_control_updated_at: z.string().datetime({ offset: true }).transform(
    v => new Date(v)
  ).optional(),
  context_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  public_id_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  tags_updated_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "access_control_updated_at": "accessControlUpdatedAt",
    "context_updated_at": "contextUpdatedAt",
    "metadata_updated_at": "metadataUpdatedAt",
    "public_id_updated_at": "publicIdUpdatedAt",
    "tags_updated_at": "tagsUpdatedAt",
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type ResourceInternalResponseLastUpdated$Outbound = {
  access_control_updated_at?: string | undefined;
  context_updated_at?: string | undefined;
  metadata_updated_at?: string | undefined;
  public_id_updated_at?: string | undefined;
  tags_updated_at?: string | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const ResourceInternalResponseLastUpdated$outboundSchema: z.ZodType<
  ResourceInternalResponseLastUpdated$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseLastUpdated
> = z.object({
  accessControlUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  contextUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  metadataUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  publicIdUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  tagsUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    accessControlUpdatedAt: "access_control_updated_at",
    contextUpdatedAt: "context_updated_at",
    metadataUpdatedAt: "metadata_updated_at",
    publicIdUpdatedAt: "public_id_updated_at",
    tagsUpdatedAt: "tags_updated_at",
    updatedAt: "updated_at",
  });
});

export function resourceInternalResponseLastUpdatedToJSON(
  resourceInternalResponseLastUpdated: ResourceInternalResponseLastUpdated,
): string {
  return JSON.stringify(
    ResourceInternalResponseLastUpdated$outboundSchema.parse(
      resourceInternalResponseLastUpdated,
    ),
  );
}
export function resourceInternalResponseLastUpdatedFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseLastUpdated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ResourceInternalResponseLastUpdated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseLastUpdated' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponseDerived$inboundSchema: z.ZodType<
  ResourceInternalResponseDerived,
  z.ZodTypeDef,
  unknown
> = z.object({
  transformation: z.string().optional(),
  format: z.string().optional(),
  bytes: z.number().int().optional(),
  id: z.string().optional(),
  url: z.string().optional(),
  secure_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "secure_url": "secureUrl",
  });
});
/** @internal */
export type ResourceInternalResponseDerived$Outbound = {
  transformation?: string | undefined;
  format?: string | undefined;
  bytes?: number | undefined;
  id?: string | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
};

/** @internal */
export const ResourceInternalResponseDerived$outboundSchema: z.ZodType<
  ResourceInternalResponseDerived$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseDerived
> = z.object({
  transformation: z.string().optional(),
  format: z.string().optional(),
  bytes: z.number().int().optional(),
  id: z.string().optional(),
  url: z.string().optional(),
  secureUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    secureUrl: "secure_url",
  });
});

export function resourceInternalResponseDerivedToJSON(
  resourceInternalResponseDerived: ResourceInternalResponseDerived,
): string {
  return JSON.stringify(
    ResourceInternalResponseDerived$outboundSchema.parse(
      resourceInternalResponseDerived,
    ),
  );
}
export function resourceInternalResponseDerivedFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseDerived, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceInternalResponseDerived$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseDerived' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponseVersion$inboundSchema: z.ZodType<
  ResourceInternalResponseVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  version_id: z.string().optional(),
  version: z.string().optional(),
  format: z.nullable(z.string()).optional(),
  size: z.number().int().optional(),
  time: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  restorable: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "version_id": "versionId",
  });
});
/** @internal */
export type ResourceInternalResponseVersion$Outbound = {
  version_id?: string | undefined;
  version?: string | undefined;
  format?: string | null | undefined;
  size?: number | undefined;
  time?: string | undefined;
  restorable?: boolean | undefined;
};

/** @internal */
export const ResourceInternalResponseVersion$outboundSchema: z.ZodType<
  ResourceInternalResponseVersion$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseVersion
> = z.object({
  versionId: z.string().optional(),
  version: z.string().optional(),
  format: z.nullable(z.string()).optional(),
  size: z.number().int().optional(),
  time: z.date().transform(v => v.toISOString()).optional(),
  restorable: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    versionId: "version_id",
  });
});

export function resourceInternalResponseVersionToJSON(
  resourceInternalResponseVersion: ResourceInternalResponseVersion,
): string {
  return JSON.stringify(
    ResourceInternalResponseVersion$outboundSchema.parse(
      resourceInternalResponseVersion,
    ),
  );
}
export function resourceInternalResponseVersionFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceInternalResponseVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseVersion' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponseInfo$inboundSchema: z.ZodType<
  ResourceInternalResponseInfo,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ResourceInternalResponseInfo$Outbound = {};

/** @internal */
export const ResourceInternalResponseInfo$outboundSchema: z.ZodType<
  ResourceInternalResponseInfo$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseInfo
> = z.object({});

export function resourceInternalResponseInfoToJSON(
  resourceInternalResponseInfo: ResourceInternalResponseInfo,
): string {
  return JSON.stringify(
    ResourceInternalResponseInfo$outboundSchema.parse(
      resourceInternalResponseInfo,
    ),
  );
}
export function resourceInternalResponseInfoFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceInternalResponseInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseInfo' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponseDerivative$inboundSchema: z.ZodType<
  ResourceInternalResponseDerivative,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  transformation: z.string().optional(),
  transformation_signature: z.string().optional(),
  secure_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "transformation_signature": "transformationSignature",
    "secure_url": "secureUrl",
  });
});
/** @internal */
export type ResourceInternalResponseDerivative$Outbound = {
  id?: string | undefined;
  transformation?: string | undefined;
  transformation_signature?: string | undefined;
  secure_url?: string | undefined;
};

/** @internal */
export const ResourceInternalResponseDerivative$outboundSchema: z.ZodType<
  ResourceInternalResponseDerivative$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponseDerivative
> = z.object({
  id: z.string().optional(),
  transformation: z.string().optional(),
  transformationSignature: z.string().optional(),
  secureUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    transformationSignature: "transformation_signature",
    secureUrl: "secure_url",
  });
});

export function resourceInternalResponseDerivativeToJSON(
  resourceInternalResponseDerivative: ResourceInternalResponseDerivative,
): string {
  return JSON.stringify(
    ResourceInternalResponseDerivative$outboundSchema.parse(
      resourceInternalResponseDerivative,
    ),
  );
}
export function resourceInternalResponseDerivativeFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponseDerivative, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ResourceInternalResponseDerivative$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponseDerivative' from JSON`,
  );
}

/** @internal */
export const ResourceInternalResponse$inboundSchema: z.ZodType<
  ResourceInternalResponse,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    asset_id: z.string().optional(),
    public_id: z.string().optional(),
    asset_folder: z.string().optional(),
    display_name: z.string().optional(),
    folder: z.string().optional(),
    filename: z.string().optional(),
    format: z.string().optional(),
    version: z.number().int().optional(),
    resource_type: z.string().optional(),
    type: DeliveryTypeAll$inboundSchema.optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    uploaded_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    bytes: z.number().int().optional(),
    backup_bytes: z.number().int().optional(),
    width: z.nullable(z.number().int()).optional(),
    height: z.nullable(z.number().int()).optional(),
    aspect_ratio: z.nullable(z.number()).optional(),
    pixels: z.nullable(z.number().int()).optional(),
    tags: z.nullable(z.array(z.string())).optional(),
    context: z.nullable(ContextFullResponse$inboundSchema).optional(),
    metadata: z.record(z.any()).optional(),
    moderation_kind: z.string().optional(),
    moderation_status: z.string().optional(),
    moderation: z.array(
      z.lazy(() => ResourceInternalResponseModeration$inboundSchema),
    ).optional(),
    backup: z.boolean().optional(),
    url: z.string().optional(),
    secure_url: z.string().optional(),
    status: z.string().optional(),
    access_control: z.nullable(z.array(AccessControlItem$inboundSchema))
      .optional(),
    etag: z.string().optional(),
    animated: z.nullable(z.boolean()).optional(),
    duration: z.nullable(z.number()).optional(),
    resource_subtype: z.nullable(z.string()).optional(),
    substatus: z.nullable(z.string()).optional(),
    related_assets: z.nullable(
      z.array(z.lazy(() => ResourceInternalResponseRelatedAsset$inboundSchema)),
    ).optional(),
    last_updated: z.nullable(
      z.lazy(() => ResourceInternalResponseLastUpdated$inboundSchema),
    ).optional(),
    next_cursor: z.string().optional(),
    derived: z.array(
      z.lazy(() => ResourceInternalResponseDerived$inboundSchema),
    ).optional(),
    faces: z.nullable(z.array(z.array(z.number().int()))).optional(),
    coordinates: z.nullable(CoordinatesResponse$inboundSchema).optional(),
    illustration_score: z.number().optional(),
    semi_transparent: z.boolean().optional(),
    grayscale: z.boolean().optional(),
    colors: z.array(z.array(z.any())).optional(),
    predominant: z.record(z.array(z.array(z.any()))).optional(),
    versions: z.array(
      z.lazy(() => ResourceInternalResponseVersion$inboundSchema),
    ).optional(),
    info: z.lazy(() => ResourceInternalResponseInfo$inboundSchema).optional(),
    derivatives: z.nullable(
      z.array(z.lazy(() => ResourceInternalResponseDerivative$inboundSchema)),
    ).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "asset_id": "assetId",
    "public_id": "publicId",
    "asset_folder": "assetFolder",
    "display_name": "displayName",
    "resource_type": "resourceType",
    "created_at": "createdAt",
    "uploaded_at": "uploadedAt",
    "backup_bytes": "backupBytes",
    "aspect_ratio": "aspectRatio",
    "moderation_kind": "moderationKind",
    "moderation_status": "moderationStatus",
    "secure_url": "secureUrl",
    "access_control": "accessControl",
    "resource_subtype": "resourceSubtype",
    "related_assets": "relatedAssets",
    "last_updated": "lastUpdated",
    "next_cursor": "nextCursor",
    "illustration_score": "illustrationScore",
    "semi_transparent": "semiTransparent",
  });
});
/** @internal */
export type ResourceInternalResponse$Outbound = {
  asset_id?: string | undefined;
  public_id?: string | undefined;
  asset_folder?: string | undefined;
  display_name?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resource_type?: string | undefined;
  type?: DeliveryTypeAll$Outbound | undefined;
  created_at?: string | undefined;
  uploaded_at?: string | undefined;
  bytes?: number | undefined;
  backup_bytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspect_ratio?: number | null | undefined;
  pixels?: number | null | undefined;
  tags?: Array<string> | null | undefined;
  context?: ContextFullResponse$Outbound | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  moderation_kind?: string | undefined;
  moderation_status?: string | undefined;
  moderation?: Array<ResourceInternalResponseModeration$Outbound> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  status?: string | undefined;
  access_control?: Array<AccessControlItem$Outbound> | null | undefined;
  etag?: string | undefined;
  animated?: boolean | null | undefined;
  duration?: number | null | undefined;
  resource_subtype?: string | null | undefined;
  substatus?: string | null | undefined;
  related_assets?:
    | Array<ResourceInternalResponseRelatedAsset$Outbound>
    | null
    | undefined;
  last_updated?:
    | ResourceInternalResponseLastUpdated$Outbound
    | null
    | undefined;
  next_cursor?: string | undefined;
  derived?: Array<ResourceInternalResponseDerived$Outbound> | undefined;
  faces?: Array<Array<number>> | null | undefined;
  coordinates?: CoordinatesResponse$Outbound | null | undefined;
  illustration_score?: number | undefined;
  semi_transparent?: boolean | undefined;
  grayscale?: boolean | undefined;
  colors?: Array<Array<any>> | undefined;
  predominant?: { [k: string]: Array<Array<any>> } | undefined;
  versions?: Array<ResourceInternalResponseVersion$Outbound> | undefined;
  info?: ResourceInternalResponseInfo$Outbound | undefined;
  derivatives?:
    | Array<ResourceInternalResponseDerivative$Outbound>
    | null
    | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ResourceInternalResponse$outboundSchema: z.ZodType<
  ResourceInternalResponse$Outbound,
  z.ZodTypeDef,
  ResourceInternalResponse
> = z.object({
  assetId: z.string().optional(),
  publicId: z.string().optional(),
  assetFolder: z.string().optional(),
  displayName: z.string().optional(),
  folder: z.string().optional(),
  filename: z.string().optional(),
  format: z.string().optional(),
  version: z.number().int().optional(),
  resourceType: z.string().optional(),
  type: DeliveryTypeAll$outboundSchema.optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  uploadedAt: z.date().transform(v => v.toISOString()).optional(),
  bytes: z.number().int().optional(),
  backupBytes: z.number().int().optional(),
  width: z.nullable(z.number().int()).optional(),
  height: z.nullable(z.number().int()).optional(),
  aspectRatio: z.nullable(z.number()).optional(),
  pixels: z.nullable(z.number().int()).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  context: z.nullable(ContextFullResponse$outboundSchema).optional(),
  metadata: z.record(z.any()).optional(),
  moderationKind: z.string().optional(),
  moderationStatus: z.string().optional(),
  moderation: z.array(
    z.lazy(() => ResourceInternalResponseModeration$outboundSchema),
  ).optional(),
  backup: z.boolean().optional(),
  url: z.string().optional(),
  secureUrl: z.string().optional(),
  status: z.string().optional(),
  accessControl: z.nullable(z.array(AccessControlItem$outboundSchema))
    .optional(),
  etag: z.string().optional(),
  animated: z.nullable(z.boolean()).optional(),
  duration: z.nullable(z.number()).optional(),
  resourceSubtype: z.nullable(z.string()).optional(),
  substatus: z.nullable(z.string()).optional(),
  relatedAssets: z.nullable(
    z.array(z.lazy(() => ResourceInternalResponseRelatedAsset$outboundSchema)),
  ).optional(),
  lastUpdated: z.nullable(
    z.lazy(() => ResourceInternalResponseLastUpdated$outboundSchema),
  ).optional(),
  nextCursor: z.string().optional(),
  derived: z.array(z.lazy(() => ResourceInternalResponseDerived$outboundSchema))
    .optional(),
  faces: z.nullable(z.array(z.array(z.number().int()))).optional(),
  coordinates: z.nullable(CoordinatesResponse$outboundSchema).optional(),
  illustrationScore: z.number().optional(),
  semiTransparent: z.boolean().optional(),
  grayscale: z.boolean().optional(),
  colors: z.array(z.array(z.any())).optional(),
  predominant: z.record(z.array(z.array(z.any()))).optional(),
  versions: z.array(
    z.lazy(() => ResourceInternalResponseVersion$outboundSchema),
  ).optional(),
  info: z.lazy(() => ResourceInternalResponseInfo$outboundSchema).optional(),
  derivatives: z.nullable(
    z.array(z.lazy(() => ResourceInternalResponseDerivative$outboundSchema)),
  ).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      assetId: "asset_id",
      publicId: "public_id",
      assetFolder: "asset_folder",
      displayName: "display_name",
      resourceType: "resource_type",
      createdAt: "created_at",
      uploadedAt: "uploaded_at",
      backupBytes: "backup_bytes",
      aspectRatio: "aspect_ratio",
      moderationKind: "moderation_kind",
      moderationStatus: "moderation_status",
      secureUrl: "secure_url",
      accessControl: "access_control",
      resourceSubtype: "resource_subtype",
      relatedAssets: "related_assets",
      lastUpdated: "last_updated",
      nextCursor: "next_cursor",
      illustrationScore: "illustration_score",
      semiTransparent: "semi_transparent",
      additionalProperties: null,
    }),
  };
});

export function resourceInternalResponseToJSON(
  resourceInternalResponse: ResourceInternalResponse,
): string {
  return JSON.stringify(
    ResourceInternalResponse$outboundSchema.parse(resourceInternalResponse),
  );
}
export function resourceInternalResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourceInternalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceInternalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceInternalResponse' from JSON`,
  );
}
