/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DirectionEnum,
  DirectionEnum$inboundSchema,
  DirectionEnum$outboundSchema,
} from "./directionenum.js";

export const Type = {
  Bytes: "bytes",
  ImagePixels: "image_pixels",
  VideoPixels: "video_pixels",
  Duration: "duration",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type SearchParametersRange = {
  /**
   * A label for the bucket, returned in the aggregation response. 1–20 chars, alphanumeric plus `-` and `_`.
   */
  key: string;
  /**
   * Start of the range (inclusive). At least one of `from` / `to` is required.
   */
  from?: number | undefined;
  /**
   * End of the range (exclusive). At least one of `from` / `to` is required.
   */
  to?: number | undefined;
};

export type Aggregate = {
  type: Type;
  /**
   * One or more ranges for the numeric field. Each range must include a `key` label and at least one of `from` / `to`.
   *
   * @remarks
   */
  ranges: Array<SearchParametersRange>;
};

export const AggregateEnum = {
  Format: "format",
  ResourceType: "resource_type",
  Type: "type",
} as const;
export type AggregateEnum = ClosedEnum<typeof AggregateEnum>;

/**
 * Fields or ranges to aggregate search results by. Requires a Tier 2 search plan; on Tier 1 the field is accepted but aggregations are omitted from the response.
 *
 * @remarks
 */
export type AggregateUnion = Array<AggregateEnum> | Array<Aggregate>;

export const WithField = {
  Context: "context",
  Tags: "tags",
  ImageMetadata: "image_metadata",
  ImageAnalysis: "image_analysis",
  Metadata: "metadata",
  QualityAnalysis: "quality_analysis",
  AccessibilityAnalysis: "accessibility_analysis",
} as const;
export type WithField = ClosedEnum<typeof WithField>;

/**
 * Common parameters for resource search operations.
 */
export type SearchParameters = {
  /**
   * The Lucene-like search expression. Supports token match (`field:value`), exact match (`field=value`), trailing `*` for prefix match, ranges (`[a TO b]`, `{a TO b}`), and comparisons (`>`, `<`, `>=`, `<=`). Combine terms with uppercase `AND`, `OR`, `NOT`, or `+`/`-`, and group with parentheses. Wrap values containing reserved characters (spaces, colons, etc.) in double quotes. See the [search expressions guide](https://cloudinary.com/documentation/search_expressions.md) for the full syntax and supported fields.
   *
   * @remarks
   */
  expression?: string | undefined;
  /**
   * An array of single-key objects mapping a field to a sort direction. Each object must contain exactly one field name mapped to 'asc' or 'desc'.
   *
   * @remarks
   * Default: [{"created_at": "desc"}].
   */
  sortBy?: Array<{ [k: string]: DirectionEnum }> | undefined;
  /**
   * The maximum number of results to return. Default - 50. Maximum - 500.
   *
   * @remarks
   * Set to `0` to get only `total_count` and `aggregations` without any resources in the response — useful for counting or aggregation-only queries.
   */
  maxResults?: number | undefined;
  /**
   * The cursor value to get the next page of results. Available when a previous search returned more results than max_results.
   */
  nextCursor?: string | undefined;
  /**
   * Fields or ranges to aggregate search results by. Requires a Tier 2 search plan; on Tier 1 the field is accepted but aggregations are omitted from the response.
   *
   * @remarks
   */
  aggregate?: Array<AggregateEnum> | Array<Aggregate> | undefined;
  /**
   * The additional asset attributes to include in each search result. The `fields` parameter takes precedence over this parameter. `image_metadata`, `image_analysis`, and `metadata` require a Tier 2 search plan.
   *
   * @remarks
   */
  withField?: Array<WithField> | undefined;
  /**
   * A comma-separated list of fields to include in the response.
   *
   * @remarks
   * Notes:
   * - This parameter takes precedence over the with_field parameter, so if you want any additional asset attributes returned, make sure to also include them in this list (e.g., tags or context).
   * - The following fields are always included in the response: public_id, asset_id, asset_folder, created_at, status, type, and resource_type.
   */
  fields?: string | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);
/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/** @internal */
export const SearchParametersRange$inboundSchema: z.ZodType<
  SearchParametersRange,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  from: z.number().optional(),
  to: z.number().optional(),
});
/** @internal */
export type SearchParametersRange$Outbound = {
  key: string;
  from?: number | undefined;
  to?: number | undefined;
};

/** @internal */
export const SearchParametersRange$outboundSchema: z.ZodType<
  SearchParametersRange$Outbound,
  z.ZodTypeDef,
  SearchParametersRange
> = z.object({
  key: z.string(),
  from: z.number().optional(),
  to: z.number().optional(),
});

export function searchParametersRangeToJSON(
  searchParametersRange: SearchParametersRange,
): string {
  return JSON.stringify(
    SearchParametersRange$outboundSchema.parse(searchParametersRange),
  );
}
export function searchParametersRangeFromJSON(
  jsonString: string,
): SafeParseResult<SearchParametersRange, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchParametersRange$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchParametersRange' from JSON`,
  );
}

/** @internal */
export const Aggregate$inboundSchema: z.ZodType<
  Aggregate,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: Type$inboundSchema,
  ranges: z.array(z.lazy(() => SearchParametersRange$inboundSchema)),
});
/** @internal */
export type Aggregate$Outbound = {
  type: string;
  ranges: Array<SearchParametersRange$Outbound>;
};

/** @internal */
export const Aggregate$outboundSchema: z.ZodType<
  Aggregate$Outbound,
  z.ZodTypeDef,
  Aggregate
> = z.object({
  type: Type$outboundSchema,
  ranges: z.array(z.lazy(() => SearchParametersRange$outboundSchema)),
});

export function aggregateToJSON(aggregate: Aggregate): string {
  return JSON.stringify(Aggregate$outboundSchema.parse(aggregate));
}
export function aggregateFromJSON(
  jsonString: string,
): SafeParseResult<Aggregate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Aggregate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Aggregate' from JSON`,
  );
}

/** @internal */
export const AggregateEnum$inboundSchema: z.ZodNativeEnum<
  typeof AggregateEnum
> = z.nativeEnum(AggregateEnum);
/** @internal */
export const AggregateEnum$outboundSchema: z.ZodNativeEnum<
  typeof AggregateEnum
> = AggregateEnum$inboundSchema;

/** @internal */
export const AggregateUnion$inboundSchema: z.ZodType<
  AggregateUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(AggregateEnum$inboundSchema),
  z.array(z.lazy(() => Aggregate$inboundSchema)),
]);
/** @internal */
export type AggregateUnion$Outbound = Array<string> | Array<Aggregate$Outbound>;

/** @internal */
export const AggregateUnion$outboundSchema: z.ZodType<
  AggregateUnion$Outbound,
  z.ZodTypeDef,
  AggregateUnion
> = z.union([
  z.array(AggregateEnum$outboundSchema),
  z.array(z.lazy(() => Aggregate$outboundSchema)),
]);

export function aggregateUnionToJSON(aggregateUnion: AggregateUnion): string {
  return JSON.stringify(AggregateUnion$outboundSchema.parse(aggregateUnion));
}
export function aggregateUnionFromJSON(
  jsonString: string,
): SafeParseResult<AggregateUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregateUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregateUnion' from JSON`,
  );
}

/** @internal */
export const WithField$inboundSchema: z.ZodNativeEnum<typeof WithField> = z
  .nativeEnum(WithField);
/** @internal */
export const WithField$outboundSchema: z.ZodNativeEnum<typeof WithField> =
  WithField$inboundSchema;

/** @internal */
export const SearchParameters$inboundSchema: z.ZodType<
  SearchParameters,
  z.ZodTypeDef,
  unknown
> = z.object({
  expression: z.string().optional(),
  sort_by: z.array(z.record(DirectionEnum$inboundSchema)).optional(),
  max_results: z.number().int().optional(),
  next_cursor: z.string().optional(),
  aggregate: z.union([
    z.array(AggregateEnum$inboundSchema),
    z.array(z.lazy(() => Aggregate$inboundSchema)),
  ]).optional(),
  with_field: z.array(WithField$inboundSchema).optional(),
  fields: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "sort_by": "sortBy",
    "max_results": "maxResults",
    "next_cursor": "nextCursor",
    "with_field": "withField",
  });
});
/** @internal */
export type SearchParameters$Outbound = {
  expression?: string | undefined;
  sort_by?: Array<{ [k: string]: string }> | undefined;
  max_results?: number | undefined;
  next_cursor?: string | undefined;
  aggregate?: Array<string> | Array<Aggregate$Outbound> | undefined;
  with_field?: Array<string> | undefined;
  fields?: string | undefined;
};

/** @internal */
export const SearchParameters$outboundSchema: z.ZodType<
  SearchParameters$Outbound,
  z.ZodTypeDef,
  SearchParameters
> = z.object({
  expression: z.string().optional(),
  sortBy: z.array(z.record(DirectionEnum$outboundSchema)).optional(),
  maxResults: z.number().int().optional(),
  nextCursor: z.string().optional(),
  aggregate: z.union([
    z.array(AggregateEnum$outboundSchema),
    z.array(z.lazy(() => Aggregate$outboundSchema)),
  ]).optional(),
  withField: z.array(WithField$outboundSchema).optional(),
  fields: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sortBy: "sort_by",
    maxResults: "max_results",
    nextCursor: "next_cursor",
    withField: "with_field",
  });
});

export function searchParametersToJSON(
  searchParameters: SearchParameters,
): string {
  return JSON.stringify(
    SearchParameters$outboundSchema.parse(searchParameters),
  );
}
export function searchParametersFromJSON(
  jsonString: string,
): SafeParseResult<SearchParameters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchParameters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchParameters' from JSON`,
  );
}
