/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$inboundSchema,
  SchemeCloudinaryAuth$Outbound,
  SchemeCloudinaryAuth$outboundSchema,
} from "./schemecloudinaryauth.js";

export type Security = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const Security$inboundSchema: z.ZodType<
  Security,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$inboundSchema.optional(),
  oauth2: z.string().optional(),
});
/** @internal */
export type Security$Outbound = {
  cloudinaryAuth?: SchemeCloudinaryAuth$Outbound | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$outboundSchema.optional(),
  oauth2: z.string().optional(),
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
export function securityFromJSON(
  jsonString: string,
): SafeParseResult<Security, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Security$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Security' from JSON`,
  );
}
