/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The storage type of the resource.
 */
export const StorageTypeParameter = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
} as const;
/**
 * The storage type of the resource.
 */
export type StorageTypeParameter = ClosedEnum<typeof StorageTypeParameter>;

/** @internal */
export const StorageTypeParameter$inboundSchema: z.ZodNativeEnum<
  typeof StorageTypeParameter
> = z.nativeEnum(StorageTypeParameter);

/** @internal */
export const StorageTypeParameter$outboundSchema: z.ZodNativeEnum<
  typeof StorageTypeParameter
> = StorageTypeParameter$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StorageTypeParameter$ {
  /** @deprecated use `StorageTypeParameter$inboundSchema` instead. */
  export const inboundSchema = StorageTypeParameter$inboundSchema;
  /** @deprecated use `StorageTypeParameter$outboundSchema` instead. */
  export const outboundSchema = StorageTypeParameter$outboundSchema;
}
