/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DeliveryTypeAll,
  DeliveryTypeAll$inboundSchema,
  DeliveryTypeAll$Outbound,
  DeliveryTypeAll$outboundSchema,
} from "./deliverytypeall.js";

/**
 * The tag operation to apply.
 *
 * @remarks
 *
 * - `add` adds the given tags, leaving existing tags untouched.
 * - `remove` removes the given tags, leaving other tags untouched.
 * - `replace` overwrites the full tag list with the given tags.
 * - `remove_all` clears every tag. The `tags` field is ignored.
 */
export const TagsUpdateRequestCommand = {
  Add: "add",
  Remove: "remove",
  Replace: "replace",
  RemoveAll: "remove_all",
} as const;
/**
 * The tag operation to apply.
 *
 * @remarks
 *
 * - `add` adds the given tags, leaving existing tags untouched.
 * - `remove` removes the given tags, leaving other tags untouched.
 * - `replace` overwrites the full tag list with the given tags.
 * - `remove_all` clears every tag. The `tags` field is ignored.
 */
export type TagsUpdateRequestCommand = ClosedEnum<
  typeof TagsUpdateRequestCommand
>;

/**
 * A tag command plus the assets it applies to.
 */
export type TagsUpdateRequest = {
  /**
   * The public IDs of the assets to apply the operation to. At most 1000 are processed per request; any beyond the first 1000 are ignored rather than rejected. Public IDs that do not exist, or that the caller lacks update permission for, are skipped rather than failing the request, so the returned `public_ids` may be shorter than the requested list.
   */
  publicIds: Array<string>;
  /**
   * The delivery type of the assets to operate on. Defaults to `upload`.
   */
  type?: DeliveryTypeAll | undefined;
  /**
   * The tag operation to apply.
   *
   * @remarks
   *
   * - `add` adds the given tags, leaving existing tags untouched.
   * - `remove` removes the given tags, leaving other tags untouched.
   * - `replace` overwrites the full tag list with the given tags.
   * - `remove_all` clears every tag. The `tags` field is ignored.
   */
  command: TagsUpdateRequestCommand;
  /**
   * The tag names to apply. Required for `add`, `remove`, and `replace`; ignored for `remove_all`. A tag name must not contain a comma.
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export const TagsUpdateRequestCommand$inboundSchema: z.ZodNativeEnum<
  typeof TagsUpdateRequestCommand
> = z.nativeEnum(TagsUpdateRequestCommand);
/** @internal */
export const TagsUpdateRequestCommand$outboundSchema: z.ZodNativeEnum<
  typeof TagsUpdateRequestCommand
> = TagsUpdateRequestCommand$inboundSchema;

/** @internal */
export const TagsUpdateRequest$inboundSchema: z.ZodType<
  TagsUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  public_ids: z.array(z.string()),
  type: DeliveryTypeAll$inboundSchema.optional(),
  command: TagsUpdateRequestCommand$inboundSchema,
  tags: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "public_ids": "publicIds",
  });
});
/** @internal */
export type TagsUpdateRequest$Outbound = {
  public_ids: Array<string>;
  type?: DeliveryTypeAll$Outbound | undefined;
  command: string;
  tags?: Array<string> | undefined;
};

/** @internal */
export const TagsUpdateRequest$outboundSchema: z.ZodType<
  TagsUpdateRequest$Outbound,
  z.ZodTypeDef,
  TagsUpdateRequest
> = z.object({
  publicIds: z.array(z.string()),
  type: DeliveryTypeAll$outboundSchema.optional(),
  command: TagsUpdateRequestCommand$outboundSchema,
  tags: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    publicIds: "public_ids",
  });
});

export function tagsUpdateRequestToJSON(
  tagsUpdateRequest: TagsUpdateRequest,
): string {
  return JSON.stringify(
    TagsUpdateRequest$outboundSchema.parse(tagsUpdateRequest),
  );
}
export function tagsUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<TagsUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TagsUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TagsUpdateRequest' from JSON`,
  );
}
