/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ManagedAssetTarget,
  ManagedAssetTarget$inboundSchema,
  ManagedAssetTarget$Outbound,
  ManagedAssetTarget$outboundSchema,
} from "./managedassettarget.js";
import {
  TemporaryTarget,
  TemporaryTarget$inboundSchema,
  TemporaryTarget$Outbound,
  TemporaryTarget$outboundSchema,
} from "./temporarytarget.js";

/**
 * Where to store the generated output, determined by `target_type`.
 *
 * @remarks
 * Optional; defaults to a `managed_asset` target when omitted.
 */
export type Target = ManagedAssetTarget | TemporaryTarget;

/** @internal */
export const Target$inboundSchema: z.ZodType<Target, z.ZodTypeDef, unknown> = z
  .union([ManagedAssetTarget$inboundSchema, TemporaryTarget$inboundSchema]);
/** @internal */
export type Target$Outbound =
  | ManagedAssetTarget$Outbound
  | TemporaryTarget$Outbound;

/** @internal */
export const Target$outboundSchema: z.ZodType<
  Target$Outbound,
  z.ZodTypeDef,
  Target
> = z.union([
  ManagedAssetTarget$outboundSchema,
  TemporaryTarget$outboundSchema,
]);

export function targetToJSON(target: Target): string {
  return JSON.stringify(Target$outboundSchema.parse(target));
}
export function targetFromJSON(
  jsonString: string,
): SafeParseResult<Target, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Target$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Target' from JSON`,
  );
}
