/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Task,
  Task$inboundSchema,
  Task$Outbound,
  Task$outboundSchema,
} from "./task.js";

/**
 * Envelope for an async generation task — returned by the accepted (202)
 *
 * @remarks
 * response and by GET /tasks/{task_id}.
 */
export type TaskResponse = {
  /**
   * An async generation task. Returned when a generation is accepted (202)
   *
   * @remarks
   * and from GET /tasks/{task_id} as it progresses. The `result` is filled
   * in once `status` is `completed`.
   */
  data?: Task | undefined;
  /**
   * Unique identifier for this request, for correlation and support.
   */
  requestId: string;
};

/** @internal */
export const TaskResponse$inboundSchema: z.ZodType<
  TaskResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: Task$inboundSchema.optional(),
  request_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type TaskResponse$Outbound = {
  data?: Task$Outbound | undefined;
  request_id: string;
};

/** @internal */
export const TaskResponse$outboundSchema: z.ZodType<
  TaskResponse$Outbound,
  z.ZodTypeDef,
  TaskResponse
> = z.object({
  data: Task$outboundSchema.optional(),
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function taskResponseToJSON(taskResponse: TaskResponse): string {
  return JSON.stringify(TaskResponse$outboundSchema.parse(taskResponse));
}
export function taskResponseFromJSON(
  jsonString: string,
): SafeParseResult<TaskResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskResponse' from JSON`,
  );
}
