/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The status of an async generation task.
 *
 * @remarks
 * * `pending`: accepted and queued, not yet started.
 * * `processing`: generation is in progress.
 * * `completed`: generation finished; `result` is populated.
 * * `failed`: generation did not complete successfully.
 */
export const TaskStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * The status of an async generation task.
 *
 * @remarks
 * * `pending`: accepted and queued, not yet started.
 * * `processing`: generation is in progress.
 * * `completed`: generation finished; `result` is populated.
 * * `failed`: generation did not complete successfully.
 */
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

/** @internal */
export const TaskStatus$inboundSchema: z.ZodNativeEnum<typeof TaskStatus> = z
  .nativeEnum(TaskStatus);
/** @internal */
export const TaskStatus$outboundSchema: z.ZodNativeEnum<typeof TaskStatus> =
  TaskStatus$inboundSchema;
