/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Store the output as a short-lived asset on the upload service.
 */
export type TemporaryTarget = {
  /**
   * Discriminator identifying this as a temporary target.
   */
  targetType: "temporary";
};

/** @internal */
export const TemporaryTarget$inboundSchema: z.ZodType<
  TemporaryTarget,
  z.ZodTypeDef,
  unknown
> = z.object({
  target_type: z.literal("temporary"),
}).transform((v) => {
  return remap$(v, {
    "target_type": "targetType",
  });
});
/** @internal */
export type TemporaryTarget$Outbound = {
  target_type: "temporary";
};

/** @internal */
export const TemporaryTarget$outboundSchema: z.ZodType<
  TemporaryTarget$Outbound,
  z.ZodTypeDef,
  TemporaryTarget
> = z.object({
  targetType: z.literal("temporary"),
}).transform((v) => {
  return remap$(v, {
    targetType: "target_type",
  });
});

export function temporaryTargetToJSON(
  temporaryTarget: TemporaryTarget,
): string {
  return JSON.stringify(TemporaryTarget$outboundSchema.parse(temporaryTarget));
}
export function temporaryTargetFromJSON(
  jsonString: string,
): SafeParseResult<TemporaryTarget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TemporaryTarget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TemporaryTarget' from JSON`,
  );
}
