/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Text alignment.
 */
export const TextAlign = {
  Left: "left",
  Center: "center",
  Right: "right",
  Justify: "justify",
} as const;
/**
 * Text alignment.
 */
export type TextAlign = ClosedEnum<typeof TextAlign>;

/**
 * Whether to use a normal or bold font.
 */
export const FontWeight = {
  Normal: "normal",
  Bold: "bold",
} as const;
/**
 * Whether to use a normal or bold font.
 */
export type FontWeight = ClosedEnum<typeof FontWeight>;

/**
 * Whether to use a normal or italic font.
 */
export const FontStyle = {
  Normal: "normal",
  Italic: "italic",
} as const;
/**
 * Whether to use a normal or italic font.
 */
export type FontStyle = ClosedEnum<typeof FontStyle>;

/**
 * Text decoration style.
 */
export const TextDecoration = {
  None: "none",
  Underline: "underline",
} as const;
/**
 * Text decoration style.
 */
export type TextDecoration = ClosedEnum<typeof TextDecoration>;

export type TextRequest = {
  /**
   * The text string to generate an image for.
   */
  text: string;
  /**
   * The identifier that is used for accessing the generated image. If not specified, a unique identifier is generated.
   */
  publicId?: string | undefined;
  /**
   * The name of the font family.
   */
  fontFamily?: string | undefined;
  /**
   * Font size in points.
   */
  fontSize?: number | undefined;
  /**
   * Name or RGB representation of the font's color (e.g., red or
   */
  fontColor?: string | undefined;
  /**
   * Text alignment.
   */
  textAlign?: TextAlign | undefined;
  /**
   * Whether to use a normal or bold font.
   */
  fontWeight?: FontWeight | undefined;
  /**
   * Whether to use a normal or italic font.
   */
  fontStyle?: FontStyle | undefined;
  /**
   * Name or RGB representation of the background color (e.g., red or
   */
  background?: string | undefined;
  /**
   * Text opacity value between 0 (invisible) and 100.
   */
  opacity?: number | undefined;
  /**
   * Text decoration style.
   */
  textDecoration?: TextDecoration | undefined;
  /**
   * The spacing between lines of text in pixels.
   */
  lineSpacing?: number | undefined;
};

/** @internal */
export const TextAlign$inboundSchema: z.ZodNativeEnum<typeof TextAlign> = z
  .nativeEnum(TextAlign);
/** @internal */
export const TextAlign$outboundSchema: z.ZodNativeEnum<typeof TextAlign> =
  TextAlign$inboundSchema;

/** @internal */
export const FontWeight$inboundSchema: z.ZodNativeEnum<typeof FontWeight> = z
  .nativeEnum(FontWeight);
/** @internal */
export const FontWeight$outboundSchema: z.ZodNativeEnum<typeof FontWeight> =
  FontWeight$inboundSchema;

/** @internal */
export const FontStyle$inboundSchema: z.ZodNativeEnum<typeof FontStyle> = z
  .nativeEnum(FontStyle);
/** @internal */
export const FontStyle$outboundSchema: z.ZodNativeEnum<typeof FontStyle> =
  FontStyle$inboundSchema;

/** @internal */
export const TextDecoration$inboundSchema: z.ZodNativeEnum<
  typeof TextDecoration
> = z.nativeEnum(TextDecoration);
/** @internal */
export const TextDecoration$outboundSchema: z.ZodNativeEnum<
  typeof TextDecoration
> = TextDecoration$inboundSchema;

/** @internal */
export const TextRequest$inboundSchema: z.ZodType<
  TextRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  public_id: z.string().optional(),
  font_family: z.string().optional(),
  font_size: z.number().int().default(12),
  font_color: z.string().default("black"),
  text_align: TextAlign$inboundSchema.optional(),
  font_weight: FontWeight$inboundSchema.default("normal"),
  font_style: FontStyle$inboundSchema.default("normal"),
  background: z.string().default("transparent"),
  opacity: z.number().int().default(100),
  text_decoration: TextDecoration$inboundSchema.default("none"),
  line_spacing: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "public_id": "publicId",
    "font_family": "fontFamily",
    "font_size": "fontSize",
    "font_color": "fontColor",
    "text_align": "textAlign",
    "font_weight": "fontWeight",
    "font_style": "fontStyle",
    "text_decoration": "textDecoration",
    "line_spacing": "lineSpacing",
  });
});
/** @internal */
export type TextRequest$Outbound = {
  text: string;
  public_id?: string | undefined;
  font_family?: string | undefined;
  font_size: number;
  font_color: string;
  text_align?: string | undefined;
  font_weight: string;
  font_style: string;
  background: string;
  opacity: number;
  text_decoration: string;
  line_spacing?: number | undefined;
};

/** @internal */
export const TextRequest$outboundSchema: z.ZodType<
  TextRequest$Outbound,
  z.ZodTypeDef,
  TextRequest
> = z.object({
  text: z.string(),
  publicId: z.string().optional(),
  fontFamily: z.string().optional(),
  fontSize: z.number().int().default(12),
  fontColor: z.string().default("black"),
  textAlign: TextAlign$outboundSchema.optional(),
  fontWeight: FontWeight$outboundSchema.default("normal"),
  fontStyle: FontStyle$outboundSchema.default("normal"),
  background: z.string().default("transparent"),
  opacity: z.number().int().default(100),
  textDecoration: TextDecoration$outboundSchema.default("none"),
  lineSpacing: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    publicId: "public_id",
    fontFamily: "font_family",
    fontSize: "font_size",
    fontColor: "font_color",
    textAlign: "text_align",
    fontWeight: "font_weight",
    fontStyle: "font_style",
    textDecoration: "text_decoration",
    lineSpacing: "line_spacing",
  });
});

export function textRequestToJSON(textRequest: TextRequest): string {
  return JSON.stringify(TextRequest$outboundSchema.parse(textRequest));
}
export function textRequestFromJSON(
  jsonString: string,
): SafeParseResult<TextRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextRequest' from JSON`,
  );
}
