/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ContextFullResponse,
  ContextFullResponse$inboundSchema,
  ContextFullResponse$Outbound,
  ContextFullResponse$outboundSchema,
} from "./contextfullresponse.js";
import {
  CoordinatesResponse,
  CoordinatesResponse$inboundSchema,
  CoordinatesResponse$Outbound,
  CoordinatesResponse$outboundSchema,
} from "./coordinatesresponse.js";

/**
 * The image metadata of the uploaded file.
 */
export type UploadResponseImageMetadata = {};

export type Eager = {
  transformation?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  bytes?: number | undefined;
  format?: string | undefined;
  url?: string | undefined;
  secureUrl?: string | undefined;
};

export type UploadResponse = {
  /**
   * The URL of the uploaded file.
   */
  url?: string | undefined;
  /**
   * The secure URL of the uploaded file.
   */
  secureUrl?: string | undefined;
  /**
   * The public ID of the uploaded file.
   */
  publicId?: string | undefined;
  /**
   * The version of the uploaded file.
   */
  version?: number | undefined;
  /**
   * Hexadecimal version ID; length is a positive multiple of 32 (typically 32 or 64).
   */
  versionId?: string | undefined;
  /**
   * The signature of the uploaded file.
   */
  signature?: string | undefined;
  /**
   * The width of the uploaded file.
   */
  width?: number | undefined;
  /**
   * The height of the uploaded file.
   */
  height?: number | undefined;
  /**
   * A 32-character hexadecimal asset ID.
   */
  assetId?: string | undefined;
  /**
   * The format of the uploaded file.
   */
  format?: string | undefined;
  /**
   * The type of resource that was uploaded.
   */
  resourceType?: string | undefined;
  /**
   * The date and time the file was uploaded.
   */
  createdAt?: Date | undefined;
  /**
   * Tag names assigned to the asset.
   */
  tags?: Array<string> | null | undefined;
  /**
   * Contextual metadata grouped by kind. Custom user context appears under the 'custom' key. Other context kinds may also appear as additional keys.
   */
  context?: ContextFullResponse | null | undefined;
  /**
   * Structured metadata associated with the uploaded file.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * The number of pages in the uploaded file.
   */
  pages?: number | undefined;
  /**
   * The size of the uploaded file in bytes.
   */
  bytes?: number | undefined;
  /**
   * The type of the uploaded file.
   */
  type?: string | undefined;
  /**
   * The ETag of the uploaded file.
   */
  etag?: string | undefined;
  /**
   * Whether the uploaded file is a placeholder.
   */
  placeholder?: boolean | undefined;
  /**
   * The original filename of the uploaded file.
   */
  originalFilename?: string | undefined;
  /**
   * The image metadata of the uploaded file.
   */
  imageMetadata?: UploadResponseImageMetadata | undefined;
  /**
   * The illustration score of the uploaded file.
   */
  illustrationScore?: number | undefined;
  /**
   * Whether the uploaded file is semi-transparent.
   */
  semiTransparent?: boolean | undefined;
  /**
   * Whether the uploaded file is grayscale.
   */
  grayscale?: boolean | undefined;
  /**
   * Detected face coordinate rectangles [x, y, width, height].
   */
  faces?: Array<Array<number>> | null | undefined;
  /**
   * Coordinate data for faces and custom regions.
   */
  coordinates?: CoordinatesResponse | null | undefined;
  eager?: Array<Eager> | undefined;
  /**
   * The asset folder where the file is stored.
   */
  assetFolder?: string | null | undefined;
  /**
   * The display name of the uploaded file.
   */
  displayName?: string | undefined;
  /**
   * The API key used to upload the file.
   */
  apiKey?: string | undefined;
};

/** @internal */
export const UploadResponseImageMetadata$inboundSchema: z.ZodType<
  UploadResponseImageMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type UploadResponseImageMetadata$Outbound = {};

/** @internal */
export const UploadResponseImageMetadata$outboundSchema: z.ZodType<
  UploadResponseImageMetadata$Outbound,
  z.ZodTypeDef,
  UploadResponseImageMetadata
> = z.object({});

export function uploadResponseImageMetadataToJSON(
  uploadResponseImageMetadata: UploadResponseImageMetadata,
): string {
  return JSON.stringify(
    UploadResponseImageMetadata$outboundSchema.parse(
      uploadResponseImageMetadata,
    ),
  );
}
export function uploadResponseImageMetadataFromJSON(
  jsonString: string,
): SafeParseResult<UploadResponseImageMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadResponseImageMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadResponseImageMetadata' from JSON`,
  );
}

/** @internal */
export const Eager$inboundSchema: z.ZodType<Eager, z.ZodTypeDef, unknown> = z
  .object({
    transformation: z.string().optional(),
    width: z.number().int().optional(),
    height: z.number().int().optional(),
    bytes: z.number().int().optional(),
    format: z.string().optional(),
    url: z.string().optional(),
    secure_url: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "secure_url": "secureUrl",
    });
  });
/** @internal */
export type Eager$Outbound = {
  transformation?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  bytes?: number | undefined;
  format?: string | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
};

/** @internal */
export const Eager$outboundSchema: z.ZodType<
  Eager$Outbound,
  z.ZodTypeDef,
  Eager
> = z.object({
  transformation: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  bytes: z.number().int().optional(),
  format: z.string().optional(),
  url: z.string().optional(),
  secureUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    secureUrl: "secure_url",
  });
});

export function eagerToJSON(eager: Eager): string {
  return JSON.stringify(Eager$outboundSchema.parse(eager));
}
export function eagerFromJSON(
  jsonString: string,
): SafeParseResult<Eager, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Eager$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Eager' from JSON`,
  );
}

/** @internal */
export const UploadResponse$inboundSchema: z.ZodType<
  UploadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
  secure_url: z.string().optional(),
  public_id: z.string().optional(),
  version: z.number().int().optional(),
  version_id: z.string().optional(),
  signature: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  asset_id: z.string().optional(),
  format: z.string().optional(),
  resource_type: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  context: z.nullable(ContextFullResponse$inboundSchema).optional(),
  metadata: z.record(z.any()).optional(),
  pages: z.number().int().optional(),
  bytes: z.number().int().optional(),
  type: z.string().optional(),
  etag: z.string().optional(),
  placeholder: z.boolean().optional(),
  original_filename: z.string().optional(),
  image_metadata: z.lazy(() => UploadResponseImageMetadata$inboundSchema)
    .optional(),
  illustration_score: z.number().optional(),
  semi_transparent: z.boolean().optional(),
  grayscale: z.boolean().optional(),
  faces: z.nullable(z.array(z.array(z.number().int()))).optional(),
  coordinates: z.nullable(CoordinatesResponse$inboundSchema).optional(),
  eager: z.array(z.lazy(() => Eager$inboundSchema)).optional(),
  asset_folder: z.nullable(z.string()).optional(),
  display_name: z.string().optional(),
  api_key: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "secure_url": "secureUrl",
    "public_id": "publicId",
    "version_id": "versionId",
    "asset_id": "assetId",
    "resource_type": "resourceType",
    "created_at": "createdAt",
    "original_filename": "originalFilename",
    "image_metadata": "imageMetadata",
    "illustration_score": "illustrationScore",
    "semi_transparent": "semiTransparent",
    "asset_folder": "assetFolder",
    "display_name": "displayName",
    "api_key": "apiKey",
  });
});
/** @internal */
export type UploadResponse$Outbound = {
  url?: string | undefined;
  secure_url?: string | undefined;
  public_id?: string | undefined;
  version?: number | undefined;
  version_id?: string | undefined;
  signature?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  asset_id?: string | undefined;
  format?: string | undefined;
  resource_type?: string | undefined;
  created_at?: string | undefined;
  tags?: Array<string> | null | undefined;
  context?: ContextFullResponse$Outbound | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  pages?: number | undefined;
  bytes?: number | undefined;
  type?: string | undefined;
  etag?: string | undefined;
  placeholder?: boolean | undefined;
  original_filename?: string | undefined;
  image_metadata?: UploadResponseImageMetadata$Outbound | undefined;
  illustration_score?: number | undefined;
  semi_transparent?: boolean | undefined;
  grayscale?: boolean | undefined;
  faces?: Array<Array<number>> | null | undefined;
  coordinates?: CoordinatesResponse$Outbound | null | undefined;
  eager?: Array<Eager$Outbound> | undefined;
  asset_folder?: string | null | undefined;
  display_name?: string | undefined;
  api_key?: string | undefined;
};

/** @internal */
export const UploadResponse$outboundSchema: z.ZodType<
  UploadResponse$Outbound,
  z.ZodTypeDef,
  UploadResponse
> = z.object({
  url: z.string().optional(),
  secureUrl: z.string().optional(),
  publicId: z.string().optional(),
  version: z.number().int().optional(),
  versionId: z.string().optional(),
  signature: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  assetId: z.string().optional(),
  format: z.string().optional(),
  resourceType: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  context: z.nullable(ContextFullResponse$outboundSchema).optional(),
  metadata: z.record(z.any()).optional(),
  pages: z.number().int().optional(),
  bytes: z.number().int().optional(),
  type: z.string().optional(),
  etag: z.string().optional(),
  placeholder: z.boolean().optional(),
  originalFilename: z.string().optional(),
  imageMetadata: z.lazy(() => UploadResponseImageMetadata$outboundSchema)
    .optional(),
  illustrationScore: z.number().optional(),
  semiTransparent: z.boolean().optional(),
  grayscale: z.boolean().optional(),
  faces: z.nullable(z.array(z.array(z.number().int()))).optional(),
  coordinates: z.nullable(CoordinatesResponse$outboundSchema).optional(),
  eager: z.array(z.lazy(() => Eager$outboundSchema)).optional(),
  assetFolder: z.nullable(z.string()).optional(),
  displayName: z.string().optional(),
  apiKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    secureUrl: "secure_url",
    publicId: "public_id",
    versionId: "version_id",
    assetId: "asset_id",
    resourceType: "resource_type",
    createdAt: "created_at",
    originalFilename: "original_filename",
    imageMetadata: "image_metadata",
    illustrationScore: "illustration_score",
    semiTransparent: "semi_transparent",
    assetFolder: "asset_folder",
    displayName: "display_name",
    apiKey: "api_key",
  });
});

export function uploadResponseToJSON(uploadResponse: UploadResponse): string {
  return JSON.stringify(UploadResponse$outboundSchema.parse(uploadResponse));
}
export function uploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<UploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadResponse' from JSON`,
  );
}
