/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of resource to upload:
 *
 * @remarks
 * - "image" for uploading strictly images
 * - "video" for uploading strictly videos
 * - "raw" for uploading non-media files
 * - "auto" for allowing Cloudinary to automatically detect the type of the uploaded file
 */
export const UploadResourceType = {
  Image: "image",
  Video: "video",
  Raw: "raw",
  Auto: "auto",
} as const;
/**
 * The type of resource to upload:
 *
 * @remarks
 * - "image" for uploading strictly images
 * - "video" for uploading strictly videos
 * - "raw" for uploading non-media files
 * - "auto" for allowing Cloudinary to automatically detect the type of the uploaded file
 */
export type UploadResourceType = ClosedEnum<typeof UploadResourceType>;

/** @internal */
export const UploadResourceType$inboundSchema: z.ZodNativeEnum<
  typeof UploadResourceType
> = z.nativeEnum(UploadResourceType);
/** @internal */
export const UploadResourceType$outboundSchema: z.ZodNativeEnum<
  typeof UploadResourceType
> = UploadResourceType$inboundSchema;
