/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Transformations = {
  /**
   * Number of transformations used
   */
  usage?: number | undefined;
};

export type Objects = {
  /**
   * Number of objects used
   */
  usage?: number | undefined;
  /**
   * Object limit for the plan
   */
  limit?: number | undefined;
  /**
   * Percentage of object limit used
   */
  usedPercent?: number | undefined;
};

export type Bandwidth = {
  /**
   * Bandwidth used in bytes
   */
  usage?: number | undefined;
  /**
   * Bandwidth limit for the plan
   */
  limit?: number | undefined;
  /**
   * Percentage of bandwidth limit used
   */
  usedPercent?: number | undefined;
};

export type UsageResponseStorage = {
  /**
   * Storage used in bytes
   */
  usage?: number | undefined;
  /**
   * Storage limit for the plan
   */
  limit?: number | undefined;
  /**
   * Percentage of storage limit used
   */
  usedPercent?: number | undefined;
};

export type Impressions = {
  /**
   * Number of impressions used
   */
  usage?: number | undefined;
};

export type SecondsDelivered = {
  /**
   * Number of seconds delivered
   */
  usage?: number | undefined;
};

/**
 * Upload size and pixel limits
 */
export type MediaLimits = {
  /**
   * Maximum size for images in bytes
   */
  imageMaxSizeBytes?: number | undefined;
  /**
   * Maximum size for videos in bytes
   */
  videoMaxSizeBytes?: number | undefined;
  /**
   * Maximum size for raw files in bytes
   */
  rawMaxSizeBytes?: number | undefined;
  /**
   * Maximum pixels for images
   */
  imageMaxPx?: number | undefined;
  /**
   * Maximum total pixels for assets
   */
  assetMaxTotalPx?: number | undefined;
};

export type UsageResponse = {
  /**
   * The current plan name
   */
  plan?: string | undefined;
  /**
   * When the usage data was last updated
   */
  lastUpdated?: RFCDate | undefined;
  /**
   * The date for which usage was requested
   */
  dateRequested?: Date | undefined;
  transformations?: Transformations | undefined;
  objects?: Objects | undefined;
  bandwidth?: Bandwidth | undefined;
  storage?: UsageResponseStorage | undefined;
  impressions?: Impressions | undefined;
  secondsDelivered?: SecondsDelivered | undefined;
  /**
   * Number of resources stored
   */
  resources?: number | undefined;
  /**
   * Number of derived resources
   */
  derivedResources?: number | undefined;
  /**
   * Number of requests made
   */
  requests?: number | undefined;
  /**
   * Upload size and pixel limits
   */
  mediaLimits?: MediaLimits | undefined;
};

/** @internal */
export const Transformations$inboundSchema: z.ZodType<
  Transformations,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.number().int().optional(),
});
/** @internal */
export type Transformations$Outbound = {
  usage?: number | undefined;
};

/** @internal */
export const Transformations$outboundSchema: z.ZodType<
  Transformations$Outbound,
  z.ZodTypeDef,
  Transformations
> = z.object({
  usage: z.number().int().optional(),
});

export function transformationsToJSON(
  transformations: Transformations,
): string {
  return JSON.stringify(Transformations$outboundSchema.parse(transformations));
}
export function transformationsFromJSON(
  jsonString: string,
): SafeParseResult<Transformations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transformations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transformations' from JSON`,
  );
}

/** @internal */
export const Objects$inboundSchema: z.ZodType<Objects, z.ZodTypeDef, unknown> =
  z.object({
    usage: z.number().int().optional(),
    limit: z.number().int().optional(),
    used_percent: z.number().optional(),
  }).transform((v) => {
    return remap$(v, {
      "used_percent": "usedPercent",
    });
  });
/** @internal */
export type Objects$Outbound = {
  usage?: number | undefined;
  limit?: number | undefined;
  used_percent?: number | undefined;
};

/** @internal */
export const Objects$outboundSchema: z.ZodType<
  Objects$Outbound,
  z.ZodTypeDef,
  Objects
> = z.object({
  usage: z.number().int().optional(),
  limit: z.number().int().optional(),
  usedPercent: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    usedPercent: "used_percent",
  });
});

export function objectsToJSON(objects: Objects): string {
  return JSON.stringify(Objects$outboundSchema.parse(objects));
}
export function objectsFromJSON(
  jsonString: string,
): SafeParseResult<Objects, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Objects$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Objects' from JSON`,
  );
}

/** @internal */
export const Bandwidth$inboundSchema: z.ZodType<
  Bandwidth,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.number().int().optional(),
  limit: z.number().int().optional(),
  used_percent: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "used_percent": "usedPercent",
  });
});
/** @internal */
export type Bandwidth$Outbound = {
  usage?: number | undefined;
  limit?: number | undefined;
  used_percent?: number | undefined;
};

/** @internal */
export const Bandwidth$outboundSchema: z.ZodType<
  Bandwidth$Outbound,
  z.ZodTypeDef,
  Bandwidth
> = z.object({
  usage: z.number().int().optional(),
  limit: z.number().int().optional(),
  usedPercent: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    usedPercent: "used_percent",
  });
});

export function bandwidthToJSON(bandwidth: Bandwidth): string {
  return JSON.stringify(Bandwidth$outboundSchema.parse(bandwidth));
}
export function bandwidthFromJSON(
  jsonString: string,
): SafeParseResult<Bandwidth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bandwidth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bandwidth' from JSON`,
  );
}

/** @internal */
export const UsageResponseStorage$inboundSchema: z.ZodType<
  UsageResponseStorage,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.number().int().optional(),
  limit: z.number().int().optional(),
  used_percent: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "used_percent": "usedPercent",
  });
});
/** @internal */
export type UsageResponseStorage$Outbound = {
  usage?: number | undefined;
  limit?: number | undefined;
  used_percent?: number | undefined;
};

/** @internal */
export const UsageResponseStorage$outboundSchema: z.ZodType<
  UsageResponseStorage$Outbound,
  z.ZodTypeDef,
  UsageResponseStorage
> = z.object({
  usage: z.number().int().optional(),
  limit: z.number().int().optional(),
  usedPercent: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    usedPercent: "used_percent",
  });
});

export function usageResponseStorageToJSON(
  usageResponseStorage: UsageResponseStorage,
): string {
  return JSON.stringify(
    UsageResponseStorage$outboundSchema.parse(usageResponseStorage),
  );
}
export function usageResponseStorageFromJSON(
  jsonString: string,
): SafeParseResult<UsageResponseStorage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageResponseStorage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageResponseStorage' from JSON`,
  );
}

/** @internal */
export const Impressions$inboundSchema: z.ZodType<
  Impressions,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.number().int().optional(),
});
/** @internal */
export type Impressions$Outbound = {
  usage?: number | undefined;
};

/** @internal */
export const Impressions$outboundSchema: z.ZodType<
  Impressions$Outbound,
  z.ZodTypeDef,
  Impressions
> = z.object({
  usage: z.number().int().optional(),
});

export function impressionsToJSON(impressions: Impressions): string {
  return JSON.stringify(Impressions$outboundSchema.parse(impressions));
}
export function impressionsFromJSON(
  jsonString: string,
): SafeParseResult<Impressions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Impressions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Impressions' from JSON`,
  );
}

/** @internal */
export const SecondsDelivered$inboundSchema: z.ZodType<
  SecondsDelivered,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.number().int().optional(),
});
/** @internal */
export type SecondsDelivered$Outbound = {
  usage?: number | undefined;
};

/** @internal */
export const SecondsDelivered$outboundSchema: z.ZodType<
  SecondsDelivered$Outbound,
  z.ZodTypeDef,
  SecondsDelivered
> = z.object({
  usage: z.number().int().optional(),
});

export function secondsDeliveredToJSON(
  secondsDelivered: SecondsDelivered,
): string {
  return JSON.stringify(
    SecondsDelivered$outboundSchema.parse(secondsDelivered),
  );
}
export function secondsDeliveredFromJSON(
  jsonString: string,
): SafeParseResult<SecondsDelivered, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecondsDelivered$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecondsDelivered' from JSON`,
  );
}

/** @internal */
export const MediaLimits$inboundSchema: z.ZodType<
  MediaLimits,
  z.ZodTypeDef,
  unknown
> = z.object({
  image_max_size_bytes: z.number().int().optional(),
  video_max_size_bytes: z.number().int().optional(),
  raw_max_size_bytes: z.number().int().optional(),
  image_max_px: z.number().int().optional(),
  asset_max_total_px: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "image_max_size_bytes": "imageMaxSizeBytes",
    "video_max_size_bytes": "videoMaxSizeBytes",
    "raw_max_size_bytes": "rawMaxSizeBytes",
    "image_max_px": "imageMaxPx",
    "asset_max_total_px": "assetMaxTotalPx",
  });
});
/** @internal */
export type MediaLimits$Outbound = {
  image_max_size_bytes?: number | undefined;
  video_max_size_bytes?: number | undefined;
  raw_max_size_bytes?: number | undefined;
  image_max_px?: number | undefined;
  asset_max_total_px?: number | undefined;
};

/** @internal */
export const MediaLimits$outboundSchema: z.ZodType<
  MediaLimits$Outbound,
  z.ZodTypeDef,
  MediaLimits
> = z.object({
  imageMaxSizeBytes: z.number().int().optional(),
  videoMaxSizeBytes: z.number().int().optional(),
  rawMaxSizeBytes: z.number().int().optional(),
  imageMaxPx: z.number().int().optional(),
  assetMaxTotalPx: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    imageMaxSizeBytes: "image_max_size_bytes",
    videoMaxSizeBytes: "video_max_size_bytes",
    rawMaxSizeBytes: "raw_max_size_bytes",
    imageMaxPx: "image_max_px",
    assetMaxTotalPx: "asset_max_total_px",
  });
});

export function mediaLimitsToJSON(mediaLimits: MediaLimits): string {
  return JSON.stringify(MediaLimits$outboundSchema.parse(mediaLimits));
}
export function mediaLimitsFromJSON(
  jsonString: string,
): SafeParseResult<MediaLimits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaLimits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaLimits' from JSON`,
  );
}

/** @internal */
export const UsageResponse$inboundSchema: z.ZodType<
  UsageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  plan: z.string().optional(),
  last_updated: z.string().transform(v => new RFCDate(v)).optional(),
  date_requested: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  transformations: z.lazy(() => Transformations$inboundSchema).optional(),
  objects: z.lazy(() => Objects$inboundSchema).optional(),
  bandwidth: z.lazy(() => Bandwidth$inboundSchema).optional(),
  storage: z.lazy(() => UsageResponseStorage$inboundSchema).optional(),
  impressions: z.lazy(() => Impressions$inboundSchema).optional(),
  seconds_delivered: z.lazy(() => SecondsDelivered$inboundSchema).optional(),
  resources: z.number().int().optional(),
  derived_resources: z.number().int().optional(),
  requests: z.number().int().optional(),
  media_limits: z.lazy(() => MediaLimits$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "last_updated": "lastUpdated",
    "date_requested": "dateRequested",
    "seconds_delivered": "secondsDelivered",
    "derived_resources": "derivedResources",
    "media_limits": "mediaLimits",
  });
});
/** @internal */
export type UsageResponse$Outbound = {
  plan?: string | undefined;
  last_updated?: string | undefined;
  date_requested?: string | undefined;
  transformations?: Transformations$Outbound | undefined;
  objects?: Objects$Outbound | undefined;
  bandwidth?: Bandwidth$Outbound | undefined;
  storage?: UsageResponseStorage$Outbound | undefined;
  impressions?: Impressions$Outbound | undefined;
  seconds_delivered?: SecondsDelivered$Outbound | undefined;
  resources?: number | undefined;
  derived_resources?: number | undefined;
  requests?: number | undefined;
  media_limits?: MediaLimits$Outbound | undefined;
};

/** @internal */
export const UsageResponse$outboundSchema: z.ZodType<
  UsageResponse$Outbound,
  z.ZodTypeDef,
  UsageResponse
> = z.object({
  plan: z.string().optional(),
  lastUpdated: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  dateRequested: z.date().transform(v => v.toISOString()).optional(),
  transformations: z.lazy(() => Transformations$outboundSchema).optional(),
  objects: z.lazy(() => Objects$outboundSchema).optional(),
  bandwidth: z.lazy(() => Bandwidth$outboundSchema).optional(),
  storage: z.lazy(() => UsageResponseStorage$outboundSchema).optional(),
  impressions: z.lazy(() => Impressions$outboundSchema).optional(),
  secondsDelivered: z.lazy(() => SecondsDelivered$outboundSchema).optional(),
  resources: z.number().int().optional(),
  derivedResources: z.number().int().optional(),
  requests: z.number().int().optional(),
  mediaLimits: z.lazy(() => MediaLimits$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    lastUpdated: "last_updated",
    dateRequested: "date_requested",
    secondsDelivered: "seconds_delivered",
    derivedResources: "derived_resources",
    mediaLimits: "media_limits",
  });
});

export function usageResponseToJSON(usageResponse: UsageResponse): string {
  return JSON.stringify(UsageResponse$outboundSchema.parse(usageResponse));
}
export function usageResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageResponse' from JSON`,
  );
}
